import { McpServer } from '@modelcontextprotocol/server';
import { z } from 'zod';
import * as S from './schemas.mjs';
import * as P from '../src/creation/project.js';
import * as C from '../src/creation/compose.js';
import { renderPlan } from '../src/creation/render.js';
const obj = fields => z.object(fields).strict();
const reply = (status, data) => ({ content: [{ type: 'text', text: JSON.stringify({ status, data }) }], structuredContent: { status, data } });
const wrapProject = p => ({ project: p });
export function createServer(adapters = {}) {
  const server = new McpServer({ name: 'aurora-mcp', version: P.VERSION }, { capabilities: { tools: {}, resources: {}, prompts: {} }, instructions: 'Compose music, sound and SFX with five Beethoven-inspired axes. Projects are client-owned immutable values: retain the returned project, pass it to the next tool, and save snapshots for undo/redo. No historical attribution is implied. First inspect get_capabilities and catalog. Rendered WAV is artifact-ready only after successful rendering; queued browser jobs need the user to open their render URL. No universal aesthetic or client compatibility guarantee.' });
  const register = (name, description, schema, run, readOnly = true) => server.registerTool(name, {
    description, inputSchema: schema, outputSchema: S.Output,
    annotations: { readOnlyHint: readOnly, destructiveHint: false, idempotentHint: readOnly, openWorldHint: !readOnly },
  }, async (args, ctx) => {
    try { const data = await run(args, ctx); return reply(data?.status || 'validated', data); }
    catch (error) { return { ...reply('error', { code: error.code || 'INVALID_ARGUMENT', message: error.message }), isError: true }; }
  });
  const capabilities = () => ({ version: P.VERSION, protocol: ['2026-07-28', '2025-11-25', '2025-06-18'], axes: P.AXES, limits: P.LIMITS,
    render: adapters.renderMode || 'unavailable', renderLimits: adapters.renderLimits || P.LIMITS, browserControl: !!adapters.browserCommand,
    output: ['stereo PCM WAV 16/24-bit', 'versioned project JSON', 'synth preset JSON', 'metrics JSON'],
    usage: 'Standard MCP clients only. Public tools hold no user library or private browser state. Client-owned project snapshots support undo/redo. Project JSON preserves automation and seed.' });
  register('get_capabilities', 'Inspect actual rendering mode, limits and five creative axes before using tools.', obj({}), capabilities);
  register('get_catalog', 'List all factory presets, categories, demo songs, tours, moods, phrases, Jam styles and SFX recipes.', obj({}), () => C.catalog());
  register('get_parameter_schema', 'Get all 235 native-unit parameter definitions, ranges, enums, globals and modulation destinations.', obj({}), () => ({ parameters: P.parameterSchema() }));
  register('get_preset', 'Get an editable factory synth patch with macro definitions.', obj({ name: z.string() }), a => ({ patch: P.patchFromPreset(a.name) }));
  register('create_project', 'Create a versioned music/sound/SFX project from five creative axes and optional custom patch. Then compose_music or set_track to add notes.', S.Create, a => wrapProject(P.createProject(a)));
  register('compose_music', 'Develop the explicit motif through repetition, transposition, inversion, augmentation or fragmentation; quantise pitches to the selected scale and apply tension and expressive velocity.', S.ProjectInput, a => wrapProject(C.compose(a.project)));
  register('design_sound_effect', 'Create impact, whoosh, riser, downer, ambience, UI tone, alarm, footstep or laser with editable notes and filter/pitch automation.', obj({ type: z.enum(C.SFX_TYPES), seconds: z.number().min(0.1).max(30).optional(), title: z.string().max(100).optional(), seed: z.number().int().min(1).max(4294967295).optional(), axes: S.Axes.optional() }), a => wrapProject(C.designSfx(a)));
  register('update_axes', 'Update selected creative axes. Recompose to apply motive/rhythm/harmony/expression to notes; use apply_timbre to map sound controls. Tempo is synchronized; bars change length only when explicitly supplied.', obj({ project: S.Project, axes: S.Axes, expectedRevision: z.number().int().optional() }), a => wrapProject(P.edited(a.project, p => { p.axes = P.axesWithDefaults(Object.fromEntries(Object.keys(P.AXES).map(k => [k, { ...p.axes[k], ...a.axes[k] }]))); if(a.axes.rhythm?.bpm!==undefined)p.globals['global.bpm']=p.axes.rhythm.bpm;if(a.axes.rhythm?.bars!==undefined)p.lengthBeats=p.axes.rhythm.bars*4; }, a.expectedRevision)));
  register('apply_timbre', 'Apply current brightness, attack, release, space and width to a track without replacing its engine or macro definitions.', obj({ project: S.Project, index: S.Index }), a => { const t = a.project.axes.timbre; return wrapProject(P.setParameters(a.project, { 'filter.cutoff': 120 * (16000 / 120) ** t.brightness, 'aenv.a': t.attack, 'aenv.r': t.release, 'reverb.on': t.space > 0, 'reverb.mix': t.space * 0.5, 'voice.spread': t.width }, a.index)); });
  register('set_parameters', 'Batch edit any native synth parameter, including all engines, envelopes, eight modulation routes, chord/arp, scale, tempo and FX. Global values are stored separately.', obj({ project: S.Project, values: S.Params, index: S.Index, expectedRevision: z.number().int().optional() }), a => wrapProject(P.setParameters(a.project, a.values, a.index, a.expectedRevision)));
  register('set_macros', 'Set four macro knob values. Macro mappings are edited through set_track.patch.', obj({ project: S.Project, values: z.array(z.number().min(0).max(1)).length(4), index: S.Index }), a => wrapProject(P.setParameters(a.project, Object.fromEntries(a.values.map((v, i) => ['macro' + (i + 1), v])), a.index)));
  register('set_track', 'Edit a track patch, notes, beat-based parameter/macro/controller automation, gain, pan or mute. Notes use MIDI pitch, velocity and duration in beats.', obj({ project: S.Project, index: S.Index, changes: S.Track.partial().strict(), expectedRevision: z.number().int().optional() }), a => wrapProject(P.setTrack(a.project, a.index, a.changes, a.expectedRevision)));
  register('add_track', 'Add a synth/percussion/texture track to the multi-part composition, up to eight tracks.', obj({ project: S.Project, track: S.Track }), a => wrapProject(P.addTrack(a.project, a.track)));
  register('remove_track', 'Remove one track from the returned copy; input project stays available for undo.', obj({ project: S.Project, index: S.Index }), a => wrapProject(P.edited(a.project, p => { P.track(p, a.index); p.tracks.splice(a.index, 1); })));
  register('resize_project', 'Explicitly set total beats; refuses notes beyond the new endpoint instead of silently truncating them.', obj({ project: S.Project, lengthBeats: z.number().min(0.05).max(720) }), a => wrapProject(P.edited(a.project, p => { p.lengthBeats = a.lengthBeats; })));
  register('apply_mood', 'Use all website magic moods or its Chinese/English mood parser, e.g. 更暗、再寬一點.', obj({ project: S.Project, moods: z.union([z.string().max(300), z.array(z.string()).min(1).max(8)]), amount: z.number().min(0.05).max(1).default(0.6), index: S.Index }), a => wrapProject(C.moodProject(a.project, a.moods, a.amount, a.index)));
  register('morph_patch', 'Blend with any factory preset using the same normalized and macro-aware Morph math as the website.', obj({ project: S.Project, preset: z.string(), position: z.number().min(0).max(1), index: S.Index }), a => wrapProject(C.morphProject(a.project, a.preset, a.position, a.index)));
  register('mutate_patch', 'Seeded subtle mutation or full random patch using the website sound-design generator.', obj({ project: S.Project, amount: z.number().min(0).max(1).optional(), seed: z.number().int().min(1).max(4294967295).optional(), random: z.boolean().optional(), index: S.Index }), a => wrapProject(C.mutateProject(a.project, a)));
  register('evolve_sound', 'Generate explicit seeded automation drift; returning a project makes the evolution renderable and reproducible.', obj({ project: S.Project, amount: z.number().min(0).max(0.5).optional(), steps: z.number().int().min(2).max(128).optional(), index: S.Index }), a => wrapProject(C.evolveProject(a.project, a)));
  register('generate_jam', 'Generate a multi-part musical arrangement using any of the seven website Jam styles, seeded harmony, drums, bass and lead.', obj({ title: z.string().max(100).optional(), style: z.enum(C.catalog().styles).optional(), seed: z.number().int().min(1).max(4294967295).optional(), axes: S.Axes.optional() }), a => wrapProject(C.jamProject(a)));
  register('load_demo_song', 'Load any of the six complete website demo songs as editable tracks, or explicitly choose an excerpt length in beats.', obj({ id: z.string(), excerptBeats: z.number().min(0.05).max(720).optional() }), a => wrapProject(C.loadSong(a.id, a.excerptBeats)));
  register('load_tour', 'Recreate one of six sound-design tours as its final patch or complete sampled parameter timeline.', obj({ id: z.string(), mode: z.enum(['final', 'timeline']).default('final') }), a => wrapProject(C.loadTour(a.id, a.mode)));
  register('apply_phrase', 'Load any website preset audition phrase into a track.', obj({ project: S.Project, phrase: z.string(), index: S.Index }), a => wrapProject(C.applyPhrase(a.project, a.phrase, a.index)));
  register('validate_project', 'Validate the project and planned memory/output budget without consuming a rendering job.', obj({ project: S.Project, options: S.RenderOptions.optional() }), a => ({ project: P.validateProject(a.project), plan: renderPlan(a.project, a.options) }));
  register('render_audio', 'Render a validated composition to downloadable WAV plus metrics. Inspect rendering mode first: local Node renders directly; cloud browser mode queues a user-operated browser render.', obj({ project: S.Project, options: S.RenderOptions.optional() }), async (a, ctx) => { renderPlan(a.project, a.options); if (!adapters.render) P.fail('RENDER_UNAVAILABLE', 'No renderer configured'); return adapters.render(a.project, a.options || {}, ctx); }, false);
  register('get_render_result', 'Get the current render job state and download locations. Node computes audio metrics; cloud metrics are browser-reported, with verified WAV header and received-byte SHA-256.', obj({ id: z.string().min(1).max(100) }), a => adapters.result ? adapters.result(a.id) : { status: 'unavailable' });
  register('export_project', 'Get complete project and selected-track preset JSON for reuse, saving, website import and client-side undo/redo.', obj({ project: S.Project, index: S.Index }), a => { P.validateProject(a.project); return { project: a.project, preset: P.track(a.project, a.index).patch, license: 'Synth engine MIT, copyright 2026 pixbvr; generated work rights depend on supplied material. Keep engine attribution with redistributed engine code.' }; });
  if (adapters.browserCommand) register('browser_command', 'Operate an explicitly enabled browser studio room: apply_project, play_project or stop. Reports queued/applied states separately; audio playback needs a user gesture.', obj({ room: z.string().max(100), requestId: z.string().min(1).max(100), action: z.enum(['apply_project', 'play_project', 'stop']), project: S.Project.optional() }), a => adapters.browserCommand(a), false);
  for (const [name, uri, data] of [['creative-axes', 'aurora://axes', P.AXES], ['catalog', 'aurora://catalog', C.catalog()], ['parameters', 'aurora://parameters', P.parameterSchema()], ['capabilities', 'aurora://capabilities', capabilities()]]) {
    server.registerResource(name, uri, { mimeType: 'application/json', description: name }, async u => ({ contents: [{ uri: u.href, mimeType: 'application/json', text: JSON.stringify(data) }] }));
  }
  if (adapters.readArtifact) adapters.registerResources?.(server);
  server.registerPrompt('scene_sound', { description: 'Translate a scene into five creative axes, then create, revise and export music or sound effects.', argsSchema: obj({ scene: z.string().min(1).max(500), duration: z.string().optional() }) }, async a => ({ messages: [{ role: 'user', content: { type: 'text', text: 'Create a reusable sound for: ' + a.scene + '. Desired duration: ' + (a.duration || 'choose a bounded duration') + '. Inspect capabilities and catalog. Specify motive/development, rhythm/tension, harmony/pitch (atonal where appropriate), dynamics/expression, timbre/space. Use compose_music, generate_jam or design_sound_effect, then edit native parameters and automation. Validate and render. Report real artifact state, metrics and tail warnings. Retain project JSON and explain any user gesture needed.' } }] }));
  return server;
}
