// Arp & Groove 琶音/律動 — factory presets.
// Every preset turns the arpeggiator on: hold a chord (or press ▶ Demo) and it plays itself.
// Tempo-synced delays/LFOs follow the global tempo; macros may ride arp gate/swing and mod depths.
export default [
  // ── 1. Flagship: Berlin-school sequence with a glassy FM ping on every step ──
  {
    name: 'Borealis Sequencer',
    category: 'arp',
    tags: ['berlin-school', 'sequence', 'analog', 'evolving'],
    description: '柏林學派的十六分音符序列：鋸齒波穿過會呼吸的階梯濾波器，每一步都閃著玻璃般的 FM 微光，回聲在左右聲道間流轉',
    params: {
      'arp.on': true, 'arp.oct': 2, 'arp.gate': 0.5,
      'osc1.unison': 2, 'osc1.detune': 0.1, 'osc1.spread': 0.5, 'osc1.drift': 0.2, 'osc1.level': 0.75,
      'osc2.on': true, 'osc2.shape': 1, 'osc2.pw': 0.4, 'osc2.oct': -1, 'osc2.fine': 5, 'osc2.level': 0.4,
      'fm.on': true, 'fm.level': 0.22, 'fm.filt': 0, 'fm.algo': 3,
      'fm.op1.ratio': 2, 'fm.op1.level': 0.9, 'fm.op1.d': 0.7, 'fm.op1.s': 0, 'fm.op1.vel': 0.5,
      'fm.op2.ratio': 7, 'fm.op2.level': 0.3, 'fm.op2.d': 0.25, 'fm.op2.s': 0, 'fm.op2.r': 0.2, 'fm.op2.vel': 0.7, 'fm.op2.kscale': -0.4,
      'fm.op3.ratio': 4, 'fm.op3.detune': 4, 'fm.op3.level': 0.35, 'fm.op3.d': 0.4, 'fm.op3.s': 0, 'fm.op3.r': 0.2, 'fm.op3.kscale': -0.3,
      'fm.op4.level': 0.2, 'fm.op4.d': 0.2, 'fm.op4.s': 0, 'fm.op4.r': 0.2,
      'filter.cutoff': 650, 'filter.res': 0.5, 'filter.drive': 0.25, 'filter.env': 0.5, 'filter.key': 0.4, 'filter.vel': 0.25,
      'fenv.a': 0.001, 'fenv.d': 0.22, 'fenv.s': 0, 'fenv.r': 0.15, 'fenv.curve': 0.3,
      'aenv.a': 0.001, 'aenv.d': 0.35, 'aenv.s': 0.35, 'aenv.r': 0.2,
      'lfo1.shape': 'sh', 'lfo1.sync': '1/16', 'lfo1.mode': 'mono',
      'lfo2.shape': 'tri', 'lfo2.sync': '4/1', 'lfo2.mode': 'mono', 'lfo2.phase': 0.75,
      'mod1.src': 'lfo1', 'mod1.dst': 'filter.cutoff', 'mod1.amt': 0.06,
      'mod2.src': 'lfo2', 'mod2.dst': 'filter.cutoff', 'mod2.amt': 0.08,
      'mod3.src': 'random', 'mod3.dst': 'amp.pan', 'mod3.amt': 0.18,
      'mod4.src': 'wheel', 'mod4.dst': 'filter.cutoff', 'mod4.amt': 0.25, 'vib.wheel': 0,
      'delay.on': true, 'delay.sync': '3/16', 'delay.feedback': 0.45, 'delay.pingpong': 0.9, 'delay.tone': 0.4, 'delay.wobble': 0.15, 'delay.mix': 0.24,
      'reverb.on': true, 'reverb.size': 0.75, 'reverb.decay': 3.5, 'reverb.mix': 0.24, 'reverb.predelay': 0.03,
      'comp.amount': 0.3,
      'amp.level': 3.6,
      'macro1': 0.25,
    },
    macros: [
      { name: '截止 Cutoff', targets: [{ id: 'filter.cutoff', amount: 0.4 }] },
      { name: '酸度 Acid', targets: [{ id: 'filter.res', amount: 0.4 }, { id: 'filter.env', amount: 0.15 }, { id: 'filter.drive', amount: 0.3 }] },
      { name: '律動 Motion', targets: [{ id: 'mod1.amt', amount: 0.1 }, { id: 'arp.gate', amount: -0.25 }] },
      { name: '空間 Space', targets: [{ id: 'delay.mix', amount: 0.25 }, { id: 'delay.feedback', amount: 0.25 }, { id: 'reverb.mix', amount: 0.2 }, { id: 'reverb.decay', amount: 0.15 }] },
    ],
    demo: 'arp',
    demoMacros: [{ index: 0, to: 0.85, beat: 0, beats: 8 }, { index: 0, to: 0.25, beat: 8, beats: 8 }],
  },

  // ── 2. Trance gate: supersaw chords re-struck every 16th, jumping an octave each step ──
  {
    name: 'Hyperion Gate',
    category: 'arp',
    tags: ['trance', 'gated', 'supersaw', 'chord'],
    description: '整個和弦每個十六分音符重擊一次、上下八度交替跳動，超鋸齒波門控的經典 Trance 能量',
    params: {
      'arp.on': true, 'arp.mode': 'chord', 'arp.oct': 2, 'arp.gate': 0.45,
      'osc1.unison': 7, 'osc1.detune': 0.35, 'osc1.spread': 0.9, 'osc1.level': 0.7,
      'osc2.on': true, 'osc2.oct': -1, 'osc2.unison': 3, 'osc2.detune': 0.15, 'osc2.level': 0.35,
      'filter.type': 'lp', 'filter.cutoff': 3200, 'filter.res': 0.15, 'filter.env': 0.2, 'filter.key': 0.25,
      'fenv.a': 0.001, 'fenv.d': 0.15, 'fenv.s': 0, 'fenv.r': 0.1,
      'aenv.a': 0.002, 'aenv.d': 0.2, 'aenv.s': 0.6, 'aenv.r': 0.08, 'aenv.curve': 0.3,
      'lfo1.shape': 'ramp', 'lfo1.sync': '1/4', 'lfo1.mode': 'mono',
      'lfo2.sync': '4/1', 'lfo2.mode': 'mono', 'lfo2.phase': 0.75,
      'mod1.src': 'lfo1', 'mod1.dst': 'filter.cutoff', 'mod1.amt': 0.06,
      'mod2.src': 'lfo2', 'mod2.dst': 'filter.cutoff', 'mod2.amt': 0.06,
      'mod3.src': 'wheel', 'mod3.dst': 'filter.cutoff', 'mod3.amt': 0.2, 'vib.wheel': 0,
      'delay.on': true, 'delay.pingpong': 0.8, 'delay.tone': 0.45, 'delay.mix': 0.16,
      'reverb.on': true, 'reverb.size': 0.8, 'reverb.mix': 0.22,
      'comp.amount': 0.4,
      'amp.level': -1.5,
      'macro1': 0.2,
    },
    macros: [
      { name: '濾波 Filter', targets: [{ id: 'filter.cutoff', amount: 0.3 }, { id: 'filter.env', amount: 0.1 }] },
      { name: '門控 Gate', targets: [{ id: 'arp.gate', amount: 0.45 }, { id: 'aenv.r', amount: 0.15 }] },
      { name: '厚度 Detune', targets: [{ id: 'osc1.detune', amount: 0.35 }, { id: 'osc2.level', amount: 0.2 }] },
      { name: '空間 Space', targets: [{ id: 'reverb.mix', amount: 0.25 }, { id: 'delay.mix', amount: 0.2 }, { id: 'reverb.decay', amount: 0.15 }] },
    ],
    demo: 'arp',
    demoMacros: [{ index: 0, to: 1, beat: 0, beats: 12 }, { index: 0, to: 0.2, beat: 12, beats: 4 }],
  },

  // ── 3. Crystal bell cascade (FM bells + shimmer) ──
  {
    name: 'Snowglobe Cascade',
    category: 'arp',
    tags: ['bell', 'fm', 'crystal', 'shimmer'],
    description: '搖一搖水晶球：FM 鐘聲上下迴旋，乒乓回聲與微光殘響像雪花緩緩落下',
    params: {
      'arp.on': true, 'arp.mode': 'updown', 'arp.oct': 2,
      'osc1.on': false,
      'fm.on': true, 'fm.filt': 0, 'fm.algo': 3,
      'fm.op1.level': 0.9, 'fm.op1.d': 2.2, 'fm.op1.s': 0, 'fm.op1.r': 1.2, 'fm.op1.vel': 0.35,
      'fm.op2.ratio': 3.5, 'fm.op2.level': 0.38, 'fm.op2.d': 0.8, 'fm.op2.s': 0, 'fm.op2.r': 0.8, 'fm.op2.vel': 0.6, 'fm.op2.kscale': -0.35,
      'fm.op3.ratio': 2, 'fm.op3.detune': 6, 'fm.op3.level': 0.45, 'fm.op3.d': 1.4, 'fm.op3.s': 0, 'fm.op3.r': 1, 'fm.op3.vel': 0.4, 'fm.op3.kscale': -0.2,
      'fm.op4.ratio': 5, 'fm.op4.detune': -4, 'fm.op4.level': 0.28, 'fm.op4.d': 0.5, 'fm.op4.s': 0, 'fm.op4.r': 0.5, 'fm.op4.vel': 0.6, 'fm.op4.kscale': -0.35,
      'filter.on': false,
      'aenv.a': 0, 'aenv.d': 10, 'aenv.s': 1, 'aenv.r': 1.4,
      'vib.depth': 4, 'vib.rate': 4.5, 'vib.delay': 0.2,
      'mod1.src': 'random', 'mod1.dst': 'amp.pan', 'mod1.amt': 0.25,
      'mod2.src': 'wheel', 'mod2.dst': 'fm.feedback', 'mod2.amt': 0.3,
      'delay.on': true, 'delay.feedback': 0.4, 'delay.pingpong': 1, 'delay.tone': 0.55, 'delay.mix': 0.24,
      'reverb.on': true, 'reverb.size': 0.85, 'reverb.decay': 5, 'reverb.damp': 0.35, 'reverb.shimmer': 0.25, 'reverb.predelay': 0.04,
      'eq.high': -1.5,
      'amp.level': 2.2,
    },
    macros: [
      { name: '亮度 Bright', targets: [{ id: 'fm.op2.level', amount: 0.2 }, { id: 'fm.op4.level', amount: 0.2 }] },
      { name: '餘韻 Ring', targets: [{ id: 'fm.op1.d', amount: 0.2 }, { id: 'fm.op3.d', amount: 0.2 }, { id: 'aenv.r', amount: 0.15 }] },
      { name: '微光 Shimmer', targets: [{ id: 'reverb.shimmer', amount: 0.5 }, { id: 'reverb.mix', amount: 0.15 }] },
      { name: '回聲 Echo', targets: [{ id: 'delay.mix', amount: 0.25 }, { id: 'delay.feedback', amount: 0.2 }] },
    ],
    demo: 'arp',
    demoMacros: [{ index: 0, to: 1, beat: 0, beats: 8 }, { index: 0, to: 0, beat: 8, beats: 8 }, { index: 2, to: 0.8, beat: 4, beats: 8 }, { index: 2, to: 0, beat: 12, beats: 4 }],
  },

  // ── 4. Koto pluck with dotted-eighth ping-pong ──
  {
    name: 'Paper Lantern Echoes',
    category: 'arp',
    tags: ['pluck', 'koto', 'ping-pong', 'physical'],
    description: '物理模型古箏撥弦由高而下，附點八分的乒乓回聲在夜空中交織成紙燈籠般的光點',
    params: {
      'arp.on': true, 'arp.mode': 'down', 'arp.rate': '1/8', 'arp.oct': 2, 'arp.gate': 0.5,
      'osc1.on': false,
      'phys.on': true, 'phys.level': 1, 'phys.hardness': 0.75, 'phys.position': 0.08, 'phys.decay': 2.6,
      'phys.brightness': 0.68, 'phys.inharm': 0.14, 'phys.body': 0.35, 'phys.spread': 0.35, 'phys.damp': 0.45,
      'phys.filt': 1, 'filter.type': 'hp', 'filter.cutoff': 110, 'filter.res': 0, 'filter.key': 0,
      'filter2.type': 'lp', 'filter2.cutoff': 10000, 'filter2.res': 0,
      'aenv.a': 0, 'aenv.d': 10, 'aenv.s': 1, 'aenv.r': 1.5,
      'mod1.src': 'random', 'mod1.dst': 'phys.position', 'mod1.amt': 0.05,
      'mod2.src': 'wheel', 'mod2.dst': 'phys.brightness', 'mod2.amt': 0.3,
      'mod3.src': 'note', 'mod3.dst': 'phys.brightness', 'mod3.amt': -0.25,
      'delay.on': true, 'delay.feedback': 0.45, 'delay.pingpong': 1, 'delay.tone': 0.45, 'delay.wobble': 0.2, 'delay.mix': 0.3,
      'reverb.on': true, 'reverb.size': 0.55, 'reverb.decay': 2.5, 'reverb.mix': 0.2,
      'comp.amount': 0.25,
      'amp.level': 5.8,
    },
    macros: [
      { name: '音色 Tone', targets: [{ id: 'phys.brightness', amount: 0.25 }, { id: 'phys.hardness', amount: 0.2 }] },
      { name: '延音 Sustain', targets: [{ id: 'phys.decay', amount: 0.25 }, { id: 'phys.damp', amount: -0.35 }] },
      { name: '回聲 Echo', targets: [{ id: 'delay.mix', amount: 0.25 }, { id: 'delay.feedback', amount: 0.25 }] },
      { name: '搖擺 Swing', targets: [{ id: 'arp.swing', amount: 0.55 }, { id: 'phys.hardness', amount: -0.3 }, { id: 'delay.wobble', amount: 0.3 }] },
    ],
    demo: 'arp',
    demoMacros: [{ index: 3, to: 0.7, beat: 0, beats: 8 }, { index: 3, to: 0, beat: 8, beats: 8 }],
  },

  // ── 5. Random ambient: glass wavetable fireflies in a shimmer hall ──
  {
    name: 'Firefly Constellation',
    category: 'arp',
    tags: ['ambient', 'random', 'wavetable', 'shimmer'],
    description: '隨機跳躍的玻璃音點在三個八度間閃爍，每一顆音色與位置都不同，漂浮在微光殘響的星空裡',
    params: {
      'arp.on': true, 'arp.mode': 'random', 'arp.rate': '1/8', 'arp.oct': 3, 'arp.gate': 0.8,
      'osc1.mode': 'wavetable', 'osc1.table': 'glass', 'osc1.shape': 0.3, 'osc1.level': 0.7,
      'osc2.on': true, 'osc2.shape': 0, 'osc2.oct': 1, 'osc2.level': 0.3,
      'filter.type': 'lp', 'filter.cutoff': 2400, 'filter.res': 0.2, 'filter.key': 0.4, 'filter.vel': 0.2,
      'aenv.a': 0.008, 'aenv.d': 0.9, 'aenv.s': 0.15, 'aenv.r': 1.4,
      'vib.depth': 3, 'vib.rate': 5,
      'mod1.src': 'random', 'mod1.dst': 'osc1.shape', 'mod1.amt': 0.3,
      'mod2.src': 'random', 'mod2.dst': 'amp.pan', 'mod2.amt': 0.35,
      'mod3.src': 'random', 'mod3.dst': 'filter.cutoff', 'mod3.amt': 0.08,
      'mod4.src': 'wheel', 'mod4.dst': 'vib.depth', 'mod4.amt': 0.2,
      'delay.on': true, 'delay.sync': '1/4', 'delay.feedback': 0.5, 'delay.pingpong': 0.9, 'delay.tone': 0.35, 'delay.mix': 0.2,
      'reverb.on': true, 'reverb.size': 0.95, 'reverb.decay': 8, 'reverb.shimmer': 0.45, 'reverb.mix': 0.4, 'reverb.predelay': 0.05, 'reverb.mod': 0.5,
      'amp.level': 1.5,
    },
    macros: [
      { name: '閃爍 Twinkle', targets: [{ id: 'mod1.amt', amount: 0.25 }, { id: 'osc2.level', amount: 0.15 }] },
      { name: '亮度 Bright', targets: [{ id: 'filter.cutoff', amount: 0.3 }] },
      { name: '微光 Shimmer', targets: [{ id: 'reverb.shimmer', amount: 0.5 }] },
      { name: '空間 Space', targets: [{ id: 'reverb.mix', amount: 0.25 }, { id: 'reverb.decay', amount: 0.15 }, { id: 'delay.mix', amount: 0.2 }] },
    ],
    demo: 'arp',
    demoMacros: [{ index: 0, to: 1, beat: 0, beats: 8 }, { index: 0, to: 0, beat: 8, beats: 8 }],
  },

  // ── 6. Syncopated bass arp: dotted accents against straight 16ths ──
  {
    name: 'Midnight Freeway',
    category: 'arp',
    tags: ['bass', 'synthwave', 'syncopated'],
    description: '午夜公路上的低音琶音：直行的十六分音符被附點八分的重音切出切分律動，微微搖擺',
    params: {
      'arp.on': true, 'arp.gate': 0.7, 'arp.swing': 0.08,
      'osc1.oct': -1, 'osc1.unison': 2, 'osc1.detune': 0.08, 'osc1.spread': 0.3, 'osc1.drift': 0.15,
      'osc2.on': true, 'osc2.shape': 0.33, 'osc2.oct': -2, 'osc2.level': 0.55, 'osc2.filt': 0.5,
      'filter.cutoff': 320, 'filter.res': 0.5, 'filter.env': 0.55, 'filter.key': 0.4, 'filter.drive': 0.35, 'filter.vel': 0.2,
      'fenv.a': 0.001, 'fenv.d': 0.18, 'fenv.s': 0, 'fenv.r': 0.1, 'fenv.curve': 0.3,
      'aenv.a': 0.001, 'aenv.d': 0.25, 'aenv.s': 0.6, 'aenv.r': 0.06,
      'lfo1.shape': 'ramp', 'lfo1.sync': '1/8D', 'lfo1.mode': 'mono',
      'mod1.src': 'lfo1', 'mod1.dst': 'filter.cutoff', 'mod1.amt': 0.1,
      'mod2.src': 'wheel', 'mod2.dst': 'filter.cutoff', 'mod2.amt': 0.2, 'vib.wheel': 0,
      'drive.on': true, 'drive.type': 'tube', 'drive.amount': 0.25,
      'delay.on': true, 'delay.feedback': 0.25, 'delay.pingpong': 0.6, 'delay.tone': 0.3, 'delay.mix': 0.1,
      'comp.amount': 0.35,
      'amp.level': 4.4,
    },
    macros: [
      { name: '截止 Cutoff', targets: [{ id: 'filter.cutoff', amount: 0.3 }] },
      { name: '重音 Accent', targets: [{ id: 'mod1.amt', amount: 0.15 }, { id: 'filter.res', amount: 0.15 }] },
      { name: '咬勁 Grit', targets: [{ id: 'filter.drive', amount: 0.5 }, { id: 'drive.amount', amount: 0.5 }, { id: 'drive.tone', amount: 0.2 }, { id: 'filter.env', amount: 0.1 }] },
      { name: '搖擺 Swing', targets: [{ id: 'arp.swing', amount: 0.5 }] },
    ],
    demo: 'arp',
    demoMacros: [{ index: 1, to: 1, beat: 0, beats: 8 }, { index: 1, to: 0, beat: 8, beats: 8 }],
  },

  // ── 7. Chiptune ──
  {
    name: 'Pixel Quest',
    category: 'arp',
    tags: ['chiptune', '8-bit', 'retro'],
    description: '三十二分音符的 8-bit 急速琶音：窄脈衝方波緩緩掃動佔空比，配上短促回聲；轉開位元巨集，就回到老遊戲機的粗糙冒險關卡',
    params: {
      'arp.on': true, 'arp.rate': '1/32', 'arp.oct': 3, 'arp.gate': 0.8,
      'osc1.shape': 1, 'osc1.pw': 0.25, 'osc1.level': 0.6, 'osc1.drift': 0, 'osc1.phase': 'reset',
      'filter.type': 'lp', 'filter.cutoff': 7000, 'filter.res': 0, 'filter.key': 0,
      'aenv.a': 0.001, 'aenv.d': 0.1, 'aenv.s': 0.7, 'aenv.r': 0.03,
      'lfo1.shape': 'tri', 'lfo1.sync': '2/1', 'lfo1.mode': 'mono',
      'mod1.src': 'lfo1', 'mod1.dst': 'osc1.pw', 'mod1.amt': 0.12,
      'vib.rate': 7, 'vib.wheel': 60, 'vib.delay': 0,
      'drive.on': true, 'drive.type': 'crush', 'drive.amount': 0.35, 'drive.mix': 0,
      'delay.on': true, 'delay.sync': '1/8', 'delay.feedback': 0.3, 'delay.pingpong': 0.6, 'delay.tone': 0.6, 'delay.mix': 0.16,
      'reverb.on': true, 'reverb.size': 0.3, 'reverb.decay': 0.8, 'reverb.mix': 0.12,
      'eq.high': -2,
      'amp.level': 0.8,
    },
    macros: [
      { name: '脈寬 Duty', targets: [{ id: 'osc1.pw', amount: 0.28 }] },
      { name: '位元 Crush', targets: [{ id: 'drive.mix', amount: 0.8 }, { id: 'drive.amount', amount: 0.35 }] },
      { name: '音長 Gate', targets: [{ id: 'arp.gate', amount: -0.45 }] },
      { name: '回聲 Echo', targets: [{ id: 'delay.mix', amount: 0.25 }, { id: 'delay.feedback', amount: 0.25 }] },
    ],
    demo: 'arp',
    demoMacros: [{ index: 0, to: 1, beat: 0, beats: 8 }, { index: 0, to: 0, beat: 8, beats: 8 }, { index: 1, to: 0.8, beat: 8, beats: 4 }, { index: 1, to: 0, beat: 12, beats: 4 }],
  },

  // ── 8. Triplet vibraphone dream ──
  {
    name: 'Moonlit Carousel',
    category: 'arp',
    tags: ['dreamy', 'triplet', 'vibraphone'],
    description: '三連音的顫音琴在月光下旋轉，馬達顫音輕輕起伏，底下墊著一層柔軟的暖色和聲',
    params: {
      'arp.on': true, 'arp.rate': '1/16T', 'arp.oct': 2, 'arp.gate': 0.9, 'voice.poly': 16,
      'osc1.shape': 0.33, 'osc1.level': 0.18, 'osc1.oct': -1, 'osc1.unison': 2, 'osc1.detune': 0.15,
      'phys.on': true, 'phys.model': 'bar', 'phys.exciter': 'mallet', 'phys.position': 0.85,
      'phys.decay': 4, 'phys.brightness': 0.55, 'phys.inharm': 0.04, 'phys.body': 0.4, 'phys.spread': 0.5,
      'filter.type': 'lp', 'filter.cutoff': 900, 'filter.key': 0.5,
      'aenv.a': 0.003, 'aenv.d': 10, 'aenv.s': 1, 'aenv.r': 0.7,
      'lfo1.rate': 5, 'lfo1.mode': 'mono',
      'lfo2.sync': '1/2', 'lfo2.mode': 'mono',
      'mod1.src': 'lfo1', 'mod1.dst': 'phys.level', 'mod1.amt': 0.12,
      'mod2.src': 'lfo2', 'mod2.dst': 'amp.pan', 'mod2.amt': 0.2,
      'mod3.src': 'wheel', 'mod3.dst': 'lfo1.rate', 'mod3.amt': 0.08,
      'chorus.on': true, 'chorus.depth': 0.4, 'chorus.mix': 0.35,
      'delay.on': true, 'delay.sync': '1/4T', 'delay.pingpong': 0.7, 'delay.tone': 0.4, 'delay.mix': 0.16,
      'reverb.on': true, 'reverb.size': 0.75, 'reverb.decay': 3.5, 'reverb.mix': 0.28,
      'amp.level': -4.5,
    },
    macros: [
      { name: '顫音 Tremolo', targets: [{ id: 'mod1.amt', amount: 0.2 }, { id: 'lfo1.rate', amount: 0.1 }] },
      { name: '暖墊 Warmth', targets: [{ id: 'osc1.level', amount: 0.25 }, { id: 'filter.cutoff', amount: 0.15 }] },
      { name: '槌硬度 Mallet', targets: [{ id: 'phys.hardness', amount: 0.35 }, { id: 'phys.brightness', amount: 0.2 }] },
      { name: '空間 Space', targets: [{ id: 'reverb.mix', amount: 0.25 }, { id: 'delay.mix', amount: 0.2 }, { id: 'reverb.decay', amount: 0.15 }] },
    ],
    demo: 'arp',
    demoMacros: [{ index: 2, to: 0.9, beat: 0, beats: 8 }, { index: 2, to: 0, beat: 8, beats: 8 }, { index: 0, to: 1, beat: 8, beats: 4 }, { index: 0, to: 0, beat: 12, beats: 4 }],
  },

  // ── 9. Dark techno ──
  {
    name: 'Obsidian Techno',
    category: 'arp',
    tags: ['techno', 'dark', 'driven'],
    description: '黑曜石般冷硬的地下室 Techno：硬同步鋸齒波撞進過載的階梯濾波器，黑暗而催眠',
    params: {
      'arp.on': true, 'arp.mode': 'down', 'arp.gate': 0.45,
      'osc1.oct': -1, 'osc1.unison': 3, 'osc1.detune': 0.12, 'osc1.level': 0.9,
      'osc2.on': true, 'osc2.oct': -1, 'osc2.sync': 0.15, 'osc2.level': 0.55,
      'filter.cutoff': 560, 'filter.res': 0.6, 'filter.drive': 0.5, 'filter.env': 0.45, 'filter.key': 0.4,
      'fenv.a': 0.001, 'fenv.d': 0.12, 'fenv.s': 0, 'fenv.r': 0.08, 'fenv.curve': 0.25,
      'menv.a': 0, 'menv.d': 0.15,
      'aenv.a': 0.001, 'aenv.d': 0.2, 'aenv.s': 0.7, 'aenv.r': 0.08,
      'lfo1.shape': 'tri', 'lfo1.sync': '4/1', 'lfo1.mode': 'mono', 'lfo1.phase': 0.75,
      'mod1.src': 'lfo1', 'mod1.dst': 'filter.cutoff', 'mod1.amt': 0.1,
      'mod2.src': 'menv', 'mod2.dst': 'osc2.sync', 'mod2.amt': 0.25,
      'mod3.src': 'wheel', 'mod3.dst': 'filter.res', 'mod3.amt': 0.3, 'vib.wheel': 0,
      'drive.on': true, 'drive.type': 'tube', 'drive.amount': 0.35, 'drive.tone': 0.4,
      'delay.on': true, 'delay.feedback': 0.45, 'delay.pingpong': 0.7, 'delay.tone': 0.3, 'delay.mix': 0.14,
      'reverb.on': true, 'reverb.size': 0.5, 'reverb.decay': 2, 'reverb.damp': 0.8, 'reverb.mix': 0.15,
      'eq.low': -2,
      'comp.amount': 0.5,
      'amp.level': 6,
    },
    macros: [
      { name: '截止 Cutoff', targets: [{ id: 'filter.cutoff', amount: 0.35 }] },
      { name: '酸度 Acid', targets: [{ id: 'filter.res', amount: 0.3 }, { id: 'filter.env', amount: 0.25 }, { id: 'mod2.amt', amount: 0.2 }] },
      { name: '失真 Drive', targets: [{ id: 'drive.amount', amount: 0.45 }, { id: 'filter.drive', amount: 0.3 }] },
      { name: '迴響 Dub', targets: [{ id: 'delay.mix', amount: 0.25 }, { id: 'delay.feedback', amount: 0.25 }, { id: 'reverb.mix', amount: 0.15 }] },
    ],
    demo: 'arp',
    demoMacros: [{ index: 1, to: 1, beat: 0, beats: 8 }, { index: 1, to: 0, beat: 8, beats: 8 }],
  },

  // ── 10. Dub chord stabs ──
  {
    name: 'Velvet Dub Stabs',
    category: 'arp',
    tags: ['dub-techno', 'chord', 'stab', 'swing'],
    description: '按住和弦就自動彈出帶搖擺的短促和弦，沉入深色的附點回聲與殘響，Dub Techno 式的絲絨律動',
    params: {
      'arp.on': true, 'arp.mode': 'chord', 'arp.rate': '1/8', 'arp.gate': 0.25, 'arp.swing': 0.25,
      'osc1.unison': 2, 'osc1.detune': 0.1, 'osc1.level': 0.6,
      'osc2.on': true, 'osc2.shape': 1, 'osc2.pw': 0.35, 'osc2.fine': 6, 'osc2.level': 0.4,
      'filter.type': 'lp', 'filter.cutoff': 1100, 'filter.res': 0.3, 'filter.env': 0.35,
      'fenv.a': 0.001, 'fenv.d': 0.25, 'fenv.s': 0, 'fenv.r': 0.2,
      'aenv.a': 0.001, 'aenv.d': 0.35, 'aenv.s': 0.2, 'aenv.r': 0.25,
      'lfo1.shape': 'square', 'lfo1.sync': '1/4D', 'lfo1.mode': 'mono',
      'mod1.src': 'lfo1', 'mod1.dst': 'filter.cutoff', 'mod1.amt': 0.09,
      'mod3.src': 'lfo1', 'mod3.dst': 'amp.level', 'mod3.amt': 0.06,
      'mod2.src': 'wheel', 'mod2.dst': 'filter.cutoff', 'mod2.amt': 0.2, 'vib.wheel': 0,
      'chorus.on': true, 'chorus.depth': 0.45, 'chorus.mix': 0.35,
      'delay.on': true, 'delay.sync': '3/16', 'delay.feedback': 0.55, 'delay.pingpong': 0.8, 'delay.tone': 0.3, 'delay.wobble': 0.25, 'delay.mix': 0.28,
      'reverb.on': true, 'reverb.size': 0.7, 'reverb.damp': 0.7, 'reverb.mix': 0.25,
      'comp.amount': 0.3,
      'amp.level': 0.8,
      // peak soft clip (unity-gain tanh): the stabs peak ≈ 17 dB over their loudness; as a jam lead they pushed the
      // safety limiter 1.5–2 dB
      'drive.on': true, 'drive.amount': 0,
    },
    macros: [
      { name: '濾波 Filter', targets: [{ id: 'filter.cutoff', amount: 0.3 }, { id: 'filter.env', amount: 0.1 }] },
      { name: '搖擺 Swing', targets: [{ id: 'arp.swing', amount: 0.55 }] },
      { name: '音長 Length', targets: [{ id: 'arp.gate', amount: 0.35 }, { id: 'aenv.d', amount: 0.12 }] },
      { name: '迴響 Dub', targets: [{ id: 'delay.mix', amount: 0.25 }, { id: 'delay.feedback', amount: 0.2 }, { id: 'reverb.mix', amount: 0.15 }] },
    ],
    demo: 'arp',
    demoMacros: [{ index: 0, to: 0.7, beat: 0, beats: 8 }, { index: 0, to: 0, beat: 8, beats: 8 }, { index: 3, to: 1, beat: 8, beats: 4 }, { index: 3, to: 0, beat: 12, beats: 4 }],
  },
];
