// Bass 貝斯 — factory presets.
// Mono presets keep everything below ~150 Hz centred (sub layers on the dry bus, wide layers high-passed).
export default [
  {
    name: 'Tidal Reese',
    category: 'bass',
    tags: ['reese', 'wide', 'dnb'],
    description: '深海潮汐般翻湧的 Reese 貝斯：多重失諧鋸齒波緩緩旋轉，底下是紋絲不動的純淨次低音。',
    params: {
      'voice.mode': 'legato', 'voice.glide': 0.06,
      'osc1.unison': 3, 'osc1.detune': 0.18, 'osc1.spread': 0.6, 'osc1.level': 0.7, 'osc1.drift': 0.3,
      'osc2.on': true, 'osc2.unison': 5, 'osc2.detune': 0.38, 'osc2.spread': 0.9, 'osc2.drift': 0.3,
      'fm.on': true, 'fm.level': 0.6, 'fm.filt': 0, 'fm.op2.level': 0, 'fm.op3.level': 0, 'fm.op4.level': 0,
      'filter.cutoff': 2200, 'filter.res': 0.25, 'filter.drive': 0.5, 'filter.key': 0.35, 'filter.env': 0.12,
      'filter2.type': 'hp', 'filter2.cutoff': 130, 'filter2.res': 0.05,
      'aenv.a': 0.003, 'aenv.d': 0.5, 'aenv.s': 0.95, 'aenv.r': 0.15,
      'lfo1.rate': 0.15, 'lfo1.mode': 'mono',
      'lfo2.shape': 'smooth', 'lfo2.rate': 0.35, 'lfo2.mode': 'mono',
      'mod1.src': 'lfo1', 'mod1.dst': 'filter.cutoff', 'mod1.amt': 0.07,
      'mod2.src': 'lfo2', 'mod2.dst': 'osc2.detune', 'mod2.amt': 0.1,
      'mod3.src': 'wheel', 'mod3.dst': 'osc2.detune', 'mod3.amt': 0.25,
      'mod4.src': 'note', 'mod4.dst': 'amp.level', 'mod4.amt': -0.06,
      'mod5.src': 'aftertouch', 'mod5.dst': 'filter.cutoff', 'mod5.amt': 0.1,
      'drive.on': true, 'drive.amount': 0.35,
      'comp.amount': 0.4, 'amp.level': 3,
    },
    macros: [
      { name: '撕裂 Tear', targets: [{ id: 'osc2.detune', amount: 0.35 }, { id: 'osc1.detune', amount: 0.3 }, { id: 'drive.amount', amount: 0.3 }] },
      { name: '亮度 Bright', targets: [{ id: 'filter.cutoff', amount: 0.2 }] },
      { name: '流動 Motion', targets: [{ id: 'mod1.amt', amount: 0.08 }, { id: 'mod2.amt', amount: 0.15 }] },
      { name: '次低音 Sub', targets: [{ id: 'fm.level', amount: 0.3 }] },
    ],
    demo: 'bass',
    demoMacros: [{ index: 0, to: 1, beat: 0, beats: 8 }, { index: 2, to: 1, beat: 4, beats: 6 }, { index: 0, to: 0, beat: 12, beats: 4 }, { index: 2, to: 0, beat: 12, beats: 4 }],
  },
  {
    name: 'Deep Bass',
    category: 'bass',
    tags: ['analog', 'mono', 'punchy'],
    description: '經典單音類比貝斯：鋸齒波與方波交疊，階梯濾波器一開一合，扎實撐起整首歌的低頻。',
    params: {
      'voice.mode': 'mono', 'voice.glide': 0.025,
      'osc1.level': 0.75, 'osc1.drift': 0.2, 'osc1.phase': 'reset',
      'osc2.on': true, 'osc2.shape': 1, 'osc2.level': 0.45, 'osc2.fine': 6, 'osc2.drift': 0.2, 'osc2.phase': 'reset',
      'filter.cutoff': 420, 'filter.res': 0.3, 'filter.drive': 0.35, 'filter.key': 0.55, 'filter.env': 0.42, 'filter.vel': 0.25,
      'fenv.a': 0.001, 'fenv.d': 0.22, 'fenv.s': 0.18, 'fenv.r': 0.15, 'fenv.curve': 0.35,
      'aenv.a': 0.001, 'aenv.d': 0.5, 'aenv.r': 0.09, 'aenv.curve': 0.4,
      'amp.vel': 0.45, 'amp.level': 2.8,
      'vib.wheel': 8,
      'mod1.src': 'wheel', 'mod1.dst': 'filter.cutoff', 'mod1.amt': 0.2,
      'drive.on': true, 'drive.type': 'tube', 'drive.amount': 0.22, 'drive.tone': 0.45,
      'comp.amount': 0.3, 'eq.low': 1.5,
    },
    macros: [
      { name: '截止 Cutoff', targets: [{ id: 'filter.cutoff', amount: 0.3 }] },
      { name: '衝擊 Punch', targets: [{ id: 'filter.env', amount: 0.3 }, { id: 'fenv.d', amount: -0.1 }] },
      { name: '失真 Drive', targets: [{ id: 'drive.amount', amount: 0.6 }, { id: 'filter.drive', amount: 0.5 }] },
      { name: '滑音 Glide', targets: [{ id: 'voice.glide', amount: 0.25 }] },
    ],
    demo: 'bass',
    demoMacros: [{ index: 0, to: 0.7, beat: 4, beats: 4 }, { index: 2, to: 0.8, beat: 8, beats: 4 }, { index: 0, to: 0, beat: 12, beats: 4 }, { index: 2, to: 0, beat: 12, beats: 4 }],
  },
  {
    name: 'Acid Serpent',
    category: 'bass',
    tags: ['acid', 'resonant', 'mono'],
    description: '像毒蛇般扭動的 303 酸性貝斯：高共振濾波器隨重音尖叫，滑音在十六分音符之間蜿蜒。',
    params: {
      'voice.mode': 'legato', 'voice.glide': 0.035,
      'osc1.level': 1, 'osc1.phase': 'reset',
      'filter.type': 'ladder12', 'filter.cutoff': 380, 'filter.res': 0.8, 'filter.drive': 0.35, 'filter.key': 0.55, 'filter.env': 0.6, 'filter.vel': 0.3,
      'fenv.a': 0.001, 'fenv.d': 0.22, 'fenv.s': 0, 'fenv.r': 0.12, 'fenv.curve': 0.25,
      'aenv.a': 0.001, 'aenv.s': 0.9, 'aenv.r': 0.06,
      'amp.level': 6,
      'mod1.src': 'velocity', 'mod1.dst': 'filter.env', 'mod1.amt': 0.15,
      'mod2.src': 'wheel', 'mod2.dst': 'filter.res', 'mod2.amt': 0.12,
      'drive.on': true, 'drive.tone': 0.55,
      'delay.on': true, 'delay.sync': '3/16', 'delay.feedback': 0.3, 'delay.pingpong': 0.6, 'delay.tone': 0.35, 'delay.mix': 0.14,
      'comp.amount': 0.35,
    },
    macros: [
      { name: '截止 Cutoff', targets: [{ id: 'filter.cutoff', amount: 0.3 }, { id: 'filter.res', amount: -0.1 }, { id: 'filter.drive', amount: 0.25 }] },
      { name: '共振 Resonance', targets: [{ id: 'filter.res', amount: 0.15 }] },
      { name: '包絡 Env Mod', targets: [{ id: 'filter.env', amount: 0.3 }, { id: 'fenv.d', amount: 0.12 }] },
      { name: '失真 Drive', targets: [{ id: 'drive.amount', amount: 0.5 }, { id: 'filter.drive', amount: 0.4 }] },
    ],
    demo: 'bass',
    demoMacros: [{ index: 0, to: 0.85, beat: 0, beats: 8 }, { index: 1, to: 0.8, beat: 4, beats: 4 }, { index: 0, to: 0, beat: 12, beats: 4 }, { index: 1, to: 0, beat: 12, beats: 4 }],
  },
  {
    name: 'Leviathan Growl',
    category: 'bass',
    tags: ['growl', 'formant', 'aggressive'],
    description: '深海巨獸般低吼的說話貝斯：母音濾波器隨每個音張口咆哮，失真把中頻撕得粗糲。',
    params: {
      'voice.mode': 'mono', 'voice.glide': 0.04,
      'osc2.on': true, 'osc2.shape': 1, 'osc2.fine': 7, 'osc2.level': 0.5,
      'fm.on': true, 'fm.level': 0.55, 'fm.filt': 0, 'fm.op2.level': 0, 'fm.op3.level': 0, 'fm.op4.level': 0,
      'filter.type': 'formant', 'filter.cutoff': 800, 'filter.res': 0.8, 'filter.key': 0,
      'menv.a': 0.03, 'menv.d': 0.3, 'menv.s': 0.35, 'menv.r': 0.2,
      'lfo1.shape': 'smooth', 'lfo1.rate': 3,
      'mod1.src': 'menv', 'mod1.dst': 'filter.vowel', 'mod1.amt': 0.55,
      'mod2.src': 'lfo1', 'mod2.dst': 'filter.vowel', 'mod2.amt': 0.25,
      'mod3.src': 'wheel', 'mod3.dst': 'filter.vowel', 'mod3.amt': 0.4,
      'mod4.src': 'note', 'mod4.dst': 'amp.level', 'mod4.amt': -0.06,
      'drive.on': true, 'drive.amount': 0.6,
      'comp.amount': 0.5, 'amp.level': 4.5,
    },
    macros: [
      { name: '母音 Vowel', targets: [{ id: 'filter.vowel', amount: 0.5 }] },
      { name: '說話 Talk', targets: [{ id: 'mod2.amt', amount: 0.15 }, { id: 'lfo1.rate', amount: 0.1 }] },
      { name: '咆哮 Growl', targets: [{ id: 'filter.res', amount: 0.15 }, { id: 'drive.amount', amount: 0.3 }] },
      { name: '次低音 Sub', targets: [{ id: 'fm.level', amount: 0.35 }] },
    ],
    demo: 'bass',
    demoMacros: [{ index: 1, to: 1, beat: 0, beats: 8 }, { index: 0, to: 0.8, beat: 4, beats: 6 }, { index: 1, to: 0, beat: 12, beats: 4 }, { index: 0, to: 0, beat: 12, beats: 4 }],
  },
  {
    name: 'Seismic Wobble',
    category: 'bass',
    tags: ['wobble', 'dubstep', 'mono'],
    description: '地震般撼動地面的 Dubstep 擺動貝斯：濾波器跟著節拍 wub-wub，一轉旋鈕就切換成三連音。',
    params: {
      'voice.mode': 'mono', 'voice.glide': 0.035,
      'osc1.mode': 'wavetable', 'osc1.table': 'growl', 'osc1.shape': 0.25,
      'osc2.on': true, 'osc2.shape': 0, 'osc2.level': 0.5, 'osc2.filt': 0,
      'filter.type': 'lp', 'filter.cutoff': 250, 'filter.res': 0.6, 'filter.key': 0.4, 'filter.drive': 0.3,
      'lfo1.sync': '1/8', 'lfo1.mode': 'mono', 'lfo1.phase': 0.75,
      'lfo2.sync': '1/16T', 'lfo2.mode': 'mono', 'lfo2.phase': 0.75,
      'mod1.src': 'lfo1', 'mod1.dst': 'filter.cutoff', 'mod1.amt': 0.24,
      'mod2.src': 'lfo1', 'mod2.dst': 'osc1.shape', 'mod2.amt': 0.12,
      'mod3.src': 'lfo2', 'mod3.dst': 'filter.cutoff',
      'mod4.src': 'wheel', 'mod4.dst': 'filter.cutoff', 'mod4.amt': 0.15,
      'drive.on': true, 'drive.amount': 0.55,
      'comp.amount': 0.45, 'amp.level': 1.5,
    },
    macros: [
      { name: '擺動 Wobble', targets: [{ id: 'mod1.amt', amount: 0.12 }, { id: 'mod2.amt', amount: 0.1 }] },
      { name: '速度 Rate', targets: [{ id: 'mod1.amt', amount: -0.12 }, { id: 'mod3.amt', amount: 0.12 }] },
      { name: '咆哮 Growl', targets: [{ id: 'osc1.shape', amount: 0.45 }, { id: 'filter.drive', amount: 0.4 }, { id: 'drive.amount', amount: 0.3 }] },
      { name: '次低音 Sub', targets: [{ id: 'osc2.level', amount: 0.35 }] },
    ],
    demo: 'bass',
    demoMacros: [{ index: 0, to: 0.6, beat: 0, beats: 4 }, { index: 1, to: 1, beat: 8, beats: 1 }, { index: 1, to: 0, beat: 12, beats: 1 }, { index: 0, to: 0, beat: 14, beats: 2 }],
  },
  {
    name: 'Chrome Slap',
    category: 'bass',
    tags: ['fm', 'slap', 'digital'],
    description: '鍍鉻般閃亮的 80 年代 FM 拍弦貝斯：彈得越用力，起音的金屬光澤就越刺眼。',
    params: {
      'voice.mode': 'mono',
      'osc1.on': false, 'fm.on': true, 'fm.filt': 0,
      'fm.algo': 2, 'fm.feedback': 0.55,
      'fm.op1.d': 2.5, 'fm.op1.s': 0.55, 'fm.op1.r': 0.12,
      'fm.op2.level': 0.85, 'fm.op2.d': 0.3, 'fm.op2.s': 0.25, 'fm.op2.r': 0.12, 'fm.op2.vel': 0.5, 'fm.op2.kscale': -0.3,
      'fm.op3.ratio': 3, 'fm.op3.level': 0.55, 'fm.op3.d': 0.1, 'fm.op3.s': 0, 'fm.op3.r': 0.1, 'fm.op3.vel': 0.8,
      'fm.op4.level': 0.25, 'fm.op4.d': 0.6, 'fm.op4.s': 0.3, 'fm.op4.r': 0.12, 'fm.op4.vel': 0.5,
      'aenv.a': 0, 'aenv.d': 10, 'aenv.s': 1, 'aenv.r': 0.12, 'amp.vel': 0.3,
      'mod1.src': 'wheel', 'mod1.dst': 'fm.op2.level', 'mod1.amt': 0.15,
      'comp.amount': 0.35, 'amp.level': 2,
    },
    macros: [
      { name: '撥擊 Slap', targets: [{ id: 'fm.op3.level', amount: 0.25 }] },
      { name: '厚度 Growl', targets: [{ id: 'fm.feedback', amount: 0.25 }, { id: 'fm.op4.level', amount: 0.2 }] },
      { name: '延持 Sustain', targets: [{ id: 'fm.op1.s', amount: 0.35 }, { id: 'fm.op2.s', amount: 0.3 }] },
      { name: '亮度 Bright', targets: [{ id: 'fm.op2.level', amount: 0.15 }] },
    ],
    demo: 'bass',
    demoMacros: [{ index: 0, to: 1, beat: 0, beats: 8 }, { index: 1, to: 0.7, beat: 8, beats: 4 }, { index: 0, to: 0, beat: 12, beats: 4 }, { index: 1, to: 0, beat: 12, beats: 4 }],
  },
  {
    name: 'Walnut Upright',
    category: 'bass',
    tags: ['acoustic', 'upright', 'jazz'],
    description: '胡桃木色的原聲低音提琴：物理模型琴弦與共鳴箱，指尖撥弦的溫潤木質感彷彿就在爵士酒館。',
    params: {
      'osc1.on': false, 'phys.on': true,
      'phys.level': 1, 'phys.hardness': 0.3, 'phys.position': 0.2, 'phys.decay': 2.5, 'phys.brightness': 0.42, 'phys.inharm': 0.04,
      'phys.body': 0.7, 'phys.spread': 0.12, 'phys.damp': 0.85,
      'vib.wheel': 15, 'vib.rate': 5,
      'aenv.a': 0, 'aenv.d': 10, 'aenv.s': 1, 'aenv.r': 0.2,
      'reverb.on': true, 'reverb.size': 0.28, 'reverb.decay': 0.9, 'reverb.damp': 0.55, 'reverb.mix': 0.1, 'reverb.predelay': 0.01,
      'comp.amount': 0.35, 'amp.level': 6,
      // parallel soft clip (was the Lo-fi Rain part override): rounder, and the pluck no longer spikes 17 dB over its loudness
      'drive.on': true, 'drive.amount': 0.4, 'drive.mix': 0.6, 'drive.tone': 0.35,
    },
    macros: [
      { name: '撥弦 Pluck', targets: [{ id: 'phys.hardness', amount: 0.4 }] },
      { name: '亮度 Tone', targets: [{ id: 'phys.brightness', amount: 0.3 }] },
      { name: '延音 Sustain', targets: [{ id: 'phys.decay', amount: 0.15 }, { id: 'phys.damp', amount: -0.35 }] },
      { name: '空間 Room', targets: [{ id: 'reverb.mix', amount: 0.15 }, { id: 'reverb.size', amount: 0.3 }, { id: 'reverb.decay', amount: 0.15 }] },
    ],
    demo: 'bass',
    demoMacros: [{ index: 0, to: 0.8, beat: 4, beats: 4 }, { index: 3, to: 0.8, beat: 8, beats: 4 }, { index: 0, to: 0, beat: 12, beats: 4 }, { index: 3, to: 0, beat: 12, beats: 4 }],
  },
  {
    name: 'Rubber Pulse',
    category: 'bass',
    tags: ['synthpop', 'pluck', '80s'],
    description: '橡皮筋般彈跳的合成流行貝斯：脈衝波緩緩呼吸，每個音都帶一點俏皮的回彈。',
    params: {
      'voice.mode': 'mono',
      'osc1.shape': 1, 'osc1.pw': 0.3, 'osc1.level': 0.9, 'osc1.phase': 'reset',
      'osc2.on': true, 'osc2.oct': 1, 'osc2.level': 0.22, 'osc2.phase': 'reset',
      'filter.type': 'ladder12', 'filter.cutoff': 450, 'filter.res': 0.3, 'filter.key': 0.5, 'filter.env': 0.55, 'filter.vel': 0.3, 'filter.drive': 0.2,
      'fenv.a': 0, 'fenv.d': 0.14, 'fenv.s': 0.08, 'fenv.r': 0.1, 'fenv.curve': 0.3,
      'aenv.a': 0.001, 'aenv.d': 0.35, 'aenv.s': 0.45, 'aenv.r': 0.08, 'aenv.curve': 0.35,
      'lfo1.rate': 0.5,
      'menv.a': 0, 'menv.d': 0.06,
      'mod1.src': 'lfo1', 'mod1.dst': 'osc1.pw', 'mod1.amt': 0.1,
      'mod2.src': 'menv', 'mod2.dst': 'voice.pitch', 'mod2.amt': 0.015,
      'mod3.src': 'wheel', 'mod3.dst': 'filter.cutoff', 'mod3.amt': 0.2,
      'vib.wheel': 10,
      'drive.on': true, 'drive.amount': 0.25,
      'comp.amount': 0.35, 'amp.level': 5.5,
    },
    macros: [
      { name: '彈性 Snap', targets: [{ id: 'filter.env', amount: 0.35 }, { id: 'fenv.d', amount: -0.08 }, { id: 'mod2.amt', amount: 0.015 }] },
      { name: '脈寬 PWM', targets: [{ id: 'mod1.amt', amount: 0.12 }, { id: 'osc1.pw', amount: -0.2 }] },
      { name: '亮度 Bright', targets: [{ id: 'filter.cutoff', amount: 0.3 }] },
      { name: '八度 Octave', targets: [{ id: 'osc2.level', amount: 0.6 }] },
    ],
    demo: 'bass',
    demoMacros: [{ index: 2, to: 0.7, beat: 0, beats: 8 }, { index: 1, to: 1, beat: 4, beats: 6 }, { index: 2, to: 0, beat: 12, beats: 4 }, { index: 1, to: 0, beat: 12, beats: 4 }],
  },
  {
    name: 'Warehouse Organ',
    category: 'bass',
    tags: ['house', 'organ', '90s'],
    description: '90 年代倉庫派對的浩室風琴貝斯：音栓風琴配上清脆鍵擊，短促又充滿律動。',
    params: {
      'voice.mode': 'mono',
      'osc1.mode': 'wavetable', 'osc1.table': 'organ', 'osc1.shape': 0.7778, 'osc1.oct': 1, 'osc1.level': 1,
      'osc2.on': true, 'osc2.mode': 'wavetable', 'osc2.table': 'organ', 'osc2.shape': 0.7778, 'osc2.oct': 1, 'osc2.fine': 4, 'osc2.level': 0.45,
      'noise.on': true, 'noise.level': 0.18, 'noise.decay': 0.012, 'noise.color': 0.3, 'noise.filt': 0.4,
      'vib.wheel': 20, 'vib.rate': 6.5,
      'filter.type': 'ladder12', 'filter.cutoff': 2500,
      'aenv.a': 0.001, 'aenv.d': 0.35, 'aenv.s': 0.5, 'aenv.r': 0.07, 'aenv.curve': 0.3,
      'drive.on': true, 'drive.type': 'tube', 'drive.amount': 0.2,
      'comp.amount': 0.5, 'eq.mid': 3, 'eq.midfreq': 700, 'amp.level': 6,
    },
    macros: [
      { name: '音栓 Drawbars', targets: [{ id: 'osc1.shape', amount: 0.22 }, { id: 'osc2.shape', amount: 0.22 }] },
      { name: '敲擊 Click', targets: [{ id: 'noise.level', amount: 0.3 }] },
      { name: '衰減 Decay', targets: [{ id: 'aenv.d', amount: 0.2 }, { id: 'aenv.s', amount: 0.2 }] },
      { name: '失真 Overdrive', targets: [{ id: 'drive.amount', amount: 0.6 }, { id: 'filter.drive', amount: 0.5 }] },
    ],
    demo: 'bass',
    demoMacros: [{ index: 0, to: 1, beat: 4, beats: 4 }, { index: 3, to: 0.8, beat: 8, beats: 4 }, { index: 0, to: 0, beat: 12, beats: 4 }, { index: 3, to: 0, beat: 12, beats: 4 }],
  },
  {
    name: 'Abyssal Sub',
    category: 'bass',
    tags: ['sub', 'clean', 'deep'],
    description: '深淵般純淨的次低音：正弦波加上一抹溫暖泛音，連小喇叭都聽得見它的重量。',
    params: {
      'voice.mode': 'mono', 'voice.glide': 0.02,
      'osc1.shape': 0, 'osc1.phase': 'reset', 'osc1.drift': 0.02, 'osc1.filt': 0,
      'osc2.on': true, 'osc2.shape': 0.3333, 'osc2.oct': 1, 'osc2.level': 0.15, 'osc2.phase': 'reset', 'osc2.drift': 0.02,
      'filter.cutoff': 700, 'filter.key': 0.6, 'filter.res': 0,
      'menv.a': 0, 'menv.d': 0.05, 'menv.r': 0.05,
      'mod1.src': 'menv', 'mod1.dst': 'voice.pitch', 'mod1.amt': 0.06,
      'mod2.src': 'note', 'mod2.dst': 'amp.level', 'mod2.amt': -0.08,
      'mod3.src': 'wheel', 'mod3.dst': 'osc2.level', 'mod3.amt': 0.4,
      'vib.wheel': 0,
      'aenv.a': 0.002, 'aenv.d': 1.5, 'aenv.s': 0.85, 'aenv.r': 0.12,
      'drive.on': true, 'drive.type': 'tube', 'drive.amount': 0.35, 'drive.tone': 0.4,
      'comp.amount': 0.25, 'amp.level': 2.5,
    },
    macros: [
      { name: '泛音 Harmonics', targets: [{ id: 'osc2.level', amount: 0.35 }, { id: 'drive.amount', amount: 0.35 }] },
      { name: '衝擊 Punch', targets: [{ id: 'mod1.amt', amount: 0.1 }, { id: 'menv.d', amount: 0.1 }] },
      { name: '尾音 Tail', targets: [{ id: 'aenv.r', amount: 0.25 }] },
      { name: '滑音 Glide', targets: [{ id: 'voice.glide', amount: 0.35 }, { id: 'aenv.r', amount: 0.09 }] },
    ],
    demo: 'bass',
    demoMacros: [{ index: 0, to: 1, beat: 4, beats: 4 }, { index: 1, to: 1, beat: 8, beats: 4 }, { index: 0, to: 0, beat: 12, beats: 4 }, { index: 1, to: 0, beat: 12, beats: 4 }],
  },
];
