// Bell 鐘琴 — factory presets (sound design: presets-bell). Flagship first.
// (The former `random → phys.decay` mod8 workaround for the phys.js reset() voice-steal bug is gone: the engine
// is fixed, see docs/PRESETS.md.)
export default [
  {
    name: 'Celestial Carillon',
    category: 'bell',
    tags: ['church', 'physical', 'shimmer', 'cinematic'],
    description: '青銅鐘樓在極光下齊鳴：低沉的嗡鳴、明亮的敲擊，與緩緩升起的天光殘響',
    params: {
      'osc1.level': 0, 'osc1.mode': 'wavetable', 'osc1.table': 'vowels', 'osc1.shape': 0.72,
      'osc1.unison': 3, 'osc1.detune': 0.22, 'osc1.spread': 0.9,
      'filter.type': 'hp', 'filter.cutoff': 55, 'filter.res': 0, 'filter.key': 0, 'phys.filt': 1,
      'phys.on': true, 'phys.level': 0.85, 'phys.model': 'bell', 'phys.exciter': 'mallet', 'phys.hardness': 0.7,
      'phys.position': 0.3, 'phys.decay': 12, 'phys.brightness': 0.55, 'phys.inharm': 0.14, 'phys.body': 0.35,
      'phys.damp': 0.2, 'phys.spread': 0.7, 'phys.oct': -1,
      'noise.on': true, 'noise.level': 0.08, 'noise.color': 0.7, 'noise.decay': 0.04, 'noise.filt': 0,
      'aenv.a': 0.001, 'aenv.d': 10, 'aenv.s': 1, 'aenv.r': 6,
      'menv.a': 1.4, 'menv.d': 3, 'menv.s': 0.8, 'menv.r': 3,
      'mod1.src': 'menv', 'mod1.dst': 'osc1.level', 'mod1.amt': 0.22,
      'mod2.src': 'wheel', 'mod2.dst': 'phys.brightness', 'mod2.amt': 0.3,
      'mod3.src': 'velocity', 'mod3.dst': 'phys.brightness', 'mod3.amt': 0.2,
      'amp.vel': 0.7,
      'vib.rate': 1.1, 'vib.wheel': 14,
      'reverb.on': true, 'reverb.size': 0.85, 'reverb.decay': 6, 'reverb.predelay': 0.035, 'reverb.damp': 0.45, 'reverb.mix': 0.32, 'reverb.shimmer': 0.15,
      'eq.low': -2.5,
      'amp.level': 3.7,
      // peak soft clip (amount 0 = unity-gain tanh, clean at playing level): chords' summed strikes no longer
      // push the output limiter (5-note chord at velocity 0.9)
      'drive.on': true, 'drive.amount': 0, 'drive.mix': 0.4,
    },
    macros: [
      { name: '敲擊 Strike', targets: [{ id: 'phys.hardness', amount: 0.3 }, { id: 'noise.level', amount: 0.25 }, { id: 'phys.brightness', amount: 0.2 }] },
      { name: '材質 Material', targets: [{ id: 'phys.inharm', amount: 0.45 }, { id: 'phys.position', amount: 0.3 }] },
      { name: '聖詠 Choir', targets: [{ id: 'mod1.amt', amount: 0.2 }, { id: 'phys.decay', amount: 0.1 }, { id: 'amp.level', amount: -0.04 }] },
      { name: '天光 Shimmer', targets: [{ id: 'reverb.shimmer', amount: 0.6 }, { id: 'reverb.mix', amount: 0.2 }] },
    ],
    demo: 'bell',
    demoMacros: [{ index: 3, to: 0.8, beat: 4, beats: 6 }, { index: 3, to: 0, beat: 12, beats: 4 }],
  },
  {
    name: 'Midnight Vibraphone',
    category: 'bell',
    tags: ['vibraphone', 'jazz', 'tremolo', 'physical'],
    description: '深夜爵士酒吧裡的顫音琴：鋁板溫柔地發亮，馬達轉動帶出一圈圈呼吸般的顫音',
    params: {
      'osc1.on': false,
      'phys.on': true, 'phys.level': 0.7, 'phys.model': 'bar', 'phys.exciter': 'mallet', 'phys.hardness': 0.48,
      'phys.position': 0.85, 'phys.decay': 6, 'phys.brightness': 0.55, 'phys.inharm': 0.04, 'phys.body': 0.4,
      'phys.damp': 0.72, 'phys.spread': 0.5,
      'aenv.a': 0.001, 'aenv.d': 10, 'aenv.s': 1, 'aenv.r': 1.2,
      'lfo1.rate': 4.8, 'lfo1.mode': 'mono',
      'mod1.src': 'lfo1', 'mod1.dst': 'phys.level', 'mod1.amt': 0.12,
      'mod2.src': 'lfo1', 'mod2.dst': 'amp.pan', 'mod2.amt': 0.08,
      'mod3.src': 'wheel', 'mod3.dst': 'lfo1.rate', 'mod3.amt': 0.08,
      'mod4.src': 'note', 'mod4.dst': 'amp.pan', 'mod4.amt': 0.25,
      'mod5.src': 'velocity', 'mod5.dst': 'phys.brightness', 'mod5.amt': 0.2,
      'amp.vel': 0.75, 'vib.wheel': 0,
      'chorus.on': true, 'chorus.rate': 0.35, 'chorus.depth': 0.25, 'chorus.mix': 0.18,
      'reverb.on': true, 'reverb.size': 0.5, 'reverb.decay': 2.2, 'reverb.predelay': 0.015, 'reverb.damp': 0.55, 'reverb.mix': 0.22,
      'eq.low': 1, 'eq.high': -1.5,
      'amp.level': -5, 'macro2': 0.3,
    },
    macros: [
      { name: '琴槌 Mallet', targets: [{ id: 'phys.hardness', amount: 0.35 }, { id: 'phys.brightness', amount: 0.2 }] },
      { name: '顫音 Tremolo', targets: [{ id: 'mod1.amt', amount: 0.16 }, { id: 'mod2.amt', amount: 0.08 }, { id: 'lfo1.rate', amount: 0.05 }, { id: 'amp.level', amount: -0.02 }] },
      { name: '踏板 Pedal', targets: [{ id: 'phys.damp', amount: -0.6 }, { id: 'aenv.r', amount: 0.25 }] },
      { name: '空間 Room', targets: [{ id: 'reverb.mix', amount: 0.25 }, { id: 'reverb.decay', amount: 0.15 }, { id: 'chorus.mix', amount: 0.2 }] },
    ],
    demo: 'keys',
    demoMacros: [{ index: 1, to: 0.9, beat: 4, beats: 6 }, { index: 1, to: 0.3, beat: 14, beats: 4 }],
  },
  {
    name: 'Rosewood Marimba',
    category: 'bell',
    tags: ['marimba', 'wood', 'warm', 'physical'],
    description: '玫瑰木琴鍵與共鳴管交融的溫暖馬林巴，毛線槌落下時圓潤而飽滿',
    params: {
      'osc1.on': false,
      'phys.on': true, 'phys.level': 0.9, 'phys.model': 'bar', 'phys.exciter': 'mallet', 'phys.hardness': 0.38,
      'phys.position': 0.9, 'phys.decay': 1.3, 'phys.brightness': 0.25, 'phys.inharm': 0, 'phys.body': 0.7,
      'phys.damp': 0.5, 'phys.spread': 0.6,
      'mod1.src': 'note', 'mod1.dst': 'amp.pan', 'mod1.amt': 0.7,
      'mod2.src': 'velocity', 'mod2.dst': 'phys.brightness', 'mod2.amt': 0.25,
      'mod3.src': 'wheel', 'mod3.dst': 'phys.decay', 'mod3.amt': 0.25,
      'amp.vel': 0.75, 'vib.wheel': 0,
      'noise.on': true, 'noise.level': 0.05, 'noise.color': -0.2, 'noise.decay': 0.018, 'noise.filt': 0,
      'aenv.a': 0.001, 'aenv.d': 10, 'aenv.s': 1, 'aenv.r': 1,
      'reverb.on': true, 'reverb.size': 0.45, 'reverb.decay': 1.6, 'reverb.predelay': 0.01, 'reverb.damp': 0.55, 'reverb.mix': 0.2,
      'amp.level': -2.2,
      // peak soft clip (amount 0 = unity-gain tanh, clean at playing level): chords' summed strikes no longer
      // push the output limiter (5-note chord at velocity 0.9)
      'drive.on': true, 'drive.amount': 0, 'drive.mix': 0.4,
    },
    macros: [
      { name: '琴槌 Mallet', targets: [{ id: 'phys.hardness', amount: 0.4 }, { id: 'phys.brightness', amount: 0.25 }, { id: 'noise.level', amount: 0.08 }] },
      { name: '敲擊點 Position', targets: [{ id: 'phys.position', amount: -0.5 }, { id: 'amp.level', amount: 0.03 }] },
      { name: '共鳴 Resonance', targets: [{ id: 'phys.decay', amount: 0.2 }, { id: 'phys.body', amount: 0.1 }, { id: 'amp.level', amount: -0.04 }] },
      { name: '空間 Room', targets: [{ id: 'reverb.mix', amount: 0.25 }, { id: 'reverb.size', amount: 0.3 }] },
    ],
    demo: 'pluck',
    demoMacros: [{ index: 0, to: 0.85, beat: 4, beats: 8 }, { index: 0, to: 0, beat: 12, beats: 4 }],
  },
  {
    name: 'Glass Harmonica',
    category: 'bell',
    tags: ['glass', 'bowed', 'ethereal', 'physical'],
    description: '沾濕的指尖摩擦旋轉的水晶碗，純淨的歌聲從玻璃裡緩緩浮現',
    params: {
      'osc1.on': false,
      'phys.on': true, 'phys.level': 0.9, 'phys.model': 'glass', 'phys.exciter': 'bow', 'phys.hardness': 0.45,
      'phys.position': 0.4, 'phys.decay': 8, 'phys.brightness': 0.55, 'phys.inharm': 0.12, 'phys.body': 0.25,
      'phys.pressure': 0.45, 'phys.damp': 0.4, 'phys.spread': 0.7, 'phys.oct': 1,
      'aenv.a': 0.08, 'aenv.d': 10, 'aenv.s': 1, 'aenv.r': 2.5,
      'vib.depth': 4, 'vib.rate': 4.5, 'vib.delay': 0.6, 'vib.wheel': 25,
      'mod1.src': 'velocity', 'mod1.dst': 'phys.pressure', 'mod1.amt': 0.2,
      'amp.vel': 0.6,
      'reverb.on': true, 'reverb.size': 0.8, 'reverb.decay': 5, 'reverb.predelay': 0.03, 'reverb.damp': 0.4, 'reverb.mix': 0.32,
      'amp.level': -7.5,
    },
    macros: [
      { name: '指壓 Pressure', targets: [{ id: 'phys.pressure', amount: 0.4 }, { id: 'phys.brightness', amount: 0.2 }] },
      { name: '水晶 Crystal', targets: [{ id: 'phys.inharm', amount: 0.4 }, { id: 'phys.position', amount: 0.3 }] },
      { name: '氣息 Breath', targets: [{ id: 'vib.depth', amount: 0.12 }, { id: 'phys.hardness', amount: -0.25 }] },
      { name: '空間 Space', targets: [{ id: 'reverb.mix', amount: 0.25 }, { id: 'reverb.shimmer', amount: 0.4 }] },
    ],
    demo: 'pad',
    demoMacros: [{ index: 0, to: 0.8, beat: 4, beats: 8 }, { index: 0, to: 0, beat: 12, beats: 4 }],
  },
  {
    name: 'Clockwork Music Box',
    category: 'bell',
    tags: ['musicbox', 'toy', 'nostalgic', 'lofi'],
    description: '轉緊發條的木頭音樂盒，鋼梳齒一根根被撥響，帶著一點舊時光的搖晃',
    params: {
      'osc1.on': false,
      'phys.on': true, 'phys.level': 0.75, 'phys.model': 'bar', 'phys.hardness': 0.7,
      'phys.position': 0.12, 'phys.decay': 2.2, 'phys.brightness': 0.55, 'phys.inharm': 0.35, 'phys.body': 0.2,
      'phys.damp': 0.1, 'phys.spread': 0.4, 'phys.oct': 1,
      'fm.on': true, 'fm.level': 0.55, 'fm.algo': 3, 'fm.oct': 1,
      'fm.op1.level': 0.9, 'fm.op1.d': 2.5, 'fm.op1.s': 0, 'fm.op1.r': 2, 'fm.op1.kscale': -0.3,
      'fm.op2.level': 0.18, 'fm.op2.d': 0.25, 'fm.op2.s': 0, 'fm.op2.r': 0.1, 'fm.op2.vel': 0.7,
      'fm.op3.ratio': 6.27, 'fm.op3.level': 0.35, 'fm.op3.d': 0.45, 'fm.op3.s': 0, 'fm.op3.r': 0.25, 'fm.op3.kscale': -0.5,
      'fm.op4.ratio': 2, 'fm.op4.level': 0.1, 'fm.op4.d': 0.2, 'fm.op4.s': 0,
      'aenv.a': 0.001, 'aenv.d': 10, 'aenv.s': 1, 'aenv.r': 2.5,
      'lfo2.shape': 'smooth', 'lfo2.rate': 0.7, 'lfo2.mode': 'mono',
      'mod1.src': 'lfo2', 'mod1.dst': 'voice.pitch', 'mod1.amt': 0.002,
      'mod2.src': 'note', 'mod2.dst': 'amp.level', 'mod2.amt': -0.1,
      'amp.vel': 0.6, 'vib.rate': 4, 'vib.wheel': 18,
      'chorus.on': true, 'chorus.rate': 0.5, 'chorus.depth': 0.3, 'chorus.mix': 0.25,
      'reverb.on': true, 'reverb.size': 0.35, 'reverb.decay': 1.4, 'reverb.predelay': 0.005, 'reverb.damp': 0.35, 'reverb.mix': 0.2,
      'eq.low': -2,
      'amp.level': 3.5,
      // peak soft clip (amount 0 = unity-gain tanh, clean at playing level): chords' summed strikes no longer
      // push the output limiter (5-note chord at velocity 0.9)
      'drive.on': true, 'drive.amount': 0, 'drive.mix': 0.7,
    },
    macros: [
      { name: '梳齒 Tine', targets: [{ id: 'phys.hardness', amount: 0.25 }, { id: 'fm.op3.level', amount: 0.25 }] },
      { name: '發條 Wind-up', targets: [{ id: 'mod1.amt', amount: 0.006 }, { id: 'lfo2.rate', amount: 0.15 }] },
      { name: '木盒 Box', targets: [{ id: 'phys.body', amount: 0.35 }, { id: 'eq.low', amount: 0.12 }, { id: 'phys.decay', amount: 0.12 }, { id: 'amp.level', amount: -0.05 }] },
      { name: '回憶 Memory', targets: [{ id: 'reverb.mix', amount: 0.3 }, { id: 'reverb.decay', amount: 0.25 }, { id: 'chorus.mix', amount: 0.3 }] },
    ],
    demo: 'bell',
    demoMacros: [{ index: 1, to: 0.8, beat: 6, beats: 6 }, { index: 1, to: 0, beat: 13, beats: 3 }],
  },
  {
    name: 'Sugar Plum Celesta',
    category: 'bell',
    tags: ['celesta', 'fm', 'sweet', 'orchestral'],
    description: '糖梅仙子的鋼片琴：小槌輕敲鋼片，木箱共鳴出甜美如糖霜的鐘音',
    params: {
      'osc1.on': false,
      'fm.on': true, 'fm.algo': 3,
      'fm.op1.level': 0.95, 'fm.op1.d': 3.5, 'fm.op1.s': 0, 'fm.op1.r': 1.2, 'fm.op1.vel': 0.4, 'fm.op1.kscale': -0.2,
      'fm.op2.level': 0.28, 'fm.op2.d': 0.5, 'fm.op2.s': 0, 'fm.op2.r': 0.4, 'fm.op2.vel': 0.8, 'fm.op2.kscale': -0.4,
      'fm.op3.ratio': 4, 'fm.op3.level': 0.35, 'fm.op3.d': 0.9, 'fm.op3.s': 0, 'fm.op3.r': 0.5, 'fm.op3.vel': 0.6, 'fm.op3.kscale': -0.4,
      'fm.op4.ratio': 9, 'fm.op4.level': 0.18, 'fm.op4.d': 0.12, 'fm.op4.s': 0, 'fm.op4.r': 0.1, 'fm.op4.vel': 0.8, 'fm.op4.kscale': -0.6,
      'phys.on': true, 'phys.level': 0.35, 'phys.model': 'bar', 'phys.exciter': 'mallet', 'phys.hardness': 0.45,
      'phys.position': 0.8, 'phys.decay': 3, 'phys.brightness': 0.5, 'phys.inharm': 0.02, 'phys.body': 0.6, 'phys.damp': 0.6, 'phys.spread': 0.5,
      'mod1.src': 'wheel', 'mod1.dst': 'fm.op2.level', 'mod1.amt': 0.3,
      'amp.vel': 0.7, 'vib.wheel': 0,
      'aenv.a': 0.001, 'aenv.d': 10, 'aenv.s': 1, 'aenv.r': 1.2,
      'chorus.on': true, 'chorus.rate': 0.4, 'chorus.depth': 0.2, 'chorus.mix': 0.15,
      'reverb.on': true, 'reverb.size': 0.65, 'reverb.decay': 2.6, 'reverb.predelay': 0.025, 'reverb.damp': 0.45, 'reverb.mix': 0.25,
      'amp.level': 3.2,
      // peak soft clip (amount 0 = unity-gain tanh, clean at playing level): chords' summed strikes no longer
      // push the output limiter (5-note chord at velocity 0.9)
      'drive.on': true, 'drive.amount': 0, 'drive.mix': 0.6,
    },
    macros: [
      { name: '甜度 Sweetness', targets: [{ id: 'fm.op2.level', amount: 0.35 }, { id: 'fm.op4.level', amount: 0.35 }, { id: 'fm.op3.level', amount: 0.2 }] },
      { name: '鋼片 Steel', targets: [{ id: 'phys.level', amount: 0.4 }, { id: 'phys.hardness', amount: 0.3 }, { id: 'amp.level', amount: -0.03 }] },
      { name: '延音 Sustain', targets: [{ id: 'fm.op1.d', amount: 0.2 }, { id: 'fm.op1.r', amount: 0.25 }, { id: 'aenv.r', amount: 0.2 }, { id: 'amp.level', amount: -0.03 }] },
      { name: '音樂廳 Hall', targets: [{ id: 'reverb.mix', amount: 0.25 }, { id: 'reverb.size', amount: 0.3 }, { id: 'reverb.decay', amount: 0.2 }] },
    ],
    demo: 'bell',
    demoMacros: [{ index: 3, to: 0.8, beat: 2, beats: 8 }, { index: 3, to: 0, beat: 12, beats: 4 }],
  },
  {
    name: 'Ombak Gamelan',
    category: 'bell',
    tags: ['gamelan', 'bronze', 'world', 'hybrid'],
    description: '峇里島青銅鍵盤成對調音，兩片銅鍵之間的拍頻像海浪般起伏（ombak）',
    params: {
      'osc1.on': false,
      'phys.on': true, 'phys.level': 0.6, 'phys.model': 'bar', 'phys.exciter': 'mallet', 'phys.hardness': 0.75,
      'phys.position': 0.3, 'phys.decay': 4, 'phys.brightness': 0.62, 'phys.inharm': 0.8, 'phys.body': 0.5,
      'phys.damp': 0.3, 'phys.spread': 0.5, 'phys.fine': -9, 'phys.pan': -0.35,
      'fm.on': true, 'fm.level': 0.75, 'fm.algo': 8, 'fm.fine': 9, 'fm.pan': 0.35,
      'fm.op1.level': 0.95, 'fm.op1.d': 4, 'fm.op1.s': 0, 'fm.op1.r': 2.5,
      'fm.op2.ratio': 2.76, 'fm.op2.level': 0.45, 'fm.op2.d': 1.6, 'fm.op2.s': 0, 'fm.op2.r': 1.2, 'fm.op2.kscale': -0.3,
      'fm.op3.ratio': 5.4, 'fm.op3.level': 0.25, 'fm.op3.d': 0.7, 'fm.op3.s': 0, 'fm.op3.r': 0.6, 'fm.op3.kscale': -0.5,
      'fm.op4.ratio': 8.93, 'fm.op4.level': 0.12, 'fm.op4.d': 0.3, 'fm.op4.s': 0, 'fm.op4.r': 0.25, 'fm.op4.kscale': -0.6,
      'aenv.a': 0.001, 'aenv.d': 10, 'aenv.s': 1, 'aenv.r': 2.5,
      'mod1.src': 'velocity', 'mod1.dst': 'phys.brightness', 'mod1.amt': 0.2,
      'mod2.src': 'wheel', 'mod2.dst': 'fm.op3.level', 'mod2.amt': 0.3,
      'amp.vel': 0.75, 'vib.wheel': 0,
      'reverb.on': true, 'reverb.size': 0.62, 'reverb.decay': 2.8, 'reverb.predelay': 0.018, 'reverb.damp': 0.45, 'reverb.mix': 0.22,
      'amp.level': 1.3,
    },
    macros: [
      { name: '波動 Ombak', targets: [{ id: 'phys.fine', amount: -0.05 }, { id: 'fm.fine', amount: 0.05 }] },
      { name: '青銅 Bronze', targets: [{ id: 'phys.hardness', amount: 0.25 }, { id: 'fm.op3.level', amount: 0.3 }, { id: 'phys.brightness', amount: 0.2 }] },
      { name: '悶音 Damping', targets: [{ id: 'phys.damp', amount: 0.6 }, { id: 'aenv.r', amount: -0.35 }] },
      { name: '廟宇 Temple', targets: [{ id: 'reverb.mix', amount: 0.25 }, { id: 'reverb.size', amount: 0.3 }, { id: 'reverb.decay', amount: 0.25 }] },
    ],
    demo: 'pluck',
    demoMacros: [{ index: 0, to: 0.9, beat: 4, beats: 6 }, { index: 0, to: 0, beat: 12, beats: 4 }],
  },
  {
    name: 'Himalayan Singing Bowl',
    category: 'bell',
    tags: ['bowl', 'meditation', 'drone', 'physical'],
    description: '喜馬拉雅頌缽：毛氈槌輕敲後沿著缽緣研磨，低沉的嗡鳴與拍頻在空氣中久久迴旋',
    params: {
      'osc1.on': false,
      'phys.on': true, 'phys.level': 0.5, 'phys.model': 'glass', 'phys.exciter': 'mallet', 'phys.hardness': 0.4,
      'phys.position': 0.35, 'phys.decay': 16, 'phys.brightness': 0.5, 'phys.inharm': 0.2, 'phys.body': 0.5,
      'phys.damp': 0.15, 'phys.spread': 0.6, 'phys.oct': -1, 'phys.filt': 1,
      'fm.on': true, 'fm.level': 0.75, 'fm.algo': 8, 'fm.oct': -1,
      'filter.type': 'hp', 'filter.cutoff': 45, 'filter.res': 0, 'filter.key': 0,
      'fm.op1.level': 0.95, 'fm.op1.a': 0.25, 'fm.op1.d': 20, 'fm.op1.s': 0.9, 'fm.op1.r': 7, 'fm.op1.vel': 0.2,
      'fm.op2.detune': 4, 'fm.op2.level': 0.85, 'fm.op2.a': 0.45, 'fm.op2.d': 20, 'fm.op2.s': 0.9, 'fm.op2.r': 7, 'fm.op2.vel': 0.2,
      'fm.op3.ratio': 2.83, 'fm.op3.detune': -3, 'fm.op3.level': 0.3, 'fm.op3.a': 0.9, 'fm.op3.d': 20, 'fm.op3.s': 0.8, 'fm.op3.r': 5, 'fm.op3.kscale': -0.4,
      'fm.op4.ratio': 5.42, 'fm.op4.level': 0.1, 'fm.op4.a': 1.3, 'fm.op4.d': 20, 'fm.op4.s': 0.7, 'fm.op4.r': 4, 'fm.op4.kscale': -0.6,
      'aenv.a': 0.001, 'aenv.d': 10, 'aenv.s': 1, 'aenv.r': 8,
      'lfo1.rate': 0.6, 'lfo1.mode': 'mono',
      'mod1.src': 'lfo1', 'mod1.dst': 'fm.level', 'mod1.amt': 0.06,
      'mod2.src': 'wheel', 'mod2.dst': 'fm.level', 'mod2.amt': 0.3,
      'voice.poly': 8, 'amp.vel': 0.6, 'vib.wheel': 0,
      'reverb.on': true, 'reverb.size': 0.75, 'reverb.decay': 5, 'reverb.predelay': 0.03, 'reverb.damp': 0.55, 'reverb.mix': 0.28,
      'amp.level': -3.1,
    },
    macros: [
      { name: '研磨 Rim', targets: [{ id: 'fm.level', amount: 0.25 }, { id: 'phys.level', amount: -0.2 }, { id: 'mod1.amt', amount: 0.06 }] },
      { name: '敲擊 Strike', targets: [{ id: 'phys.hardness', amount: 0.35 }, { id: 'phys.brightness', amount: 0.2 }] },
      { name: '拍頻 Beat', targets: [{ id: 'fm.op2.detune', amount: 0.2 }, { id: 'phys.spread', amount: 0.35 }, { id: 'lfo1.rate', amount: 0.1 }] },
      { name: '冥想 Space', targets: [{ id: 'reverb.mix', amount: 0.3 }, { id: 'reverb.decay', amount: 0.25 }] },
    ],
    demo: 'bell',
    demoMacros: [{ index: 0, to: 0.85, beat: 2, beats: 8 }, { index: 0, to: 0, beat: 12, beats: 4 }],
  },
  {
    name: 'Frost Lantern',
    category: 'bell',
    tags: ['fm', 'pad', 'glassy', 'wide'],
    description: '冰晶燈籠在雪夜裡叮噹作響：清脆的 FM 鐘聲下，玻璃般的光暈緩緩亮起',
    params: {
      'osc1.level': 0, 'osc1.mode': 'wavetable', 'osc1.table': 'glass', 'osc1.shape': 0.35,
      'osc1.unison': 4, 'osc1.detune': 0.18, 'osc1.spread': 0.9,
      'filter.type': 'lp', 'filter.cutoff': 3200, 'filter.res': 0.15, 'filter.key': 0.5,
      'fm.on': true, 'fm.level': 0.75, 'fm.algo': 3, 'fm.filt': 0,
      'fm.op1.level': 0.9, 'fm.op1.d': 5, 'fm.op1.s': 0, 'fm.op1.r': 3, 'fm.op1.vel': 0.35,
      'fm.op2.ratio': 3.5, 'fm.op2.level': 0.42, 'fm.op2.d': 2.2, 'fm.op2.s': 0, 'fm.op2.r': 2, 'fm.op2.vel': 0.7, 'fm.op2.kscale': -0.7,
      'fm.op3.ratio': 2, 'fm.op3.detune': 5, 'fm.op3.level': 0.45, 'fm.op3.d': 3, 'fm.op3.s': 0, 'fm.op3.r': 2.5,
      'fm.op4.ratio': 7, 'fm.op4.detune': -3, 'fm.op4.level': 0.28, 'fm.op4.d': 0.8, 'fm.op4.s': 0, 'fm.op4.r': 0.8, 'fm.op4.vel': 0.7, 'fm.op4.kscale': -0.8,
      'aenv.a': 0.001, 'aenv.d': 10, 'aenv.s': 1, 'aenv.r': 3,
      'menv.a': 0.9, 'menv.d': 3, 'menv.s': 0.75, 'menv.r': 2.5,
      'mod1.src': 'menv', 'mod1.dst': 'osc1.level', 'mod1.amt': 0.4,
      'lfo1.rate': 0.25, 'mod2.src': 'lfo1', 'mod2.dst': 'osc1.shape', 'mod2.amt': 0.15,
      'mod3.src': 'wheel', 'mod3.dst': 'filter.cutoff', 'mod3.amt': 0.25,
      'voice.poly': 10, 'amp.vel': 0.7, 'vib.wheel': 12,
      'delay.on': true, 'delay.sync': '1/4D', 'delay.feedback': 0.32, 'delay.pingpong': 0.8, 'delay.tone': 0.45, 'delay.mix': 0.2,
      'reverb.on': true, 'reverb.size': 0.8, 'reverb.decay': 4.5, 'reverb.predelay': 0.03, 'reverb.damp': 0.4, 'reverb.mix': 0.28, 'reverb.shimmer': 0.2,
      'amp.level': 2.5,
    },
    macros: [
      { name: '冰晶 Crystal', targets: [{ id: 'fm.op2.level', amount: 0.2 }, { id: 'fm.op4.level', amount: 0.25 }] },
      { name: '光暈 Halo', targets: [{ id: 'mod1.amt', amount: 0.2 }, { id: 'filter.cutoff', amount: 0.1 }, { id: 'amp.level', amount: -0.08 }] },
      { name: '回聲 Echo', targets: [{ id: 'delay.mix', amount: 0.25 }, { id: 'delay.feedback', amount: 0.25 }, { id: 'amp.level', amount: -0.02 }] },
      { name: '極光 Aurora', targets: [{ id: 'reverb.shimmer', amount: 0.55 }, { id: 'reverb.mix', amount: 0.2 }, { id: 'mod2.amt', amount: 0.3 }, { id: 'amp.level', amount: -0.02 }] },
    ],
    demo: 'pad',
    demoMacros: [{ index: 1, to: 0.9, beat: 2, beats: 8 }, { index: 1, to: 0, beat: 12, beats: 4 }],
  },
  {
    name: 'Wind Chime Garden',
    category: 'bell',
    tags: ['chimes', 'arp', 'random', 'ambient'],
    description: '微風吹過庭院的鋁管風鈴：按住和弦，鈴管便隨機地輕輕互撞，叮叮噹噹不停歇',
    params: {
      'osc1.on': false,
      'phys.on': true, 'phys.level': 0.75, 'phys.model': 'bar', 'phys.exciter': 'mallet', 'phys.hardness': 0.8,
      'phys.position': 0.2, 'phys.decay': 5, 'phys.brightness': 0.62, 'phys.inharm': 1, 'phys.body': 0.2,
      'phys.damp': 0, 'phys.spread': 0.7,
      'aenv.a': 0.001, 'aenv.d': 10, 'aenv.s': 1, 'aenv.r': 5,
      'voice.poly': 16, 'voice.spread': 0.6,
      'arp.on': true, 'arp.mode': 'random', 'arp.rate': '1/8', 'arp.oct': 2, 'arp.gate': 0.3, 'arp.swing': 0.35,
      'mod1.src': 'random', 'mod1.dst': 'amp.level', 'mod1.amt': 0.12,
      'mod2.src': 'random', 'mod2.dst': 'phys.position', 'mod2.amt': 0.2,
      'mod3.src': 'note', 'mod3.dst': 'amp.level', 'mod3.amt': -0.12,
      'mod4.src': 'note', 'mod4.dst': 'phys.brightness', 'mod4.amt': -0.25,
      'mod5.src': 'wheel', 'mod5.dst': 'phys.brightness', 'mod5.amt': 0.3,
      'mod8.src': 'random', 'mod8.dst': 'phys.decay', 'mod8.amt': 0.03,
      'amp.vel': 0.6, 'vib.wheel': 0,
      'reverb.on': true, 'reverb.size': 0.7, 'reverb.decay': 3.5, 'reverb.predelay': 0.025, 'reverb.damp': 0.45, 'reverb.mix': 0.32,
      'amp.level': -1,
    },
    macros: [
      { name: '風力 Breeze', targets: [{ id: 'arp.swing', amount: -0.5 }, { id: 'arp.gate', amount: 0.3 }, { id: 'mod1.amt', amount: 0.08 }, { id: 'amp.level', amount: -0.07 }] },
      { name: '鈴管 Tubes', targets: [{ id: 'phys.inharm', amount: -0.5 }, { id: 'phys.brightness', amount: 0.15 }] },
      { name: '音域 Range', targets: [{ id: 'arp.oct', amount: 0.34 }, { id: 'amp.level', amount: -0.06 }] },
      { name: '庭院 Garden', targets: [{ id: 'reverb.mix', amount: 0.25 }, { id: 'reverb.decay', amount: 0.25 }] },
    ],
    demo: 'arp',
    demoMacros: [{ index: 2, to: 1, beat: 4, beats: 4 }, { index: 2, to: 0, beat: 12, beats: 2 }],
  },
];
