// Drum 打擊 — factory presets.
// Single-instrument voices (kick / snare / clap / hats / ride / world percussion) that also play a groove on the
// 'drum' demo phrase: velocity ghosts the off-beats, and each description says which keys work best.
export default [
  {
    name: 'Thunder Taiko',
    category: 'drum',
    tags: ['taiko', 'tom', 'epic', 'cinematic'],
    description: '雷鳴般的太鼓群：物理鼓皮加上低頻衝擊與大殿殘響，低音區是大太鼓、高音區是締太鼓；C2–C5 最佳。',
    params: {
      'voice.poly': 10, 'voice.pitch': 9,
      'phys.on': true, 'phys.level': 1, 'phys.model': 'membrane', 'phys.exciter': 'mallet', 'phys.hardness': 0.6, 'phys.position': 0.7,
      'phys.decay': 1.0, 'phys.brightness': 0.55, 'phys.inharm': 0.9, 'phys.body': 0.8, 'phys.damp': 0.1, 'phys.spread': 0.5, 'phys.oct': -1,
      'osc1.shape': 0, 'osc1.level': 0, 'osc1.oct': -1, 'osc1.phase': 'reset', 'osc1.drift': 0, 'osc1.filt': 0,
      'aenv.a': 0, 'aenv.d': 3, 'aenv.s': 0, 'aenv.r': 3,
      'fenv.a': 0, 'fenv.d': 0.45, 'fenv.s': 0, 'fenv.r': 0.45,
      'mod3.src': 'fenv', 'mod3.dst': 'osc1.level', 'mod3.amt': 0.8,
      'noise.on': true, 'noise.level': 0.85, 'noise.color': -0.2, 'noise.decay': 0.05, 'noise.width': 0.6,
      'filter.type': 'bp', 'filter.cutoff': 1500, 'filter.res': 0.25, 'filter.key': 0.5, 'filter.vel': 0.25,
      'menv.a': 0, 'menv.d': 0.3, 'menv.r': 0.3, 'menv.curve': 0.3,
      'mod1.src': 'menv', 'mod1.dst': 'voice.pitch', 'mod1.amt': 0.06,
      'mod2.src': 'note', 'mod2.dst': 'voice.pitch', 'mod2.amt': -0.15,
      'mod4.src': 'wheel', 'mod4.dst': 'phys.position', 'mod4.amt': -0.45,
      'mod5.src': 'velocity', 'mod5.dst': 'voice.pitch', 'mod5.amt': 0.02,
      'mod6.src': 'random', 'mod6.dst': 'phys.position', 'mod6.amt': 0.06,
      'mod7.src': 'random', 'mod7.dst': 'voice.pitch', 'mod7.amt': 0.004,
      'amp.vel': 0.95, 'amp.level': 4.5,
      'drive.on': true, 'drive.amount': 0.2, 'drive.tone': 0.45,
      'comp.amount': 0.3, 'eq.low': 3,
      'reverb.on': true, 'reverb.size': 0.85, 'reverb.decay': 2.8, 'reverb.damp': 0.45, 'reverb.mix': 0.22,
    },
    macros: [
      { name: '張力 Tension', targets: [{ id: 'voice.pitch', amount: 0.1 }, { id: 'phys.brightness', amount: 0.2 }] },
      { name: '鼓棒 Stick', targets: [{ id: 'phys.hardness', amount: 0.35 }, { id: 'noise.level', amount: 0.15 }, { id: 'phys.brightness', amount: 0.2 }, { id: 'filter.cutoff', amount: 0.1 }] },
      { name: '殿堂 Hall', targets: [{ id: 'reverb.mix', amount: 0.3 }, { id: 'reverb.decay', amount: 0.15 }] },
      { name: '餘韻 Ring', targets: [{ id: 'phys.decay', amount: 0.15 }] },
    ],
    demo: 'drum',
    demoMacros: [{ index: 2, to: 0.75, beat: 0, beats: 8 }, { index: 0, to: 0.6, beat: 8, beats: 4 }, { index: 0, to: 0, beat: 12, beats: 4 }, { index: 2, to: 0.2, beat: 12, beats: 4 }],
  },
  {
    name: 'Tectonic 808',
    category: 'drum',
    tags: ['808', 'kick', 'sub', 'trap'],
    description: '板塊位移般的 808 長尾大鼓：正弦波從高處俯衝落地，管式飽和讓次低音在小喇叭上也聽得見；C1–C5 都好用。',
    params: {
      'voice.mode': 'mono', 'voice.pitch': -18,
      'osc1.shape': 0, 'osc1.level': 1, 'osc1.semi': -6, 'osc1.phase': 'reset', 'osc1.drift': 0, 'osc1.filt': 0,
      'noise.on': true, 'noise.level': 0.45, 'noise.decay': 0.012, 'noise.width': 0.3,
      'filter.type': 'bp', 'filter.cutoff': 3000, 'filter.key': 0, 'filter.vel': 0.3,
      'aenv.a': 0, 'aenv.d': 0.45, 'aenv.s': 0, 'aenv.r': 0.45, 'aenv.curve': 0.62,
      'menv.a': 0, 'menv.d': 0.18, 'menv.r': 0.18, 'menv.curve': 0.3,
      'mod1.src': 'menv', 'mod1.dst': 'voice.pitch', 'mod1.amt': 0.4,
      'mod2.src': 'note', 'mod2.dst': 'voice.pitch', 'mod2.amt': -0.8,
      'mod3.src': 'wheel', 'mod3.dst': 'osc1.shape', 'mod3.amt': 0.3,
      'mod4.src': 'velocity', 'mod4.dst': 'noise.level', 'mod4.amt': 0.25,
      'amp.vel': 0.55, 'amp.level': 5,
      'drive.on': true, 'drive.type': 'tube', 'drive.amount': 0.35, 'drive.tone': 0.45,
      'comp.amount': 0.25,
      'macro2': 0.5,
    },
    macros: [
      { name: '衝擊 Punch', targets: [{ id: 'mod1.amt', amount: 0.2 }, { id: 'noise.level', amount: 0.3 }] },
      { name: '尾音 Decay', targets: [{ id: 'aenv.d', amount: 0.186 }, { id: 'aenv.r', amount: 0.186 }] },
      { name: '失真 Drive', targets: [{ id: 'drive.amount', amount: 0.5 }] },
      { name: '音高 Tune', targets: [{ id: 'voice.pitch', amount: 0.125 }] },
    ],
    demo: 'bass',
    demoMacros: [{ index: 2, to: 0.8, beat: 4, beats: 4 }, { index: 1, to: 0.8, beat: 8, beats: 4 }, { index: 2, to: 0, beat: 12, beats: 4 }, { index: 1, to: 0, beat: 12, beats: 4 }],
  },
  {
    name: 'Anvil Kick',
    category: 'drum',
    tags: ['kick', 'punchy', 'acoustic'],
    description: '鐵砧般結實的大鼓：鼓皮物理模型加上瞬間俯衝的正弦波與踏板敲擊聲，緊實有力、穿透混音；C1–C5 都好用。',
    params: {
      'voice.mode': 'mono', 'voice.pitch': -18,
      'osc1.shape': 0, 'osc1.level': 1, 'osc1.semi': -6, 'osc1.phase': 'reset', 'osc1.drift': 0, 'osc1.filt': 0,
      'phys.on': true, 'phys.level': 1, 'phys.model': 'membrane', 'phys.exciter': 'mallet', 'phys.hardness': 0.7, 'phys.position': 0.85,
      'phys.decay': 0.3, 'phys.brightness': 0.3, 'phys.inharm': 1, 'phys.body': 0.6, 'phys.damp': 0.2, 'phys.spread': 0.2,
      'noise.on': true, 'noise.level': 0.45, 'noise.color': 0.3, 'noise.decay': 0.008, 'noise.width': 0.2,
      'filter.type': 'bp', 'filter.cutoff': 3500, 'filter.res': 0.3, 'filter.key': 0, 'filter.vel': 0.3,
      'aenv.a': 0, 'aenv.d': 0.42, 'aenv.s': 0, 'aenv.r': 0.42, 'aenv.curve': 0.35,
      'menv.a': 0, 'menv.d': 0.07, 'menv.r': 0.07, 'menv.curve': 0.15,
      'mod1.src': 'menv', 'mod1.dst': 'voice.pitch', 'mod1.amt': 0.45,
      'mod2.src': 'note', 'mod2.dst': 'voice.pitch', 'mod2.amt': -0.8,
      'mod3.src': 'velocity', 'mod3.dst': 'noise.level', 'mod3.amt': 0.3,
      'mod4.src': 'wheel', 'mod4.dst': 'phys.decay', 'mod4.amt': 0.3,
      'amp.vel': 0.6, 'amp.level': 6,
      'drive.on': true, 'drive.amount': 0.25,
      'reverb.on': true, 'reverb.size': 0.3, 'reverb.decay': 0.9, 'reverb.damp': 0.6, 'reverb.predelay': 0.005, 'reverb.mix': 0.04,
      'eq.low': 6, 'eq.mid': 2, 'eq.midfreq': 3000, 'comp.amount': 0.35,
    },
    macros: [
      { name: '衝擊 Punch', targets: [{ id: 'mod1.amt', amount: 0.15 }, { id: 'noise.level', amount: 0.3 }] },
      { name: '鼓腔 Body', targets: [{ id: 'phys.decay', amount: 0.18 }, { id: 'aenv.d', amount: 0.06 }, { id: 'aenv.r', amount: 0.06 }] },
      { name: '悶音 Muffle', targets: [{ id: 'filter.cutoff', amount: -0.25 }, { id: 'phys.brightness', amount: -0.25 }, { id: 'noise.level', amount: -0.2 }] },
      { name: '房間 Room', targets: [{ id: 'reverb.mix', amount: 0.3 }] },
    ],
    demo: 'bass',
    demoMacros: [{ index: 0, to: 0.8, beat: 0, beats: 4 }, { index: 2, to: 0.7, beat: 8, beats: 4 }, { index: 0, to: 0, beat: 12, beats: 4 }, { index: 2, to: 0, beat: 12, beats: 4 }],
  },
  {
    name: 'Cobalt Snare',
    category: 'drum',
    tags: ['snare', 'acoustic', 'crisp'],
    description: '鈷藍色的清脆小鼓：鼓皮共鳴、響線沙沙與鼓腔音調層層疊加，力度越輕越像幽靈音；C2–C5 皆可，越高越像短笛小鼓。',
    params: {
      'voice.poly': 8, 'voice.pitch': -1,
      'phys.on': true, 'phys.level': 1, 'phys.model': 'membrane', 'phys.exciter': 'mallet', 'phys.hardness': 0.75, 'phys.position': 0.45,
      'phys.decay': 0.35, 'phys.brightness': 0.55, 'phys.inharm': 1, 'phys.body': 0.4, 'phys.damp': 0.3, 'phys.spread': 0.4,
      'osc1.shape': 0.15, 'osc1.level': 0.6, 'osc1.phase': 'reset', 'osc1.drift': 0, 'osc1.filt': 0,
      'noise.on': true, 'noise.level': 0.85, 'noise.color': -0.35, 'noise.decay': 0.22, 'noise.width': 0.7,
      'filter.type': 'hp', 'filter.cutoff': 1100, 'filter.res': 0.15, 'filter.key': 0, 'filter.vel': 0.2,
      'filter2.type': 'lp', 'filter2.cutoff': 8000,
      'aenv.a': 0, 'aenv.d': 0.38, 'aenv.s': 0, 'aenv.r': 0.38, 'aenv.curve': 0.35,
      'menv.a': 0, 'menv.d': 0.05, 'menv.r': 0.05, 'menv.curve': 0.2,
      'mod1.src': 'menv', 'mod1.dst': 'voice.pitch', 'mod1.amt': 0.12,
      'mod2.src': 'note', 'mod2.dst': 'voice.pitch', 'mod2.amt': -0.8,
      'mod3.src': 'wheel', 'mod3.dst': 'phys.position', 'mod3.amt': -0.4,
      'mod4.src': 'random', 'mod4.dst': 'phys.position', 'mod4.amt': 0.05,
      'amp.vel': 0.9, 'amp.level': 6,
      'drive.on': true, 'drive.amount': 0.35,
      'reverb.on': true, 'reverb.size': 0.4, 'reverb.decay': 1.2, 'reverb.predelay': 0.01, 'reverb.mix': 0.14,
      'eq.mid': 2, 'eq.midfreq': 220, 'eq.high': 2, 'comp.amount': 0.3,
    },
    macros: [
      { name: '響線 Snares', targets: [{ id: 'noise.level', amount: 0.3 }, { id: 'noise.decay', amount: 0.1 }] },
      { name: '音高 Tune', targets: [{ id: 'voice.pitch', amount: 0.12 }] },
      { name: '厚度 Fat', targets: [{ id: 'osc1.level', amount: 0.25 }, { id: 'phys.decay', amount: 0.1 }, { id: 'aenv.d', amount: 0.04 }, { id: 'aenv.r', amount: 0.04 }] },
      { name: '空間 Space', targets: [{ id: 'reverb.mix', amount: 0.3 }, { id: 'reverb.decay', amount: 0.12 }] },
    ],
    demo: 'drum',
    demoMacros: [{ index: 0, to: 0.8, beat: 0, beats: 8 }, { index: 3, to: 0.6, beat: 4, beats: 4 }, { index: 2, to: 0.7, beat: 8, beats: 4 }, { index: 0, to: 0.2, beat: 12, beats: 4 }, { index: 2, to: 0, beat: 12, beats: 4 }, { index: 3, to: 0, beat: 12, beats: 4 }],
  },
  {
    name: 'Stadium Clap',
    category: 'drum',
    tags: ['clap', 'room', 'electronic'],
    description: '整座球場一起拍手：多層噪音爆發錯落疊加，再推進明亮的房間殘響；C2–C6 都能用，高音區更清脆。',
    params: {
      'voice.poly': 8,
      'osc1.on': false,
      'noise.on': true, 'noise.level': 1, 'noise.color': -0.1, 'noise.decay': 0.02, 'noise.width': 0.5,
      'fm.on': true, 'fm.level': 0.9, 'fm.feedback': 1, 'fm.oct': -2,
      'fm.op1.a': 0.025, 'fm.op1.d': 0.25, 'fm.op1.s': 0, 'fm.op1.r': 0.25, 'fm.op1.vel': 0.5,
      'fm.op2.level': 0.8, 'fm.op3.ratio': 1.41, 'fm.op3.level': 0.8,
      'fm.op4.level': 1, 'fm.op4.d': 5,
      'filter.type': 'lp', 'filter.cutoff': 4500, 'filter.res': 0.2, 'filter.vel': 0.15,
      'filter2.type': 'hp', 'filter2.cutoff': 750,
      'aenv.a': 0, 'aenv.d': 0.5, 'aenv.s': 0, 'aenv.r': 0.5,
      'mod1.src': 'note', 'mod1.dst': 'voice.pitch', 'mod1.amt': -0.5,
      'mod2.src': 'random', 'mod2.dst': 'filter.cutoff', 'mod2.amt': 0.03,
      'mod3.src': 'wheel', 'mod3.dst': 'filter.cutoff', 'mod3.amt': 0.1,
      'mod4.src': 'velocity', 'mod4.dst': 'fm.level', 'mod4.amt': 0.1,
      'amp.vel': 0.7, 'amp.level': 6,
      'drive.on': true, 'drive.amount': 0.5,
      'delay.on': true, 'delay.sync': 'off', 'delay.time': 0.0105, 'delay.feedback': 0.5, 'delay.pingpong': 0.4, 'delay.tone': 0.55, 'delay.wobble': 0.15, 'delay.mix': 0.5,
      'reverb.on': true, 'reverb.size': 0.25, 'reverb.decay': 0.8, 'reverb.predelay': 0.005, 'reverb.mix': 0.4,
      'eq.mid': 12, 'eq.midfreq': 1400, 'eq.high': 3, 'comp.amount': 0.3,
    },
    macros: [
      { name: '人數 Crowd', targets: [{ id: 'delay.feedback', amount: 0.3 }, { id: 'delay.wobble', amount: 0.3 }] },
      { name: '音色 Tone', targets: [{ id: 'filter.cutoff', amount: 0.08 }, { id: 'filter2.cutoff', amount: 0.1 }] },
      { name: '尾音 Tail', targets: [{ id: 'fm.op1.d', amount: 0.12 }, { id: 'fm.op1.r', amount: 0.12 }, { id: 'aenv.d', amount: 0.1 }, { id: 'aenv.r', amount: 0.1 }] },
      { name: '空間 Space', targets: [{ id: 'reverb.mix', amount: 0.3 }, { id: 'reverb.decay', amount: 0.15 }] },
    ],
    demo: 'drum',
    demoMacros: [{ index: 0, to: 0.8, beat: 0, beats: 8 }, { index: 3, to: 0.7, beat: 8, beats: 4 }, { index: 0, to: 0, beat: 12, beats: 4 }, { index: 3, to: 0, beat: 12, beats: 4 }],
  },
  {
    name: 'Quicksilver Hats',
    category: 'drum',
    tags: ['hihat', 'metallic', 'groove'],
    description: '水銀般流動的腳踏鈸：往高音逐漸從閉合張開成長嘶聲；F♯2 閉合、A♯2 開放，調變輪可把鈸踩開。',
    params: {
      'voice.poly': 8,
      'osc1.shape': 1, 'osc1.level': 0.35, 'osc1.oct': 1, 'osc1.drift': 0,
      'osc2.on': true, 'osc2.shape': 1, 'osc2.level': 0.35, 'osc2.oct': 1, 'osc2.semi': 7, 'osc2.fine': 25, 'osc2.drift': 0,
      'noise.on': true, 'noise.level': 0.8, 'noise.color': -0.3, 'noise.width': 0.6,
      'filter.type': 'bp', 'filter.cutoff': 6000, 'filter.res': 0.3, 'filter.key': 0, 'filter.vel': 0.1,
      'filter2.type': 'hp', 'filter2.cutoff': 5500,
      'aenv.a': 0, 'aenv.d': 1.6, 'aenv.s': 0,
      'menv.a': 0, 'menv.d': 10, 'menv.r': 0.05, 'menv.curve': 0.9,
      'mod1.src': 'menv', 'mod1.dst': 'amp.level', 'mod1.amt': 1,
      'mod2.src': 'note', 'mod2.dst': 'menv.d', 'mod2.amt': 1,
      'mod3.src': 'note', 'mod3.dst': 'menv.d', 'mod3.amt': 0.5,
      'mod4.src': 'note', 'mod4.dst': 'voice.pitch', 'mod4.amt': -0.7,
      'mod5.src': 'random', 'mod5.dst': 'filter.cutoff', 'mod5.amt': 0.02,
      'mod6.src': 'wheel', 'mod6.dst': 'menv.d', 'mod6.amt': 0.2,
      'amp.vel': 0.8, 'amp.level': -36,
      'drive.on': true, 'drive.amount': 0.4,
      'reverb.on': true, 'reverb.size': 0.3, 'reverb.decay': 0.8, 'reverb.damp': 0.3, 'reverb.mix': 0.06,
      'eq.mid': 8, 'eq.midfreq': 8000, 'comp.amount': 0.2,
      'macro3': 0.5,
    },
    macros: [
      { name: '開合 Open', targets: [{ id: 'mod3.amt', amount: -0.175 }] },
      { name: '金屬 Metal', targets: [{ id: 'osc1.level', amount: 0.3 }, { id: 'osc2.level', amount: 0.3 }, { id: 'osc1.sync', amount: 0.4 }, { id: 'osc2.sync', amount: 0.3 }] },
      { name: '音色 Tone', targets: [{ id: 'filter.cutoff', amount: 0.08 }] },
      { name: '空間 Space', targets: [{ id: 'reverb.mix', amount: 0.35 }, { id: 'reverb.decay', amount: 0.15 }, { id: 'reverb.size', amount: 0.3 }] },
    ],
    demo: 'drum',
    demoMacros: [{ index: 0, to: 0.7, beat: 0, beats: 8 }, { index: 1, to: 0.8, beat: 4, beats: 4 }, { index: 0, to: 0, beat: 8, beats: 6 }, { index: 1, to: 0, beat: 12, beats: 4 }],
  },
  {
    name: 'Bronze Ride',
    category: 'drum',
    tags: ['ride', 'cymbal', 'jazz'],
    description: '溫潤青銅鑄造的疊音鈸：金屬板模型的密集泛音加上沙沙的嘶聲，力度越大越有鐘心的亮音；C3–C5 最自然。',
    params: {
      'osc1.on': false,
      'phys.on': true, 'phys.level': 1, 'phys.model': 'plate', 'phys.exciter': 'mallet', 'phys.hardness': 0.8, 'phys.position': 0.3,
      'phys.decay': 4, 'phys.inharm': 0.7, 'phys.body': 0.1, 'phys.damp': 0.1, 'phys.spread': 0.7, 'phys.oct': 2,
      'fm.on': true, 'fm.level': 0.45, 'fm.algo': 5, 'fm.oct': 2, 'fm.feedback': 0.3, 'fm.filt': 0,
      'fm.op1.d': 3, 'fm.op1.s': 0, 'fm.op1.r': 2,
      'fm.op2.ratio': 1.41, 'fm.op2.level': 0.8, 'fm.op2.d': 2.5, 'fm.op2.s': 0, 'fm.op2.r': 2,
      'fm.op3.ratio': 1.93, 'fm.op3.level': 0.7, 'fm.op3.d': 2, 'fm.op3.s': 0, 'fm.op3.r': 2,
      'fm.op4.ratio': 2.57, 'fm.op4.level': 0.75, 'fm.op4.d': 1.2, 'fm.op4.s': 0, 'fm.op4.r': 1,
      'noise.on': true, 'noise.color': -0.2, 'noise.decay': 1.5, 'noise.width': 0.8,
      'filter.type': 'hp', 'filter.cutoff': 5000, 'filter.key': 0,
      'aenv.a': 0, 'aenv.d': 6, 'aenv.s': 0, 'aenv.r': 2,
      'mod1.src': 'note', 'mod1.dst': 'voice.pitch', 'mod1.amt': -0.7,
      'mod2.src': 'velocity', 'mod2.dst': 'phys.brightness', 'mod2.amt': 0.15,
      'mod3.src': 'random', 'mod3.dst': 'phys.position', 'mod3.amt': 0.04,
      'mod4.src': 'wheel', 'mod4.dst': 'phys.position', 'mod4.amt': 0.4,
      'mod5.src': 'velocity', 'mod5.dst': 'noise.level', 'mod5.amt': 0.08,
      'amp.vel': 0.7, 'amp.level': -2,
      'reverb.on': true, 'reverb.size': 0.5, 'reverb.decay': 1.8, 'reverb.damp': 0.4, 'reverb.mix': 0.15,
    },
    macros: [
      { name: '鐘心 Bell', targets: [{ id: 'phys.position', amount: 0.5 }, { id: 'phys.hardness', amount: 0.2 }, { id: 'fm.level', amount: -0.25 }, { id: 'noise.level', amount: -0.15 }] },
      { name: '沙沙 Sizzle', targets: [{ id: 'noise.level', amount: 0.3 }, { id: 'noise.decay', amount: 0.2 }] },
      { name: '延音 Sustain', targets: [{ id: 'phys.decay', amount: 0.12 }] },
      { name: '空間 Space', targets: [{ id: 'reverb.mix', amount: 0.3 }] },
    ],
    demo: 'drum',
    demoMacros: [{ index: 0, to: 0.9, beat: 4, beats: 4 }, { index: 1, to: 0.7, beat: 8, beats: 4 }, { index: 0, to: 0, beat: 12, beats: 4 }, { index: 1, to: 0, beat: 12, beats: 4 }],
  },
  {
    name: 'Varanasi Tabla',
    category: 'drum',
    tags: ['tabla', 'indian', 'pitched'],
    description: '恆河畔的塔布拉鼓：鼓皮會「唱」出音高，低音區是渾厚 Bayan、高音區是清亮 Dayan；調變輪可做掌壓滑音。',
    params: {
      'voice.poly': 8,
      'osc1.on': false,
      'phys.on': true, 'phys.level': 1, 'phys.model': 'membrane', 'phys.exciter': 'mallet', 'phys.hardness': 0.55, 'phys.position': 0.3,
      'phys.decay': 1.3, 'phys.brightness': 0.55, 'phys.inharm': 0, 'phys.body': 1, 'phys.damp': 0.4,
      'aenv.a': 0, 'aenv.d': 3, 'aenv.s': 0, 'aenv.r': 1,
      'menv.a': 0, 'menv.d': 0.12, 'menv.r': 0.12, 'menv.curve': 0.3,
      'mod1.src': 'menv', 'mod1.dst': 'voice.pitch', 'mod1.amt': 0.025,
      'mod2.src': 'note', 'mod2.dst': 'voice.pitch', 'mod2.amt': -0.5,
      'mod3.src': 'aftertouch', 'mod3.dst': 'voice.pitch', 'mod3.amt': 0.06,
      'mod4.src': 'wheel', 'mod4.dst': 'voice.pitch', 'mod4.amt': 0.04,
      'mod5.src': 'random', 'mod5.dst': 'phys.position', 'mod5.amt': 0.05,
      'mod6.src': 'note', 'mod6.dst': 'phys.position', 'mod6.amt': -0.4,
      'amp.vel': 0.85, 'amp.level': 4,
      'drive.on': true, 'drive.amount': 0.35,
      'reverb.on': true, 'reverb.size': 0.35, 'reverb.decay': 1.3, 'reverb.damp': 0.55, 'reverb.predelay': 0.01, 'reverb.mix': 0.16,
      'eq.low': 3, 'eq.mid': 6, 'eq.midfreq': 400, 'comp.amount': 0.3,
    },
    macros: [
      { name: '音高 Tune', targets: [{ id: 'voice.pitch', amount: 0.1 }] },
      { name: '指法 Stroke', targets: [{ id: 'phys.position', amount: -0.25 }, { id: 'phys.hardness', amount: 0.25 }] },
      { name: '共鳴 Ring', targets: [{ id: 'phys.decay', amount: 0.15 }, { id: 'phys.brightness', amount: 0.2 }] },
      { name: '空間 Room', targets: [{ id: 'reverb.mix', amount: 0.3 }] },
    ],
    demo: 'drum',
    demoMacros: [{ index: 2, to: 0.6, beat: 0, beats: 8 }, { index: 1, to: 0.7, beat: 4, beats: 4 }, { index: 1, to: 0, beat: 8, beats: 4 }, { index: 0, to: 0.5, beat: 8, beats: 4 }, { index: 0, to: 0, beat: 12, beats: 4 }, { index: 2, to: 0, beat: 12, beats: 4 }],
  },
  {
    name: 'Copper Cowbell',
    category: 'drum',
    tags: ['cowbell', '808', 'percussion'],
    description: '銅鑄般的 808 牛鈴：兩組方波交織出金屬音色與鐘體共鳴，C3–C6 皆宜；轉開回聲巨集就是 Dub 律動。',
    params: {
      'voice.poly': 6,
      'osc1.shape': 1, 'osc1.level': 0.6, 'osc1.oct': 1, 'osc1.drift': 0, 'osc1.phase': 'reset',
      'osc2.on': true, 'osc2.shape': 1, 'osc2.level': 0.6, 'osc2.oct': 1, 'osc2.semi': 7, 'osc2.fine': -20, 'osc2.drift': 0, 'osc2.phase': 'reset',
      'phys.on': true, 'phys.level': 0.35, 'phys.model': 'bell', 'phys.exciter': 'mallet', 'phys.hardness': 0.8, 'phys.decay': 1.2, 'phys.oct': 1, 'phys.filt': 1,
      'filter.type': 'bp', 'filter.cutoff': 1500, 'filter.res': 0.3, 'filter.key': 0.5, 'filter.vel': 0.2,
      'filter2.type': 'lp', 'filter2.cutoff': 7000,
      'aenv.a': 0, 'aenv.d': 0.45, 'aenv.s': 0, 'aenv.r': 0.45, 'aenv.curve': 0.05,
      'mod1.src': 'note', 'mod1.dst': 'voice.pitch', 'mod1.amt': -0.7,
      'mod2.src': 'wheel', 'mod2.dst': 'filter.cutoff', 'mod2.amt': 0.15,
      'mod3.src': 'random', 'mod3.dst': 'osc2.fine', 'mod3.amt': 0.03,
      'amp.vel': 0.8, 'amp.level': 6,
      'drive.on': true, 'drive.type': 'tube', 'drive.amount': 0.2,
      'delay.on': true, 'delay.feedback': 0.4, 'delay.pingpong': 0.8, 'delay.tone': 0.4, 'delay.mix': 0.001,
      'reverb.on': true, 'reverb.size': 0.3, 'reverb.decay': 0.9, 'reverb.mix': 0.1,
    },
    macros: [
      { name: '音高 Tune', targets: [{ id: 'voice.pitch', amount: 0.1 }] },
      { name: '敲擊 Clank', targets: [{ id: 'phys.level', amount: 0.4 }, { id: 'phys.hardness', amount: 0.2 }] },
      { name: '衰減 Decay', targets: [{ id: 'aenv.d', amount: 0.07 }, { id: 'aenv.r', amount: 0.07 }] },
      { name: '回聲 Echo', targets: [{ id: 'delay.mix', amount: 0.35 }] },
    ],
    demo: 'drum',
    demoMacros: [{ index: 3, to: 0.8, beat: 0, beats: 4 }, { index: 1, to: 0.9, beat: 4, beats: 4 }, { index: 0, to: 0.5, beat: 8, beats: 4 }, { index: 0, to: 0, beat: 12, beats: 4 }, { index: 1, to: 0, beat: 12, beats: 4 }, { index: 3, to: 0.2, beat: 12, beats: 4 }],
  },
  {
    name: 'Sandstorm Shaker',
    category: 'drum',
    tags: ['shaker', 'texture', 'groove'],
    description: '沙暴中翻滾的沙鈴：一粒一粒的沙粒質感隨機閃動、左右飄移，力度越大越明亮；整個鍵盤都能用。',
    params: {
      'voice.poly': 8,
      'osc1.on': false,
      'noise.on': true, 'noise.level': 1, 'noise.color': -0.3, 'noise.width': 0.8,
      'filter.type': 'bp', 'filter.cutoff': 4800, 'filter.res': 0.3, 'filter.vel': 0.35,
      'filter2.type': 'hp', 'filter2.cutoff': 2500,
      'aenv.a': 0.014, 'aenv.d': 0.1, 'aenv.s': 0, 'aenv.r': 0.1, 'aenv.curve': 0.6,
      'lfo1.shape': 'sh', 'lfo1.rate': 38,
      'mod1.src': 'lfo1', 'mod1.dst': 'filter.cutoff', 'mod1.amt': 0.04,
      'mod2.src': 'random', 'mod2.dst': 'amp.pan', 'mod2.amt': 0.15,
      'mod3.src': 'random', 'mod3.dst': 'filter.cutoff', 'mod3.amt': 0.03,
      'mod4.src': 'wheel', 'mod4.dst': 'filter.cutoff', 'mod4.amt': 0.06,
      'amp.vel': 0.85, 'amp.level': 4,
      'drive.on': true,
      'reverb.on': true, 'reverb.size': 0.3, 'reverb.decay': 0.8, 'reverb.damp': 0.4, 'reverb.mix': 0.12,
      'eq.mid': 4, 'eq.midfreq': 5000,
      'macro3': 0.5,
    },
    macros: [
      { name: '沙粒 Grain', targets: [{ id: 'mod1.amt', amount: 0.06 }, { id: 'lfo1.rate', amount: -0.1 }] },
      { name: '長度 Length', targets: [{ id: 'aenv.d', amount: 0.04 }, { id: 'aenv.r', amount: 0.04 }, { id: 'aenv.a', amount: 0.06 }] },
      { name: '音色 Tone', targets: [{ id: 'filter.cutoff', amount: 0.065 }] },
      { name: '空間 Space', targets: [{ id: 'reverb.mix', amount: 0.3 }] },
    ],
    demo: 'drum',
    demoMacros: [{ index: 1, to: 0.8, beat: 0, beats: 8 }, { index: 0, to: 0.7, beat: 4, beats: 4 }, { index: 1, to: 0.2, beat: 8, beats: 8 }, { index: 0, to: 0, beat: 12, beats: 4 }],
  },
];
