// FX & Texture 音效/質感 — factory presets.
// Cinematic tools (riser, impact), nature (ocean, wind, rain), sci-fi (laser, radio, glitch, drone) and a granular-ish
// texture. Each preset keeps its loudness near −19 LUFS on its demo phrase, is tamed across the keyboard (key → level or
// cutoff where needed), maps the mod wheel to something expressive, and rides one or two macros in its ▶ demo.
export default [
  // ── 1. Cinematic riser ──
  {
    name: 'Singularity',
    category: 'fx',
    tags: ['riser', 'cinematic', 'build-up'],
    description: '按住就開始升空的電影感上升音效：諧波波表與噪音一同攀升、顫動越來越急，最後沒入微光殘響',
    params: {
      'osc1.mode': 'wavetable', 'osc1.table': 'harmonic', 'osc1.shape': 0.3, 'osc1.unison': 6, 'osc1.detune': 0.35, 'osc1.spread': 1, 'osc1.level': 0.6,
      'osc2.on': true, 'osc2.semi': 7, 'osc2.unison': 3, 'osc2.detune': 0.25, 'osc2.level': 0.3,
      'noise.on': true, 'noise.level': 0.15, 'noise.color': 0.2,
      'filter.type': 'lp', 'filter.cutoff': 450, 'filter.res': 0.45, 'filter.key': 0.4,
      'filter2.type': 'hp', 'filter2.cutoff': 45,
      'aenv.a': 1.5, 'aenv.d': 1, 'aenv.s': 1, 'aenv.r': 1.5, 'aenv.curve': 0.7,
      'menv.a': 7, 'menv.d': 1, 'menv.s': 1, 'menv.r': 8, 'menv.curve': 0.75,
      'lfo1.rate': 3,
      'mod1.src': 'menv', 'mod1.dst': 'voice.pitch', 'mod1.amt': 0.25,
      'mod2.src': 'menv', 'mod2.dst': 'filter.cutoff', 'mod2.amt': 0.45,
      'mod3.src': 'menv', 'mod3.dst': 'osc1.shape', 'mod3.amt': 0.6,
      'mod4.src': 'menv', 'mod4.dst': 'lfo1.rate', 'mod4.amt': 0.2,
      'mod5.src': 'lfo1', 'mod5.dst': 'amp.level', 'mod5.amt': 0.07,
      'mod6.src': 'menv', 'mod6.dst': 'noise.level', 'mod6.amt': 0.35,
      'mod7.src': 'menv', 'mod7.dst': 'amp.level', 'mod7.amt': 0.14,
      'mod8.src': 'note', 'mod8.dst': 'amp.level', 'mod8.amt': -0.08,
      'delay.on': true, 'delay.feedback': 0.4, 'delay.mix': 0.18, 'delay.tone': 0.55,
      'reverb.on': true, 'reverb.size': 0.85, 'reverb.decay': 6, 'reverb.shimmer': 0.3, 'reverb.mix': 0.35,
      'comp.amount': 0.3,
      'amp.level': -8,
    },
    macros: [
      { name: '上升 Rise', targets: [{ id: 'mod1.amt', amount: 0.15 }] },
      { name: '張力 Tension', targets: [{ id: 'filter.res', amount: 0.35 }, { id: 'mod5.amt', amount: 0.05 }, { id: 'amp.level', amount: -0.06 }] },
      { name: '氣流 Air', targets: [{ id: 'noise.level', amount: 0.4 }] },
      { name: '空間 Space', targets: [{ id: 'reverb.mix', amount: 0.3 }, { id: 'reverb.shimmer', amount: 0.4 }] },
    ],
    demo: 'fx',
    demoMacros: [{ index: 0, to: 1, beat: 0, beats: 8 }, { index: 3, to: 0.7, beat: 8, beats: 4 }, { index: 0, to: 0, beat: 12, beats: 4 }, { index: 3, to: 0, beat: 14, beats: 2 }],
  },

  // ── 2. Impact / sub drop ──
  {
    name: 'Gravity Well',
    category: 'fx',
    tags: ['impact', 'sub-drop', 'cinematic'],
    description: '重擊瞬間的金屬爆裂與向下俯衝的次低頻，餘波在巨大空間裡迴盪',
    params: {
      'voice.pitch': -5,
      'osc1.shape': 0, 'osc1.oct': -1, 'osc1.level': 0.9, 'osc1.filt': 0,
      'osc2.on': true, 'osc2.shape': 0.55, 'osc2.oct': -1, 'osc2.level': 0.45,
      'noise.on': true, 'noise.level': 0.7, 'noise.decay': 0.45, 'noise.color': -0.1,
      'phys.on': true, 'phys.model': 'plate', 'phys.exciter': 'mallet', 'phys.hardness': 0.35, 'phys.position': 0.3, 'phys.decay': 3.5,
      'phys.brightness': 0.55, 'phys.inharm': 0.6, 'phys.spread': 0.8, 'phys.level': 0.4, 'phys.damp': 0.2,
      'filter.cutoff': 180, 'filter.res': 0.2, 'filter.env': 0.75, 'filter.key': 0, 'filter.drive': 0.3, 'filter.vel': 0.3,
      'fenv.a': 0, 'fenv.d': 0.7, 'fenv.s': 0, 'fenv.r': 0.5, 'fenv.curve': 0.3,
      'aenv.a': 0, 'aenv.d': 5, 'aenv.s': 0, 'aenv.r': 2.5, 'aenv.curve': 0.55,
      'menv.a': 0, 'menv.d': 1.4, 'menv.r': 1, 'menv.curve': 0.35,
      'mod1.src': 'menv', 'mod1.dst': 'voice.pitch', 'mod1.amt': 0.45,
      'mod2.src': 'note', 'mod2.dst': 'voice.pitch', 'mod2.amt': -0.5,
      'mod3.src': 'wheel', 'mod3.dst': 'phys.level', 'mod3.amt': 0.3, 'vib.wheel': 0,
      'drive.on': true, 'drive.type': 'tube', 'drive.amount': 0.35,
      'reverb.on': true, 'reverb.size': 0.9, 'reverb.decay': 5, 'reverb.damp': 0.6,
      'eq.low': 3,
      'comp.amount': 0.4,
      'amp.level': 2,
    },
    macros: [
      { name: '墜落 Drop', targets: [{ id: 'mod1.amt', amount: 0.25 }, { id: 'menv.d', amount: 0.1 }] },
      { name: '爆裂 Crack', targets: [{ id: 'noise.level', amount: 0.3 }, { id: 'noise.color', amount: 0.2 }, { id: 'filter.env', amount: 0.12 }] },
      { name: '金屬 Metal', targets: [{ id: 'phys.level', amount: 0.45 }, { id: 'phys.decay', amount: 0.12 }, { id: 'amp.level', amount: -0.03 }] },
      { name: '空間 Space', targets: [{ id: 'reverb.mix', amount: 0.3 }, { id: 'reverb.decay', amount: 0.2 }] },
    ],
    demo: 'fx',
    demoMacros: [{ index: 2, to: 0.8, beat: 2, beats: 8 }, { index: 0, to: 0.7, beat: 7, beats: 5 }, { index: 2, to: 0, beat: 14, beats: 2 }, { index: 0, to: 0, beat: 14, beats: 2 }],
  },

  // ── 3. Ocean waves ──
  {
    name: 'Lunar Tide',
    category: 'fx',
    tags: ['ocean', 'nature', 'ambient'],
    description: '月光下的潮汐：浪湧緩緩堆高、碎成浪花再退去，轉動「月光」讓海浪唱出和弦',
    params: {
      'osc1.shape': 0.2, 'osc1.unison': 3, 'osc1.spread': 1, 'osc1.level': 0,
      'noise.on': true, 'noise.level': 0.6, 'noise.color': -0.3,
      'filter.cutoff': 780, 'filter.res': 0.12, 'filter.key': 0.25,
      'filter2.type': 'hp', 'filter2.cutoff': 70,
      'aenv.a': 1.2, 'aenv.s': 1, 'aenv.r': 4,
      'lfo1.rate': 0.18, 'lfo1.phase': 0.75,
      'lfo2.shape': 'smooth', 'lfo2.rate': 0.21,
      'mod1.src': 'lfo1', 'mod1.dst': 'filter.cutoff', 'mod1.amt': 0.2,
      'mod2.src': 'lfo1', 'mod2.dst': 'noise.level', 'mod2.amt': 0.4,
      'mod3.src': 'lfo2', 'mod3.dst': 'filter.cutoff', 'mod3.amt': 0.06,
      'mod4.src': 'lfo2', 'mod4.dst': 'amp.pan', 'mod4.amt': 0.35,
      'mod5.src': 'lfo1', 'mod5.dst': 'noise.color', 'mod5.amt': 0.12,
      'mod6.src': 'wheel', 'mod6.dst': 'filter.cutoff', 'mod6.amt': 0.1, 'vib.wheel': 0,
      'reverb.on': true, 'reverb.size': 0.8, 'reverb.decay': 4, 'reverb.mix': 0.25,
      'comp.amount': 0.35,
      'amp.level': 6,
    },
    macros: [
      { name: '浪湧 Swell', targets: [{ id: 'mod1.amt', amount: 0.05 }, { id: 'mod2.amt', amount: 0.05 }, { id: 'amp.level', amount: -0.05 }] },
      { name: '潮速 Tide', targets: [{ id: 'lfo1.rate', amount: 0.2 }, { id: 'lfo2.rate', amount: 0.2 }] },
      { name: '浪花 Foam', targets: [{ id: 'filter.cutoff', amount: 0.08 }, { id: 'noise.color', amount: 0.15 }] },
      { name: '月光 Moonlight', targets: [{ id: 'osc1.level', amount: 0.3 }, { id: 'noise.level', amount: -0.25 }] },
    ],
    demo: 'fx',
    demoMacros: [{ index: 3, to: 0.8, beat: 4, beats: 8 }, { index: 3, to: 0, beat: 13, beats: 3 }],
  },

  // ── 4. Wind ──
  {
    name: 'Howling Canyon',
    category: 'fx',
    tags: ['wind', 'nature', 'whistle'],
    description: '穿過峽谷的風：氣流隨音高呼嘯，一陣陣襲來又遠去，調變輪讓風聲更尖銳',
    params: {
      'osc1.on': false,
      'noise.on': true, 'noise.level': 0.9, 'noise.color': -0.2,
      'filter.type': 'lp', 'filter.cutoff': 523, 'filter.res': 0.72, 'filter.key': 1,
      'filter2.type': 'hp', 'filter2.cutoff': 110,
      'aenv.a': 1.2, 'aenv.s': 1, 'aenv.r': 2.5, 'aenv.curve': 0.7,
      'lfo1.shape': 'smooth', 'lfo1.rate': 0.9,
      'lfo2.shape': 'smooth', 'lfo2.rate': 0.3,
      'mod1.src': 'lfo1', 'mod1.dst': 'filter.cutoff', 'mod1.amt': 0.02,
      'mod2.src': 'lfo2', 'mod2.dst': 'amp.level', 'mod2.amt': 0.12,
      'mod3.src': 'lfo2', 'mod3.dst': 'filter.cutoff', 'mod3.amt': 0.04,
      'mod4.src': 'lfo1', 'mod4.dst': 'amp.pan', 'mod4.amt': 0.4,
      'mod5.src': 'wheel', 'mod5.dst': 'filter.res', 'mod5.amt': 0.2, 'vib.wheel': 0,
      'mod6.src': 'note', 'mod6.dst': 'amp.level', 'mod6.amt': -0.1,
      'reverb.on': true, 'reverb.size': 0.9, 'reverb.decay': 5, 'reverb.predelay': 0.05,
      'amp.level': -6.5,
    },
    macros: [
      { name: '陣風 Gust', targets: [{ id: 'mod2.amt', amount: 0.05 }, { id: 'mod3.amt', amount: 0.04 }, { id: 'lfo2.rate', amount: 0.12 }, { id: 'amp.level', amount: -0.06 }] },
      { name: '呼嘯 Howl', targets: [{ id: 'filter.res', amount: 0.2 }, { id: 'amp.level', amount: -0.05 }] },
      { name: '寒意 Chill', targets: [{ id: 'filter.cutoff', amount: 0.06 }, { id: 'noise.color', amount: 0.15 }, { id: 'amp.level', amount: 0.03 }] },
      { name: '峽谷 Canyon', targets: [{ id: 'reverb.mix', amount: 0.3 }, { id: 'reverb.decay', amount: 0.2 }, { id: 'reverb.predelay', amount: 0.3 }] },
    ],
    demo: 'fx',
    demoMacros: [{ index: 0, to: 0.9, beat: 0, beats: 6 }, { index: 1, to: 0.8, beat: 6, beats: 6 }, { index: 0, to: 0, beat: 13, beats: 3 }, { index: 1, to: 0, beat: 13, beats: 3 }],
  },

  // ── 5. Laser zap ──
  {
    name: 'Photon Blaster',
    category: 'fx',
    tags: ['laser', 'sci-fi', 'zap'],
    description: '復古科幻雷射槍：同步鋸齒波一路俯衝，乒乓回聲在左右來回彈射',
    params: {
      'voice.pitch': -12,
      'osc1.sync': 0.2, 'osc1.oct': 1, 'osc1.unison': 2, 'osc1.detune': 0.12, 'osc1.level': 0.9,
      'osc2.on': true, 'osc2.shape': 0.35, 'osc2.level': 0.4,
      'filter.cutoff': 2600, 'filter.res': 0.4, 'filter.key': 0.2,
      'aenv.a': 0, 'aenv.d': 0.5, 'aenv.s': 0, 'aenv.r': 0.15,
      'menv.a': 0, 'menv.d': 0.28, 'menv.r': 0.2, 'menv.curve': 0.25,
      'mod1.src': 'menv', 'mod1.dst': 'voice.pitch', 'mod1.amt': 0.36,
      'mod2.src': 'menv', 'mod2.dst': 'osc1.sync', 'mod2.amt': 0.3,
      'mod3.src': 'velocity', 'mod3.dst': 'filter.cutoff', 'mod3.amt': 0.1,
      'mod4.src': 'wheel', 'mod4.dst': 'osc1.sync', 'mod4.amt': 0.3, 'vib.wheel': 0,
      'delay.on': true, 'delay.feedback': 0.45, 'delay.pingpong': 0.9, 'delay.mix': 0.28, 'delay.tone': 0.6,
      'reverb.on': true, 'reverb.size': 0.5, 'reverb.mix': 0.15,
      'comp.amount': 0.25,
      'amp.level': 6,
    },
    macros: [
      { name: '俯衝 Sweep', targets: [{ id: 'mod1.amt', amount: 0.19 }] },
      { name: '長度 Length', targets: [{ id: 'menv.d', amount: 0.15 }, { id: 'aenv.d', amount: 0.12 }, { id: 'amp.level', amount: -0.06 }] },
      { name: '同步 Sync', targets: [{ id: 'osc1.sync', amount: 0.5 }] },
      { name: '回聲 Echo', targets: [{ id: 'delay.mix', amount: 0.25 }, { id: 'delay.feedback', amount: 0.3 }] },
    ],
    demo: 'pluck',
    demoMacros: [{ index: 0, to: 1, beat: 0, beats: 8 }, { index: 3, to: 0.8, beat: 8, beats: 4 }, { index: 0, to: 0, beat: 12, beats: 4 }, { index: 3, to: 0, beat: 14, beats: 2 }],
  },

  // ── 6. Alien radio ──
  {
    name: 'Numbers Station',
    category: 'fx',
    tags: ['radio', 'sci-fi', 'glitch'],
    description: '來自深空的神秘短波電台：機械嗓音不停低語，夾雜靜電與失真',
    params: {
      'osc1.level': 0.6,
      'fm.on': true, 'fm.feedback': 0.3, 'fm.level': 0.5,
      'fm.op2.ratio': 2.01, 'fm.op2.level': 0.35, 'fm.op3.ratio': 3.5, 'fm.op3.level': 0.3, 'fm.op4.ratio': 0.5, 'fm.op4.level': 0.3,
      'noise.on': true, 'noise.level': 0.08, 'noise.color': -0.4, 'noise.filt': 0.6,
      'filter.type': 'formant', 'filter.cutoff': 1600, 'filter.res': 0.55,
      'filter2.type': 'bp', 'filter2.cutoff': 1400, 'filter2.res': 0.05,
      'aenv.a': 0.05, 'aenv.s': 1, 'aenv.r': 0.8,
      'lfo1.shape': 'sh', 'lfo1.rate': 7,
      'lfo2.shape': 'sh', 'lfo2.rate': 23,
      'mod1.src': 'lfo1', 'mod1.dst': 'filter.vowel', 'mod1.amt': 0.6,
      'mod2.src': 'lfo1', 'mod2.dst': 'voice.pitch', 'mod2.amt': 0.1,
      'mod3.src': 'lfo1', 'mod3.dst': 'fm.op2.level', 'mod3.amt': 0.3,
      'mod4.src': 'lfo2', 'mod4.dst': 'noise.level', 'mod4.amt': 0.2,
      'mod5.src': 'note', 'mod5.dst': 'amp.level', 'mod5.amt': -0.2,
      'mod6.src': 'wheel', 'mod6.dst': 'lfo1.rate', 'mod6.amt': 0.15, 'vib.wheel': 0,
      'drive.on': true, 'drive.type': 'crush', 'drive.amount': 0.35, 'drive.tone': 0.3, 'drive.mix': 0.6,
      'delay.on': true, 'delay.sync': '1/8', 'delay.mix': 0.18,
      'reverb.on': true, 'reverb.size': 0.4, 'reverb.mix': 0.2,
      'eq.low': -10, 'eq.high': -3,
      'amp.level': -2,
    },
    macros: [
      { name: '語速 Chatter', targets: [{ id: 'lfo1.rate', amount: 0.2 }] },
      { name: '調頻 Warp', targets: [{ id: 'mod2.amt', amount: 0.1 }, { id: 'fm.op2.level', amount: 0.3 }, { id: 'fm.feedback', amount: 0.3 }] },
      { name: '靜電 Static', targets: [{ id: 'noise.level', amount: 0.35 }] },
      { name: '失真 Crush', targets: [{ id: 'drive.amount', amount: 0.45 }, { id: 'drive.mix', amount: 0.4 }] },
    ],
    demo: 'fx',
    demoMacros: [{ index: 3, to: 0.7, beat: 4, beats: 6 }, { index: 0, to: 0.8, beat: 8, beats: 4 }, { index: 3, to: 0, beat: 14, beats: 2 }, { index: 0, to: 0, beat: 14, beats: 2 }],
  },

  // ── 7. Glitch stutter ──
  {
    name: 'Data Corruption',
    category: 'fx',
    tags: ['glitch', 'stutter', 'bitcrush'],
    description: '資料損毀般的故障切片：和弦被切成三十二分音符的碎片、八度翻轉與位元壓碎，每一拍都在斷裂重組',
    params: {
      'arp.on': true, 'arp.mode': 'chord', 'arp.rate': '1/32', 'arp.oct': 2, 'arp.gate': 0.4,
      'voice.pitch': -6,
      'osc1.mode': 'wavetable', 'osc1.table': 'digital', 'osc1.shape': 0.4, 'osc1.level': 0.75,
      'osc2.on': true, 'osc2.shape': 1, 'osc2.pw': 0.3, 'osc2.oct': -1, 'osc2.level': 0.3,
      'filter.type': 'ladder12', 'filter.cutoff': 2000, 'filter.res': 0.35, 'filter.env': 0.3, 'filter.key': 0,
      'filter2.type': 'hp', 'filter2.cutoff': 90,
      'fenv.a': 0, 'fenv.d': 0.08, 'fenv.s': 0,
      'aenv.a': 0, 'aenv.d': 0.12, 'aenv.s': 0.35, 'aenv.r': 0.04,
      'lfo1.shape': 'sh', 'lfo1.sync': '1/16',
      'lfo2.shape': 'square', 'lfo2.sync': '1/8T',
      'mod1.src': 'lfo1', 'mod1.dst': 'osc1.shape', 'mod1.amt': 0.5,
      'mod2.src': 'lfo1', 'mod2.dst': 'filter.cutoff', 'mod2.amt': 0.15,
      'mod3.src': 'lfo1', 'mod3.dst': 'amp.level', 'mod3.amt': 0.25,
      'mod4.src': 'lfo2', 'mod4.dst': 'voice.pitch', 'mod4.amt': 0.125,
      'mod5.src': 'random', 'mod5.dst': 'amp.pan', 'mod5.amt': 0.7,
      'mod6.src': 'wheel', 'mod6.dst': 'filter.cutoff', 'mod6.amt': 0.2, 'vib.wheel': 0,
      'drive.on': true, 'drive.type': 'crush', 'drive.amount': 0.4, 'drive.tone': 0.3, 'drive.mix': 0.7,
      'delay.on': true, 'delay.sync': '1/16', 'delay.feedback': 0.5, 'delay.mix': 0.2, 'delay.pingpong': 0.8,
      'reverb.on': true, 'reverb.size': 0.35, 'reverb.mix': 0.12,
      'amp.level': -1,
    },
    macros: [
      { name: '故障 Glitch', targets: [{ id: 'mod1.amt', amount: 0.2 }, { id: 'mod2.amt', amount: 0.1 }, { id: 'mod3.amt', amount: 0.08 }] },
      { name: '位元 Bits', targets: [{ id: 'drive.amount', amount: 0.45 }, { id: 'drive.mix', amount: 0.3 }] },
      { name: '切片 Chop', targets: [{ id: 'arp.gate', amount: -0.4 }, { id: 'aenv.s', amount: -0.25 }, { id: 'amp.level', amount: 0.11 }] },
      { name: '回聲 Echo', targets: [{ id: 'delay.mix', amount: 0.22 }, { id: 'delay.feedback', amount: 0.25 }, { id: 'amp.level', amount: -0.03 }] },
    ],
    demo: 'arp',
    demoMacros: [{ index: 1, to: 0.8, beat: 0, beats: 8 }, { index: 2, to: 0.8, beat: 8, beats: 4 }, { index: 1, to: 0, beat: 12, beats: 4 }, { index: 2, to: 0, beat: 14, beats: 2 }],
  },

  // ── 8. Rain drops ──
  {
    name: 'Glass Rain',
    category: 'fx',
    tags: ['rain', 'droplets', 'ambient'],
    description: '按住和弦，音符就化作玻璃雨滴隨機灑落，輕重不一地濺在左右聲場，漣漪在殘響裡擴散',
    params: {
      'arp.on': true, 'arp.mode': 'random', 'arp.rate': '1/32', 'arp.oct': 2, 'arp.gate': 0.25,
      'osc1.shape': 0, 'osc1.oct': 1, 'osc1.level': 0.5,
      'phys.on': true, 'phys.model': 'glass', 'phys.exciter': 'mallet', 'phys.hardness': 0.85, 'phys.position': 0.4, 'phys.decay': 0.5,
      'phys.brightness': 0.75, 'phys.spread': 0.7, 'phys.level': 0.7, 'phys.oct': 1, 'phys.damp': 0.1,
      'noise.on': true, 'noise.level': 0.18, 'noise.decay': 0.03,
      'filter.type': 'hp', 'filter.cutoff': 160, 'filter.res': 0, 'filter.key': 0,
      'aenv.a': 0.002, 'aenv.s': 0, 'aenv.r': 0.25,
      'menv.a': 0, 'menv.d': 0.04, 'menv.curve': 0.3,
      'mod1.src': 'menv', 'mod1.dst': 'voice.pitch', 'mod1.amt': -0.2,
      'mod2.src': 'random', 'mod2.dst': 'amp.pan', 'mod2.amt': 0.8,
      'mod3.src': 'random', 'mod3.dst': 'amp.level', 'mod3.amt': 0.18,
      'mod4.src': 'random', 'mod4.dst': 'phys.hardness', 'mod4.amt': 0.15,
      'mod5.src': 'wheel', 'mod5.dst': 'phys.decay', 'mod5.amt': 0.15, 'vib.wheel': 0,
      'delay.on': true, 'delay.feedback': 0.3, 'delay.mix': 0.18, 'delay.pingpong': 1, 'delay.tone': 0.4,
      'reverb.on': true, 'reverb.size': 0.8, 'reverb.decay': 4.5, 'reverb.mix': 0.35,
      'comp.amount': 0.3,
      'amp.level': 6,
    },
    macros: [
      { name: '雨勢 Downpour', targets: [{ id: 'mod3.amt', amount: -0.12 }, { id: 'arp.gate', amount: 0.25 }] },
      { name: '水滴 Drop', targets: [{ id: 'mod1.amt', amount: -0.12 }, { id: 'osc1.level', amount: 0.3 }] },
      { name: '水花 Splash', targets: [{ id: 'noise.level', amount: 0.3 }, { id: 'phys.hardness', amount: 0.15 }] },
      { name: '空間 Space', targets: [{ id: 'reverb.mix', amount: 0.3 }, { id: 'delay.mix', amount: 0.2 }] },
    ],
    demo: 'pad',
    demoMacros: [{ index: 0, to: 1, beat: 0, beats: 8 }, { index: 3, to: 0.7, beat: 6, beats: 6 }, { index: 0, to: 0, beat: 12, beats: 4 }, { index: 3, to: 0, beat: 14, beats: 2 }],
  },

  // ── 9. Sci-fi drone ──
  {
    name: 'Derelict Starship',
    category: 'fx',
    tags: ['drone', 'sci-fi', 'dark'],
    description: '漂流在深空的廢棄星艦：低沉引擎轟鳴、金屬艙壁的呻吟與緩慢掃過的相位，轉動「脈動」讓引擎重新啟動',
    params: {
      'osc1.mode': 'wavetable', 'osc1.table': 'growl', 'osc1.shape': 0.3, 'osc1.unison': 3, 'osc1.detune': 0.15, 'osc1.level': 0.7,
      'osc2.on': true, 'osc2.fine': 9, 'osc2.level': 0.3,
      'fm.on': true, 'fm.algo': 2, 'fm.feedback': 0.4, 'fm.level': 0.35, 'fm.op2.ratio': 1.41, 'fm.op2.level': 0.4, 'fm.op3.ratio': 2.76, 'fm.op3.level': 0.25,
      'noise.on': true, 'noise.level': 0.15, 'noise.color': -0.5,
      'filter.cutoff': 900, 'filter.res': 0.5, 'filter.drive': 0.4, 'filter.key': 0.4,
      'filter2.type': 'hp', 'filter2.cutoff': 45,
      'aenv.a': 1.5, 'aenv.s': 1, 'aenv.r': 3,
      'lfo1.shape': 'tri', 'lfo1.sync': '1/8', 'lfo1.mode': 'mono',
      'lfo2.shape': 'smooth', 'lfo2.rate': 0.15,
      'mod1.src': 'lfo2', 'mod1.dst': 'osc1.shape', 'mod1.amt': 0.3,
      'mod2.src': 'lfo2', 'mod2.dst': 'filter.cutoff', 'mod2.amt': 0.1,
      'mod3.src': 'lfo2', 'mod3.dst': 'fm.op2.level', 'mod3.amt': 0.2,
      'mod4.src': 'lfo1', 'mod4.dst': 'amp.level',
      'mod5.src': 'lfo1', 'mod5.dst': 'filter.cutoff',
      'mod6.src': 'wheel', 'mod6.dst': 'fm.level', 'mod6.amt': 0.3, 'vib.wheel': 0,
      'phaser.on': true, 'phaser.rate': 0.08, 'phaser.feedback': 0.7, 'phaser.mix': 0.45,
      'drive.on': true, 'drive.type': 'tube', 'drive.amount': 0.25,
      'delay.on': true, 'delay.sync': '1/4D', 'delay.feedback': 0.4, 'delay.mix': 0.15, 'delay.tone': 0.3,
      'reverb.on': true, 'reverb.size': 0.9, 'reverb.decay': 7, 'reverb.damp': 0.7, 'reverb.mix': 0.35,
      'eq.low': -2,
      'amp.level': 2.5,
    },
    macros: [
      { name: '深淵 Abyss', targets: [{ id: 'voice.pitch', amount: -0.25 }, { id: 'filter.cutoff', amount: -0.05 }, { id: 'reverb.decay', amount: 0.15 }, { id: 'amp.level', amount: 0.07 }] },
      { name: '機械 Machine', targets: [{ id: 'fm.level', amount: 0.4 }, { id: 'fm.feedback', amount: 0.3 }] },
      { name: '脈動 Pulse', targets: [{ id: 'mod4.amt', amount: 0.06 }, { id: 'mod5.amt', amount: 0.08 }] },
      { name: '空間 Space', targets: [{ id: 'reverb.mix', amount: 0.3 }, { id: 'delay.mix', amount: 0.2 }] },
    ],
    demo: 'fx',
    demoMacros: [{ index: 2, to: 1, beat: 2, beats: 8 }, { index: 1, to: 0.7, beat: 6, beats: 6 }, { index: 2, to: 0, beat: 13, beats: 3 }, { index: 1, to: 0, beat: 13, beats: 3 }],
  },

  // ── 10. Granular nebula texture ──
  {
    name: 'Stardust Nebula',
    category: 'fx',
    tags: ['texture', 'granular', 'shimmer'],
    description: '星塵般的顆粒雲：玻璃波表碎成閃爍的微粒，在左右聲場間飄散並沒入微光殘響',
    params: {
      'osc1.mode': 'wavetable', 'osc1.table': 'glass', 'osc1.shape': 0.35, 'osc1.unison': 5, 'osc1.detune': 0.25, 'osc1.spread': 1, 'osc1.level': 0.55,
      'phys.on': true, 'phys.model': 'glass', 'phys.exciter': 'bow', 'phys.pressure': 0.45, 'phys.decay': 10, 'phys.inharm': 0.2, 'phys.spread': 0.7, 'phys.level': 0.3, 'phys.oct': 2,
      'filter.type': 'lp', 'filter.cutoff': 3500, 'filter.res': 0.2,
      'filter2.type': 'hp', 'filter2.cutoff': 110,
      'aenv.a': 1.2, 'aenv.s': 1, 'aenv.r': 4,
      'lfo1.shape': 'sh', 'lfo1.rate': 14,
      'lfo2.shape': 'smooth', 'lfo2.rate': 0.12,
      'mod1.src': 'lfo1', 'mod1.dst': 'osc1.shape', 'mod1.amt': 0.2,
      'mod2.src': 'lfo1', 'mod2.dst': 'amp.pan', 'mod2.amt': 0.5,
      'mod3.src': 'lfo1', 'mod3.dst': 'amp.level', 'mod3.amt': 0.06,
      'mod4.src': 'lfo2', 'mod4.dst': 'filter.cutoff', 'mod4.amt': 0.15,
      'mod5.src': 'lfo2', 'mod5.dst': 'osc1.shape', 'mod5.amt': 0.25,
      'mod6.src': 'lfo1', 'mod6.dst': 'osc1.fine', 'mod6.amt': 0.12,
      'mod7.src': 'wheel', 'mod7.dst': 'osc1.shape', 'mod7.amt': 0.3, 'vib.wheel': 0,
      'chorus.on': true, 'chorus.mode': 'ensemble', 'chorus.mix': 0.4,
      'delay.on': true, 'delay.sync': '1/4D', 'delay.feedback': 0.5, 'delay.wobble': 0.4,
      'reverb.on': true, 'reverb.size': 0.95, 'reverb.decay': 9, 'reverb.shimmer': 0.4, 'reverb.mix': 0.45,
      'amp.level': 1,
    },
    macros: [
      { name: '顆粒 Grain', targets: [{ id: 'mod3.amt', amount: 0.12 }, { id: 'mod6.amt', amount: 0.1 }, { id: 'mod1.amt', amount: 0.15 }, { id: 'amp.level', amount: -0.04 }] },
      { name: '演化 Evolve', targets: [{ id: 'mod4.amt', amount: 0.15 }, { id: 'mod5.amt', amount: 0.25 }] },
      { name: '微光 Shimmer', targets: [{ id: 'reverb.shimmer', amount: 0.4 }, { id: 'phys.level', amount: 0.3 }] },
      { name: '亮度 Bright', targets: [{ id: 'filter.cutoff', amount: 0.2 }] },
    ],
    demo: 'fx',
    demoMacros: [{ index: 0, to: 1, beat: 0, beats: 8 }, { index: 2, to: 0.8, beat: 6, beats: 6 }, { index: 0, to: 0, beat: 12, beats: 4 }, { index: 2, to: 0, beat: 14, beats: 2 }],
  },
];
