// Keys 鍵盤 — factory presets. Flagship first. Loudness-calibrated on each preset's demo phrase (≈ −19 LUFS, peaks ≤ −1 dBFS).
export default [
  {
    name: 'Moonlit Suitcase',
    category: 'keys',
    tags: ['electric piano', 'fm', 'tremolo', 'lush'],
    description: '月光下的皮箱電鋼琴：溫潤的音叉鐘鳴在左右聲道間搖曳，推起「綻放」便湧出一層絲絨般的鋪底。',
    params: {
      'osc1.level': 0, 'osc1.unison': 3, 'osc1.detune': 0.22, 'osc1.spread': 0.8, 'osc1.drift': 0.25,
      'fm.on': true, 'fm.level': 0.9, 'fm.filt': 0, 'fm.algo': 3, 'fm.feedback': 0.08,
      'fm.op1.level': 0.95, 'fm.op1.d': 5.5, 'fm.op1.s': 0, 'fm.op1.r': 0.45, 'fm.op1.vel': 0.35, 'fm.op1.kscale': -0.15,
      'fm.op2.level': 0.33, 'fm.op2.d': 1.8, 'fm.op2.s': 0.12, 'fm.op2.r': 0.45, 'fm.op2.vel': 0.85, 'fm.op2.kscale': -0.35,
      'fm.op3.detune': 3, 'fm.op3.level': 0.55, 'fm.op3.d': 2.4, 'fm.op3.s': 0, 'fm.op3.r': 0.35, 'fm.op3.vel': 0.5, 'fm.op3.kscale': -0.2,
      'fm.op4.ratio': 14, 'fm.op4.level': 0.25, 'fm.op4.d': 0.32, 'fm.op4.s': 0, 'fm.op4.r': 0.2, 'fm.op4.vel': 0.75, 'fm.op4.kscale': -0.5,
      'filter.cutoff': 900, 'filter.res': 0.15, 'filter.key': 0.5,
      'aenv.a': 0, 'aenv.d': 10, 'aenv.s': 1, 'aenv.r': 0.6, 'amp.vel': 0.6,
      'menv.a': 1.4, 'menv.d': 2, 'menv.s': 1, 'menv.r': 1, 'menv.curve': 0.6,
      'lfo1.rate': 4.2, 'lfo1.mode': 'mono',
      'mod1.src': 'lfo1', 'mod1.dst': 'amp.pan', 'mod1.amt': 0.14,
      'mod2.src': 'menv', 'mod2.dst': 'osc1.level', 'mod2.amt': 0.2,
      'mod3.src': 'wheel', 'mod3.dst': 'fm.op2.level', 'mod3.amt': 0.25,
      'vib.wheel': 0,
      'chorus.on': true, 'chorus.rate': 0.35, 'chorus.depth': 0.35, 'chorus.mix': 0.25,
      'delay.on': true, 'delay.mix': 0, 'delay.feedback': 0.3, 'delay.tone': 0.35, 'delay.pingpong': 0.9,
      'reverb.on': true, 'reverb.size': 0.55, 'reverb.decay': 2.4, 'reverb.mix': 0.2, 'reverb.damp': 0.45,
      'comp.amount': 0.2,
    },
    macros: [
      { name: '咆哮 Bark', targets: [{ id: 'fm.op2.level', amount: 0.25 }, { id: 'fm.op4.level', amount: 0.15 }] },
      { name: '顫音 Tremolo', targets: [{ id: 'mod1.amt', amount: 0.18 }, { id: 'lfo1.rate', amount: 0.06 }] },
      { name: '綻放 Bloom', targets: [{ id: 'mod2.amt', amount: 0.25 }, { id: 'reverb.shimmer', amount: 0.3 }] },
      { name: '空間 Space', targets: [{ id: 'reverb.mix', amount: 0.3 }, { id: 'reverb.decay', amount: 0.2 }, { id: 'delay.mix', amount: 0.18 }] },
    ],
    demo: 'keys',
    demoMacros: [{ index: 1, to: 0.75, beat: 2, beats: 4 }, { index: 2, to: 0.9, beat: 8, beats: 6 }, { index: 0, to: 0.5, beat: 12, beats: 4 }, { index: 3, to: 0.6, beat: 16, beats: 4 }],
  },
  {
    name: 'Ivory Hall Grand',
    category: 'keys',
    tags: ['piano', 'acoustic', 'physical'],
    description: '音樂廳裡的平台鋼琴：琴槌力度決定明暗，低音渾厚、高音清亮，踩下踏板讓琴弦自由共鳴。',
    params: {
      'osc1.on': false,
      'phys.on': true, 'phys.level': 0.9, 'phys.exciter': 'mallet',
      'phys.hardness': 0.48, 'phys.position': 0.12, 'phys.decay': 9, 'phys.brightness': 0.55, 'phys.inharm': 0.3,
      'phys.body': 0.35, 'phys.spread': 0.4, 'phys.damp': 0.8, 'phys.filt': 1,
      'noise.on': true, 'noise.level': 0.06, 'noise.color': -0.4, 'noise.decay': 0.05, 'noise.width': 0.5, 'noise.filt': 0,
      'filter.on': false, 'filter2.type': 'hp', 'filter2.cutoff': 35,
      'aenv.a': 0, 'aenv.d': 10, 'aenv.s': 1, 'aenv.r': 2.5, 'amp.vel': 0.75,
      'mod1.src': 'note', 'mod1.dst': 'phys.decay', 'mod1.amt': -0.14,
      'mod2.src': 'velocity', 'mod2.dst': 'phys.brightness', 'mod2.amt': 0.15,
      'mod3.src': 'note', 'mod3.dst': 'filter2.cutoff', 'mod3.amt': 0.2,
      'mod4.src': 'note', 'mod4.dst': 'amp.level', 'mod4.amt': -0.08,
      'mod5.src': 'wheel', 'mod5.dst': 'phys.brightness', 'mod5.amt': -0.25,
      'mod6.src': 'wheel', 'mod6.dst': 'phys.hardness', 'mod6.amt': -0.2,
      'mod7.src': 'wheel', 'mod7.dst': 'amp.level', 'mod7.amt': -0.1,
      'vib.wheel': 0,
      'reverb.on': true, 'reverb.size': 0.72, 'reverb.decay': 2.8, 'reverb.predelay': 0.025, 'reverb.damp': 0.55, 'reverb.mix': 0.2,
      'eq.low': 3, 'comp.amount': 0.15,
    },
    macros: [
      { name: '觸鍵 Touch', targets: [{ id: 'phys.hardness', amount: 0.25 }, { id: 'phys.brightness', amount: 0.15 }] },
      { name: '踏板 Pedal', targets: [{ id: 'phys.damp', amount: -0.7 }, { id: 'phys.decay', amount: 0.08 }, { id: 'aenv.r', amount: 0.1 }] },
      { name: '共鳴 Resonance', targets: [{ id: 'phys.body', amount: 0.4 }, { id: 'phys.spread', amount: 0.4 }] },
      { name: '音樂廳 Hall', targets: [{ id: 'reverb.mix', amount: 0.3 }, { id: 'reverb.decay', amount: 0.15 }, { id: 'reverb.size', amount: 0.2 }] },
    ],
    demo: 'keys',
    demoMacros: [{ index: 0, to: 0.6, beat: 4, beats: 4 }, { index: 1, to: 1, beat: 8, beats: 1 }, { index: 3, to: 0.7, beat: 12, beats: 6 }],
  },
  {
    name: 'Felt Lullaby',
    category: 'keys',
    tags: ['piano', 'felt', 'intimate'],
    description: '蓋上毛氈的直立鋼琴，貼近琴槌錄下的柔軟觸鍵與木頭機械聲，像深夜裡哼給自己聽的搖籃曲。',
    params: {
      'osc1.on': false,
      'phys.on': true, 'phys.exciter': 'mallet', 'phys.hardness': 0.16, 'phys.position': 0.2, 'phys.decay': 7,
      'phys.brightness': 0.35, 'phys.inharm': 0.32, 'phys.damp': 0.75, 'phys.filt': 1,
      'filter.type': 'lp', 'filter.cutoff': 2200, 'filter.res': 0.05, 'filter.key': 0.4, 'filter.vel': 0.25,
      'noise.on': true, 'noise.level': 0.35, 'noise.color': -0.3, 'noise.decay': 0.12, 'noise.width': 0.3,
      'filter2.type': 'hp', 'filter2.cutoff': 45,
      'aenv.a': 0, 'aenv.d': 10, 'aenv.s': 1, 'aenv.r': 1.5, 'amp.vel': 0.7, 'amp.level': -3.5,
      'mod1.src': 'note', 'mod1.dst': 'phys.decay', 'mod1.amt': -0.12,
      'mod2.src': 'note', 'mod2.dst': 'phys.hardness', 'mod2.amt': 0.3,
      'mod3.src': 'note', 'mod3.dst': 'filter2.cutoff', 'mod3.amt': 0.2,
      'mod4.src': 'wheel', 'mod4.dst': 'filter.cutoff', 'mod4.amt': 0.15,
      'vib.wheel': 0,
      'reverb.on': true, 'reverb.size': 0.35, 'reverb.decay': 1.4, 'reverb.damp': 0.7, 'reverb.mix': 0.18, 'reverb.predelay': 0.01,
      'eq.low': 2, 'eq.high': -2, 'comp.amount': 0.3,
    },
    macros: [
      { name: '氈布 Felt', targets: [{ id: 'phys.hardness', amount: -0.12 }, { id: 'filter.cutoff', amount: -0.1 }, { id: 'phys.brightness', amount: -0.15 }] },
      { name: '踏板 Pedal', targets: [{ id: 'phys.damp', amount: -0.65 }, { id: 'reverb.mix', amount: 0.05 }, { id: 'aenv.r', amount: 0.3 }] },
      { name: '機械 Mechanics', targets: [{ id: 'noise.level', amount: 0.6 }] },
      { name: '房間 Room', targets: [{ id: 'reverb.mix', amount: 0.3 }, { id: 'reverb.size', amount: 0.35 }, { id: 'reverb.decay', amount: 0.15 }] },
    ],
    demo: 'keys',
    demoMacros: [{ index: 1, to: 0.8, beat: 4, beats: 2 }, { index: 2, to: 0.6, beat: 8, beats: 4 }, { index: 3, to: 0.6, beat: 12, beats: 6 }],
  },
  {
    name: 'Platinum Ballad',
    category: 'keys',
    tags: ['electric piano', 'fm', '80s', 'bright'],
    description: '八〇年代抒情金曲裡的數位電鋼琴：清脆閃亮的音叉叮噹，配上寬闊合唱與乒乓回音。',
    params: {
      'osc1.on': false, 'fm.on': true, 'fm.level': 0.9, 'fm.filt': 0, 'fm.algo': 3, 'fm.feedback': 0.12,
      'fm.op1.level': 0.9, 'fm.op1.d': 4, 'fm.op1.s': 0, 'fm.op1.r': 0.5, 'fm.op1.kscale': -0.1,
      'fm.op2.level': 0.28, 'fm.op2.d': 1.2, 'fm.op2.s': 0.1, 'fm.op2.r': 0.5, 'fm.op2.vel': 0.7, 'fm.op2.kscale': -0.3,
      'fm.op3.detune': 7, 'fm.op3.level': 0.6, 'fm.op3.d': 2.5, 'fm.op3.s': 0, 'fm.op3.r': 0.4, 'fm.op3.vel': 0.5,
      'fm.op4.ratio': 14, 'fm.op4.level': 0.38, 'fm.op4.d': 0.45, 'fm.op4.s': 0.02, 'fm.op4.vel': 0.85, 'fm.op4.kscale': -0.6,
      'filter.on': false,
      'aenv.a': 0, 'aenv.d': 10, 'aenv.s': 1, 'aenv.r': 0.7, 'amp.vel': 0.55, 'amp.level': 0.5,
      'vib.wheel': 25,
      'chorus.on': true, 'chorus.rate': 0.8, 'chorus.depth': 0.45, 'chorus.mix': 0.4,
      'delay.on': true, 'delay.feedback': 0.3, 'delay.mix': 0.14, 'delay.tone': 0.4, 'delay.pingpong': 0.8,
      'reverb.on': true, 'reverb.size': 0.65, 'reverb.decay': 2.6, 'reverb.mix': 0.22, 'reverb.damp': 0.35,
      'eq.low': -1,
    },
    macros: [
      { name: '玻璃 Glass', targets: [{ id: 'fm.op4.level', amount: 0.2 }, { id: 'fm.op4.d', amount: 0.1 }] },
      { name: '合唱 Chorus', targets: [{ id: 'chorus.mix', amount: 0.4 }, { id: 'chorus.depth', amount: 0.3 }] },
      { name: '回音 Echo', targets: [{ id: 'delay.mix', amount: 0.3 }, { id: 'delay.feedback', amount: 0.2 }] },
      { name: '空間 Space', targets: [{ id: 'reverb.mix', amount: 0.3 }, { id: 'reverb.decay', amount: 0.2 }] },
    ],
    demo: 'keys',
    demoMacros: [{ index: 1, to: 0.8, beat: 2, beats: 4 }, { index: 2, to: 0.6, beat: 8, beats: 4 }, { index: 0, to: 0.7, beat: 12, beats: 4 }],
  },
  {
    name: 'Amber Reeds',
    category: 'keys',
    tags: ['electric piano', 'reed', 'vintage'],
    description: '琥珀色燈光下的簧片電鋼琴，輕觸時圓潤帶鼻音，重擊時音箱發出沙啞咆哮。',
    params: {
      'osc1.on': false, 'fm.on': true, 'fm.level': 0.9, 'fm.algo': 3,
      'fm.op1.d': 3.5, 'fm.op1.s': 0, 'fm.op1.r': 0.25, 'fm.op1.kscale': -0.1,
      'fm.op2.ratio': 2, 'fm.op2.level': 0.3, 'fm.op2.d': 0.9, 'fm.op2.s': 0.15, 'fm.op2.r': 0.25, 'fm.op2.vel': 0.9, 'fm.op2.kscale': -0.3,
      'fm.op3.d': 2.5, 'fm.op3.s': 0, 'fm.op3.r': 0.25, 'fm.op3.vel': 0.4,
      'fm.op4.level': 0.3, 'fm.op4.d': 0.6, 'fm.op4.s': 0.1, 'fm.op4.r': 0.25, 'fm.op4.vel': 0.8,
      'filter.type': 'ladder12', 'filter.cutoff': 3500, 'filter.drive': 0.25, 'filter.vel': 0.3,
      'aenv.a': 0, 'aenv.d': 10, 'aenv.s': 1, 'amp.vel': 0.65, 'amp.level': -1.5,
      'lfo1.rate': 5.5, 'lfo1.mode': 'mono',
      'mod1.src': 'lfo1', 'mod1.dst': 'amp.level', 'mod1.amt': 0.03,
      'mod2.src': 'velocity', 'mod2.dst': 'filter.drive', 'mod2.amt': 0.35,
      'mod3.src': 'wheel', 'mod3.dst': 'filter.drive', 'mod3.amt': 0.3,
      'mod4.src': 'wheel', 'mod4.dst': 'amp.level', 'mod4.amt': -0.04,
      'vib.wheel': 0,
      'drive.on': true, 'drive.type': 'tube', 'drive.amount': 0.1, 'drive.tone': 0.45,
      'eq.midfreq': 1200,
      'reverb.on': true, 'reverb.size': 0.4, 'reverb.decay': 1.2, 'reverb.mix': 0.15,
    },
    macros: [
      { name: '咆哮 Bark', targets: [{ id: 'fm.op2.level', amount: 0.2 }, { id: 'filter.drive', amount: 0.45 }, { id: 'drive.amount', amount: 0.15 }, { id: 'amp.level', amount: -0.07 }] },
      { name: '顫音 Tremolo', targets: [{ id: 'mod1.amt', amount: 0.045 }, { id: 'lfo1.rate', amount: 0.02 }, { id: 'amp.level', amount: -0.04 }] },
      { name: '鼻音 Nasal', targets: [{ id: 'fm.op2.level', amount: 0.15 }, { id: 'eq.mid', amount: 0.25 }, { id: 'amp.level', amount: -0.045 }] },
      { name: '空間 Space', targets: [{ id: 'reverb.mix', amount: 0.3 }, { id: 'reverb.decay', amount: 0.2 }] },
    ],
    demo: 'keys',
    demoMacros: [{ index: 1, to: 0.8, beat: 4, beats: 4 }, { index: 0, to: 0.9, beat: 10, beats: 4 }, { index: 3, to: 0.5, beat: 16, beats: 4 }],
  },
  {
    name: 'Gospel Rotary',
    category: 'keys',
    tags: ['organ', 'drawbar', 'rotary'],
    description: '週日教堂裡的拉桿風琴：轉動的號角喇叭把和弦甩向四方，拉滿音栓就是整座詩班的吶喊。',
    params: {
      'osc1.mode': 'wavetable', 'osc1.table': 'organ', 'osc1.shape': 0.667, 'osc1.level': 0.7, 'osc1.drift': 0.05,
      'fm.on': true, 'fm.level': 0.35, 'fm.filt': 0,
      'fm.op1.ratio': 3, 'fm.op1.d': 0.5, 'fm.op1.s': 0, 'fm.op1.r': 0.05, 'fm.op1.vel': 0,
      'fm.op2.level': 0, 'fm.op3.level': 0, 'fm.op4.level': 0,
      'noise.on': true, 'noise.level': 0.05, 'noise.color': 0.3, 'noise.decay': 0.012,
      'filter.type': 'lp', 'filter.cutoff': 7000, 'filter.key': 0, 'filter2.type': 'hp', 'filter2.cutoff': 55,
      'aenv.a': 0.002, 'aenv.d': 1, 'aenv.s': 1, 'aenv.r': 0.06, 'amp.vel': 0, 'amp.level': -4.5,
      'lfo1.rate': 0.8, 'lfo1.mode': 'mono', 'lfo2.rate': 0.65, 'lfo2.mode': 'mono',
      'mod1.src': 'lfo1', 'mod1.dst': 'amp.pan', 'mod1.amt': 0.22,
      'mod2.src': 'lfo1', 'mod2.dst': 'voice.pitch', 'mod2.amt': 0.0015,
      'mod3.src': 'lfo2', 'mod3.dst': 'amp.level', 'mod3.amt': 0.025,
      'mod4.src': 'wheel', 'mod4.dst': 'osc1.shape', 'mod4.amt': 0.3,
      'vib.wheel': 0,
      'chorus.on': true, 'chorus.rate': 6.5, 'chorus.depth': 0.15, 'chorus.mix': 0.3,
      'drive.on': true, 'drive.type': 'tube', 'drive.amount': 0.08,
      'reverb.on': true, 'reverb.decay': 2.2, 'reverb.mix': 0.18,
    },
    macros: [
      { name: '音栓 Drawbars', targets: [{ id: 'osc1.shape', amount: 0.33 }] },
      { name: '轉速 Rotor', targets: [{ id: 'lfo1.rate', amount: 0.256 }, { id: 'lfo2.rate', amount: 0.264 }] },
      { name: '打擊音 Percussion', targets: [{ id: 'fm.level', amount: 0.65 }] },
      { name: '過載 Overdrive', targets: [{ id: 'drive.amount', amount: 0.55 }] },
    ],
    demo: 'keys',
    demoMacros: [{ index: 2, to: 0.7, beat: 2, beats: 2 }, { index: 1, to: 1, beat: 7.5, beats: 2 }, { index: 0, to: 0.7, beat: 11, beats: 2 }, { index: 1, to: 0, beat: 16, beats: 3 }],
  },
  {
    name: 'Strut Clav',
    category: 'keys',
    tags: ['clavinet', 'funk', 'physical'],
    description: '放克樂手最愛的撥弦鍵盤：短促帶勁的琴弦撥響，配上會說話的哇哇濾波與迷幻相位。',
    params: {
      'osc1.on': false,
      'phys.on': true, 'phys.level': 1, 'phys.hardness': 0.85, 'phys.position': 0.12, 'phys.decay': 2.8, 'phys.brightness': 0.8,
      'phys.inharm': 0.12, 'phys.body': 0, 'phys.spread': 0.1, 'phys.damp': 0.95, 'phys.filt': 1,
      'filter.cutoff': 2400, 'filter.res': 0.25, 'filter.env': 0.25, 'filter.vel': 0.3,
      'filter2.type': 'hp', 'filter2.cutoff': 75,
      'fenv.a': 0.001, 'fenv.d': 0.3, 'fenv.s': 0.1, 'fenv.r': 0.1,
      'lfo1.mode': 'mono', 'lfo1.sync': '1/4',
      'aenv.a': 0, 'aenv.d': 10, 'aenv.s': 1, 'aenv.r': 0.08, 'amp.vel': 0.7, 'amp.level': 6,
      'mod1.src': 'wheel', 'mod1.dst': 'filter.cutoff', 'mod1.amt': -0.2,
      'mod2.src': 'lfo1', 'mod2.dst': 'filter.cutoff',
      'mod3.src': 'note', 'mod3.dst': 'filter2.cutoff', 'mod3.amt': 0.25,
      'mod4.src': 'wheel', 'mod4.dst': 'filter.res', 'mod4.amt': 0.35,
      'vib.wheel': 0,
      'drive.on': true, 'drive.amount': 0.2,
      'phaser.on': true, 'phaser.rate': 0.4, 'phaser.depth': 0.6, 'phaser.feedback': 0.5, 'phaser.mix': 0.3,
      'reverb.on': true, 'reverb.size': 0.3, 'reverb.decay': 0.9, 'reverb.mix': 0.1,
      'comp.amount': 0.4,
    },
    macros: [
      { name: '哇音 Wah', targets: [{ id: 'mod2.amt', amount: 0.14 }, { id: 'filter.res', amount: 0.45 }, { id: 'filter.env', amount: -0.1 }, { id: 'filter.cutoff', amount: -0.1 }] },
      { name: '拾音 Pickup', targets: [{ id: 'phys.position', amount: 0.2 }] },
      { name: '止音 Mute', targets: [{ id: 'phys.decay', amount: -0.15 }] },
      { name: '相位 Phaser', targets: [{ id: 'phaser.mix', amount: 0.4 }, { id: 'phaser.feedback', amount: 0.2 }] },
    ],
    demo: 'pluck',
    demoMacros: [{ index: 0, to: 0.9, beat: 2, beats: 4 }, { index: 3, to: 0.8, beat: 8, beats: 4 }, { index: 1, to: 0.6, beat: 12, beats: 4 }],
  },
  {
    name: 'Versailles Harpsichord',
    category: 'keys',
    tags: ['harpsichord', 'baroque', 'physical'],
    description: '凡爾賽宮鏡廳裡的大鍵琴，羽管撥弦清脆閃亮，兩組琴弦微微錯開，迴盪著巴洛克的華麗。',
    params: {
      'osc1.on': false,
      'phys.on': true, 'phys.hardness': 0.95, 'phys.position': 0.1, 'phys.decay': 5, 'phys.brightness': 0.8,
      'phys.inharm': 0.06, 'phys.body': 0.5, 'phys.spread': 0.45, 'phys.damp': 0.85, 'phys.filt': 1,
      'fm.on': true, 'fm.level': 0.15, 'fm.filt': 0, 'fm.algo': 3,
      'fm.op1.ratio': 2, 'fm.op1.d': 3.5, 'fm.op1.s': 0, 'fm.op1.vel': 0,
      'fm.op2.ratio': 2, 'fm.op2.level': 0.35, 'fm.op2.d': 1.5, 'fm.op2.s': 0, 'fm.op2.vel': 0,
      'fm.op3.level': 0, 'fm.op4.level': 0,
      'filter.type': 'lp', 'filter.cutoff': 14000, 'filter.key': 0, 'filter2.type': 'hp', 'filter2.cutoff': 70,
      'aenv.a': 0, 'aenv.d': 10, 'aenv.s': 1, 'aenv.r': 0.5, 'amp.vel': 0.15, 'amp.level': 3.5,
      'mod1.src': 'note', 'mod1.dst': 'phys.decay', 'mod1.amt': -0.1,
      'mod2.src': 'note', 'mod2.dst': 'filter2.cutoff', 'mod2.amt': 0.25,
      'mod3.src': 'wheel', 'mod3.dst': 'phys.brightness', 'mod3.amt': -0.3,
      'vib.wheel': 0,
      'reverb.on': true, 'reverb.decay': 2.2, 'reverb.mix': 0.2, 'reverb.damp': 0.4,
      'eq.mid': -1.5, 'eq.midfreq': 600, 'eq.high': 1,
      // peak soft clip (amount 0 = unity-gain tanh, clean at playing level): chords' summed strikes no longer
      // push the output limiter (5-note chord at velocity 0.9)
      'drive.on': true, 'drive.amount': 0, 'drive.mix': 0.6,
    },
    macros: [
      { name: '琉特 Lute', targets: [{ id: 'phys.hardness', amount: -0.4 }, { id: 'phys.brightness', amount: -0.35 }, { id: 'phys.position', amount: 0.1 }, { id: 'amp.level', amount: -0.03 }] },
      { name: '八度 Octave', targets: [{ id: 'fm.level', amount: 0.45 }] },
      { name: '共鳴 Body', targets: [{ id: 'phys.body', amount: 0.4 }, { id: 'phys.decay', amount: 0.1 }] },
      { name: '殿堂 Hall', targets: [{ id: 'reverb.mix', amount: 0.3 }, { id: 'reverb.decay', amount: 0.2 }] },
    ],
    demo: 'pluck',
    demoMacros: [{ index: 1, to: 1, beat: 4, beats: 1 }, { index: 0, to: 0.8, beat: 8, beats: 2 }, { index: 3, to: 0.6, beat: 12, beats: 4 }],
  },
  {
    name: 'Sunset Poly',
    category: 'keys',
    tags: ['synth', 'analog', 'poly', '80s'],
    description: '夕陽灑落海岸公路，溫暖的類比複音合成器和弦透過經典立體合唱緩緩展開，是八〇年代合成器流行的招牌聲響。',
    params: {
      'osc1.unison': 2, 'osc1.detune': 0.12, 'osc1.drift': 0.2, 'osc1.level': 0.7,
      'osc2.on': true, 'osc2.shape': 1, 'osc2.level': 0.35, 'osc2.drift': 0.2, 'osc2.fine': 4,
      'filter.cutoff': 1000, 'filter.res': 0.25, 'filter.key': 0.5, 'filter.env': 0.35, 'filter.vel': 0.3,
      'fenv.a': 0.002, 'fenv.d': 0.8, 'fenv.s': 0.25,
      'aenv.a': 0.003, 'aenv.d': 1.5, 'aenv.s': 0.55, 'aenv.r': 0.45, 'amp.vel': 0.4, 'amp.level': -2,
      'lfo2.shape': 'tri', 'lfo2.rate': 0.6,
      'mod1.src': 'lfo2', 'mod1.dst': 'osc2.pw', 'mod1.amt': 0.3,
      'mod2.src': 'wheel', 'mod2.dst': 'filter.cutoff', 'mod2.amt': 0.2,
      'vib.wheel': 0,
      'chorus.on': true, 'chorus.rate': 0.5, 'chorus.mix': 0.45,
      'delay.on': true, 'delay.feedback': 0.3, 'delay.mix': 0.1, 'delay.tone': 0.35, 'delay.pingpong': 0.8,
      'reverb.on': true, 'reverb.size': 0.55, 'reverb.decay': 2, 'reverb.mix': 0.18,
    },
    macros: [
      { name: '亮度 Bright', targets: [{ id: 'filter.cutoff', amount: 0.16 }] },
      { name: '衝擊 Punch', targets: [{ id: 'filter.env', amount: 0.15 }, { id: 'fenv.d', amount: -0.15 }, { id: 'aenv.s', amount: -0.3 }, { id: 'amp.level', amount: 0.04 }] },
      { name: '合唱 Chorus', targets: [{ id: 'chorus.mix', amount: 0.2 }, { id: 'chorus.depth', amount: 0.2 }, { id: 'osc1.detune', amount: 0.15 }] },
      { name: '空間 Space', targets: [{ id: 'reverb.mix', amount: 0.3 }, { id: 'reverb.decay', amount: 0.2 }, { id: 'delay.mix', amount: 0.2 }] },
    ],
    demo: 'keys',
    demoMacros: [{ index: 0, to: 0.6, beat: 2, beats: 6 }, { index: 1, to: 0.8, beat: 8, beats: 4 }, { index: 3, to: 0.6, beat: 14, beats: 6 }],
  },
  {
    name: 'Faded Summer',
    category: 'keys',
    tags: ['lo-fi', 'tape', 'nostalgic'],
    description: '從抽屜深處翻出的舊錄音帶：走音晃動的電鋼琴、細碎的底噪與失真，一按下去就回到那年夏天。',
    params: {
      // phase reset: osc1 and FM op1 share the pitch; with a free-running osc1 their relative phase was random
      // on every key press, so the same note came out up to 10 LU quieter (partial cancellation)
      'osc1.mode': 'wavetable', 'osc1.table': 'digital', 'osc1.shape': 0.05, 'osc1.level': 0.35, 'osc1.phase': 'reset',
      'fm.on': true, 'fm.algo': 3,
      'fm.op1.level': 0.95, 'fm.op1.d': 4, 'fm.op1.s': 0, 'fm.op1.r': 0.4, 'fm.op1.vel': 0.35,
      'fm.op2.level': 0.3, 'fm.op2.d': 1.2, 'fm.op2.s': 0.1, 'fm.op2.r': 0.4, 'fm.op2.vel': 0.8,
      'fm.op3.detune': 4, 'fm.op3.d': 2, 'fm.op3.s': 0, 'fm.op3.r': 0.4,
      'fm.op4.ratio': 7, 'fm.op4.level': 0.18, 'fm.op4.d': 0.25, 'fm.op4.s': 0, 'fm.op4.vel': 0.7,
      'filter.type': 'ladder12', 'filter.cutoff': 2600, 'filter.key': 0.2,
      'filter2.type': 'hp', 'filter2.cutoff': 180,
      'noise.on': true, 'noise.level': 0.02, 'noise.color': 0.2,
      'aenv.a': 0, 'aenv.d': 3, 'aenv.s': 0.25, 'aenv.r': 0.4,
      'lfo1.shape': 'smooth', 'lfo1.rate': 0.7, 'lfo1.mode': 'mono',
      'mod1.src': 'lfo1', 'mod1.dst': 'voice.pitch', 'mod1.amt': 0.0015,
      'mod2.src': 'lfo1', 'mod2.dst': 'amp.pan',
      'mod3.src': 'lfo1', 'mod3.dst': 'filter.cutoff',
      'vib.depth': 3, 'vib.rate': 7, 'vib.delay': 0, 'vib.wheel': 12,
      'drive.on': true, 'drive.type': 'crush', 'drive.amount': 0.2, 'drive.tone': 0.2, 'drive.mix': 0.45,
      'delay.on': true, 'delay.sync': '1/4', 'delay.wobble': 0.7, 'delay.tone': 0.3, 'delay.mix': 0.15,
      'reverb.on': true, 'reverb.size': 0.4, 'reverb.decay': 1.5, 'reverb.mix': 0.15,
      'eq.high': -8, 'amp.level': -0.5,
    },
    macros: [
      { name: '抖動 Wow', targets: [{ id: 'mod1.amt', amount: 0.0012 }, { id: 'lfo1.rate', amount: 0.06 }, { id: 'delay.wobble', amount: 0.3 }, { id: 'mod2.amt', amount: 0.12 }, { id: 'mod3.amt', amount: 0.02 }] },
      { name: '歲月 Age', targets: [{ id: 'filter.cutoff', amount: -0.15 }, { id: 'noise.level', amount: 0.1 }, { id: 'mod1.amt', amount: 0.0005 }, { id: 'eq.high', amount: -0.15 }, { id: 'drive.tone', amount: -0.2 }] },
      { name: '回音 Echo', targets: [{ id: 'delay.mix', amount: 0.3 }, { id: 'delay.feedback', amount: 0.2 }] },
      { name: '空間 Space', targets: [{ id: 'reverb.mix', amount: 0.3 }, { id: 'reverb.decay', amount: 0.2 }] },
    ],
    demo: 'keys',
    demoMacros: [{ index: 0, to: 1, beat: 4, beats: 6 }, { index: 1, to: 0.8, beat: 10, beats: 6 }, { index: 2, to: 0.6, beat: 14, beats: 4 }],
  },

];
