// Lead 主奏 — factory presets (AURORA 極光). See docs/ARCHITECTURE.md §9.
export default [
  // 1 ── Flagship: hard-sync lead (mod-env sync sweep per note) ───────
  {
    name: 'Polaris Sync',
    category: 'lead',
    tags: ['sync', 'bright', 'expressive'],
    description: '硬同步鋸齒波隨每個音符呼嘯掃過，乒乓回聲把旋律拋向北極星',
    params: {
      'voice.mode': 'mono', 'voice.glide': 0.06,
      'vib.depth': 10, 'vib.delay': 0.45, 'vib.wheel': 40,
      'amp.vel': 0.35,
      'osc1.level': 0.7, 'osc1.sync': 0.18, 'osc1.unison': 3, 'osc1.detune': 0.12, 'osc1.spread': 0.9, 'osc1.phase': 'reset',
      'osc2.on': true, 'osc2.level': 0.38, 'osc2.oct': -1, 'osc2.shape': 0.85, 'osc2.fine': 6,
      'filter.cutoff': 3200, 'filter.res': 0.22, 'filter.drive': 0.25,
      'filter.env': 0.22, 'filter.vel': 0.12,
      'filter2.type': 'hp', 'filter2.cutoff': 70,
      'fenv.a': 0.002, 'fenv.d': 0.55, 'fenv.s': 0.35, 'fenv.r': 0.3,
      'aenv.a': 0.003, 'aenv.d': 0.6, 'aenv.s': 0.85, 'aenv.r': 0.28,
      'menv.a': 0.001, 'menv.d': 0.7, 'menv.s': 0.15, 'menv.r': 0.4,
      'lfo2.shape': 'tri', 'lfo2.rate': 0.35,
      'mod1.src': 'menv', 'mod1.dst': 'osc1.sync', 'mod1.amt': 0.38,
      'mod2.src': 'lfo2', 'mod2.dst': 'osc1.sync', 'mod2.amt': 0.05,
      'mod3.src': 'velocity', 'mod3.dst': 'osc1.sync', 'mod3.amt': 0.12,
      'mod4.src': 'aftertouch', 'mod4.dst': 'filter.cutoff', 'mod4.amt': 0.15,
      'drive.on': true, 'drive.type': 'tube', 'drive.amount': 0.2, 'drive.tone': 0.45,
      'delay.on': true, 'delay.feedback': 0.34, 'delay.pingpong': 0.8, 'delay.tone': 0.42, 'delay.wobble': 0.15, 'delay.mix': 0.2,
      'reverb.on': true, 'reverb.size': 0.7, 'reverb.decay': 2.8, 'reverb.damp': 0.55, 'reverb.mix': 0.18,
      'eq.high': -3, 'comp.amount': 0.2,
    },
    macros: [
      { name: '同步 Sync', targets: [{ id: 'osc1.sync', amount: 0.4 }, { id: 'filter.cutoff', amount: 0.06 }] },
      { name: '亮度 Bright', targets: [{ id: 'filter.cutoff', amount: 0.22 }, { id: 'filter.res', amount: 0.15 }] },
      { name: '咆哮 Grit', targets: [{ id: 'drive.amount', amount: 0.6 }, { id: 'filter.drive', amount: 0.45 }, { id: 'filter.res', amount: 0.12 }] },
      { name: '空間 Space', targets: [{ id: 'delay.mix', amount: 0.25 }, { id: 'delay.feedback', amount: 0.2 }, { id: 'reverb.mix', amount: 0.2 }] },
    ],
    demo: 'lead',
    demoMacros: [
      { index: 3, to: 0, beat: 0, beats: 1 },
      { index: 0, to: 0.75, beat: 4, beats: 6 },
      { index: 0, to: 0.15, beat: 12, beats: 4 },
      { index: 3, to: 0.7, beat: 13, beats: 3 },
    ],
  },

  // 2 ── Trance supersaw ───────────────────────────────────────────
  {
    name: 'Stellar Supersaw',
    category: 'lead',
    tags: ['supersaw', 'trance', 'wide'],
    description: '七聲齊奏的超級鋸齒波鋪滿聲場，附點回聲讓旋律像星河般閃耀',
    params: {
      'voice.poly': 8, 'voice.glide': 0.02,
      'vib.delay': 0.5, 'vib.wheel': 25,
      'amp.vel': 0.3, 'amp.level': -1.5,
      'osc1.unison': 7, 'osc1.detune': 0.34, 'osc1.spread': 0.9, 'osc1.level': 0.72,
      'osc2.on': true, 'osc2.unison': 5, 'osc2.detune': 0.26, 'osc2.spread': 1, 'osc2.oct': 1, 'osc2.level': 0.26,
      'filter.type': 'lp', 'filter.cutoff': 3800, 'filter.res': 0.12, 'filter.key': 0.35, 'filter.env': 0.18, 'filter.vel': 0.15,
      'fenv.a': 0.002, 'fenv.d': 0.7, 'fenv.s': 0.4,
      'aenv.a': 0.004, 'aenv.d': 0.4, 'aenv.s': 0.88, 'aenv.r': 0.35,
      'lfo1.shape': 'square', 'lfo1.sync': '1/16', 'lfo1.mode': 'mono',
      'mod1.src': 'lfo1', 'mod1.dst': 'filter.cutoff',
      'mod2.src': 'aftertouch', 'mod2.dst': 'filter.cutoff', 'mod2.amt': 0.12,
      'delay.on': true, 'delay.feedback': 0.4, 'delay.pingpong': 0.85, 'delay.tone': 0.45, 'delay.mix': 0.22,
      'reverb.on': true, 'reverb.size': 0.8, 'reverb.decay': 3.4, 'reverb.mix': 0.24,
      'eq.low': -3, 'eq.high': -1.5, 'comp.amount': 0.35,
    },
    macros: [
      { name: '亮度 Bright', targets: [{ id: 'filter.cutoff', amount: 0.22 }, { id: 'filter.env', amount: 0.1 }] },
      { name: '齊奏 Detune', targets: [{ id: 'osc1.detune', amount: 0.35 }, { id: 'osc2.detune', amount: 0.3 }, { id: 'osc2.level', amount: 0.15 }] },
      { name: '閘門 Gate', targets: [{ id: 'mod1.amt', amount: -0.2 }] },
      { name: '空間 Space', targets: [{ id: 'delay.mix', amount: 0.25 }, { id: 'reverb.mix', amount: 0.25 }, { id: 'reverb.decay', amount: 0.15 }] },
    ],
    demo: 'lead',
    demoMacros: [
      { index: 2, to: 1, beat: 8, beats: 4 },
      { index: 2, to: 0, beat: 14, beats: 2 },
    ],
  },

  // 3 ── Classic mono solo ─────────────────────────────────────────
  {
    name: 'Monolith Solo',
    category: 'lead',
    tags: ['analog', 'mono', 'glide'],
    description: '經典單音類比獨奏：飽和的階梯濾波器、一氣呵成的滑音與轉輪顫音',
    params: {
      'voice.mode': 'legato', 'voice.glide': 0.09,
      'vib.wheel': 45, 'vib.rate': 5.2,
      'amp.vel': 0.3,
      'osc1.level': 0.7, 'osc1.drift': 0.25,
      'osc2.on': true, 'osc2.level': 0.55, 'osc2.fine': 9, 'osc2.drift': 0.25,
      'filter.cutoff': 1300, 'filter.res': 0.38, 'filter.drive': 0.35, 'filter.key': 0.6,
      'filter.env': 0.42, 'filter.vel': 0.15,
      'filter2.type': 'hp', 'filter2.cutoff': 50,
      'fenv.a': 0.004, 'fenv.d': 0.7, 'fenv.r': 0.3,
      'aenv.a': 0.003, 'aenv.d': 0.5, 'aenv.s': 0.92, 'aenv.r': 0.22,
      'mod1.src': 'aftertouch', 'mod1.dst': 'filter.cutoff', 'mod1.amt': 0.18,
      'drive.on': true, 'drive.type': 'tube', 'drive.amount': 0.25,
      'delay.on': true, 'delay.sync': '1/4', 'delay.feedback': 0.25, 'delay.mix': 0.1, 'delay.tone': 0.35,
      'reverb.on': true, 'reverb.size': 0.4, 'reverb.decay': 1.5, 'reverb.mix': 0.13,
    },
    macros: [
      { name: '截止 Cutoff', targets: [{ id: 'filter.cutoff', amount: 0.28 }] },
      { name: '共振 Emphasis', targets: [{ id: 'filter.res', amount: 0.45 }, { id: 'filter.cutoff', amount: -0.05 }] },
      { name: '包絡 Contour', targets: [{ id: 'filter.env', amount: 0.25 }, { id: 'fenv.d', amount: 0.15 }, { id: 'fenv.s', amount: -0.2 }] },
      { name: '滑音 Glide', targets: [{ id: 'voice.glide', amount: 0.3 }] },
    ],
    demo: 'lead',
    demoMacros: [
      { index: 0, to: 0.6, beat: 0, beats: 8 },
      { index: 0, to: 0.15, beat: 12, beats: 4 },
    ],
  },

  // 4 ── Chiptune ─────────────────────────────────────────────────
  {
    name: 'Cartridge Hero',
    category: 'lead',
    tags: ['chiptune', '8-bit', 'retro'],
    description: '插上卡匣主角登場：八位元脈衝波、延遲顫音與一點位元壓縮',
    params: {
      'voice.mode': 'mono',
      'vib.depth': 22, 'vib.rate': 7, 'vib.delay': 0.28, 'vib.wheel': 50,
      'amp.vel': 0.2, 'amp.level': -1,
      'osc1.shape': 1, 'osc1.pw': 0.25, 'osc1.level': 0.62, 'osc1.drift': 0, 'osc1.phase': 'reset',
      'osc2.on': true, 'osc2.shape': 1, 'osc2.pw': 0.125, 'osc2.oct': 1, 'osc2.level': 0.12, 'osc2.drift': 0, 'osc2.fine': 4,
      'filter.type': 'lp', 'filter.cutoff': 9000, 'filter.res': 0, 'filter.key': 0,
      'aenv.a': 0.001, 'aenv.d': 0.25, 'aenv.s': 0.75, 'aenv.r': 0.08, 'aenv.curve': 0.2,
      'menv.a': 0, 'menv.d': 0.045, 'menv.r': 0.05,
      'mod1.src': 'menv', 'mod1.dst': 'voice.pitch', 'mod1.amt': 0.06,
      'lfo1.shape': 'tri', 'lfo1.rate': 0.4,
      'mod2.src': 'lfo1', 'mod2.dst': 'osc1.pw', 'mod2.amt': 0.06,
      'mod3.src': 'aftertouch', 'mod3.dst': 'vib.depth', 'mod3.amt': 0.3,
      'drive.on': true, 'drive.type': 'crush', 'drive.amount': 0.06, 'drive.tone': 0.3,
      'delay.on': true, 'delay.sync': '1/8', 'delay.feedback': 0.3, 'delay.pingpong': 0.6, 'delay.mix': 0.14, 'delay.tone': 0.4,
      'reverb.on': true, 'reverb.size': 0.3, 'reverb.decay': 1, 'reverb.mix': 0.08,
      'eq.high': -2,
    },
    macros: [
      { name: '脈寬 Pulse', targets: [{ id: 'osc1.pw', amount: -0.17 }, { id: 'amp.level', amount: 0.06 }] },
      { name: '位元 Crush', targets: [{ id: 'drive.amount', amount: 0.4 }] },
      { name: '跳音 Blip', targets: [{ id: 'mod1.amt', amount: 0.1 }, { id: 'menv.d', amount: 0.15 }] },
      { name: '回聲 Echo', targets: [{ id: 'delay.mix', amount: 0.25 }, { id: 'delay.feedback', amount: 0.2 }] },
    ],
    demo: 'lead',
    demoMacros: [
      { index: 0, to: 1, beat: 4, beats: 4 },
      { index: 0, to: 0, beat: 12, beats: 4 },
    ],
  },

  // 5 ── Sine whistle ─────────────────────────────────────────────
  {
    name: 'Meadow Whistle',
    category: 'lead',
    tags: ['sine', 'soft', 'airy'],
    description: '晚風吹過草原的口哨：純淨正弦帶著氣息與滑音，顫音在長音裡綻開',
    params: {
      'voice.mode': 'legato', 'voice.glide': 0.13,
      'vib.depth': 16, 'vib.rate': 5.2, 'vib.delay': 0.35, 'vib.wheel': 40,
      'amp.vel': 0.45, 'amp.level': -3,
      'osc1.shape': 0, 'osc1.drift': 0.3, 'osc1.filt': 0,
      'osc2.on': true, 'osc2.shape': 0.333, 'osc2.oct': 1, 'osc2.level': 0.08, 'osc2.filt': 0,
      'noise.on': true, 'noise.level': 0.22, 'noise.color': 0.2,
      'filter.type': 'bp', 'filter.cutoff': 560, 'filter.res': 0.55, 'filter.key': 1,
      'aenv.a': 0.05, 'aenv.d': 0.4, 'aenv.s': 1, 'aenv.curve': 0.6,
      'lfo1.shape': 'smooth', 'lfo1.rate': 3.5,
      'mod1.src': 'lfo1', 'mod1.dst': 'noise.level', 'mod1.amt': 0.06,
      'mod2.src': 'aftertouch', 'mod2.dst': 'noise.level', 'mod2.amt': 0.15,
      'mod4.src': 'velocity', 'mod4.dst': 'noise.level', 'mod4.amt': 0.1,
      'menv.a': 0, 'menv.d': 0.15, 'menv.r': 0.1,
      'mod3.src': 'menv', 'mod3.dst': 'voice.pitch', 'mod3.amt': -0.008,
      'delay.on': true, 'delay.sync': '1/4', 'delay.feedback': 0.3, 'delay.wobble': 0.3, 'delay.tone': 0.35, 'delay.mix': 0.12,
      'reverb.on': true, 'reverb.size': 0.78, 'reverb.decay': 3.8, 'reverb.predelay': 0.03,
    },
    macros: [
      { name: '氣息 Breath', targets: [{ id: 'noise.level', amount: 0.3 }] },
      { name: '顫音 Vibrato', targets: [{ id: 'vib.depth', amount: 0.25 }, { id: 'vib.delay', amount: -0.2 }, { id: 'vib.rate', amount: 0.06 }, { id: 'noise.level', amount: 0.08 }] },
      { name: '泛音 Overtone', targets: [{ id: 'osc2.level', amount: 0.5 }, { id: 'osc1.shape', amount: 0.25 }] },
      { name: '空間 Space', targets: [{ id: 'reverb.mix', amount: 0.3 }, { id: 'delay.mix', amount: 0.2 }] },
    ],
    demo: 'lead',
    demoMacros: [
      { index: 1, to: 0.8, beat: 4, beats: 6 },
      { index: 1, to: 0.2, beat: 12, beats: 4 },
    ],
  },

  // 6 ── Vowel / formant lead ─────────────────────────────────────
  {
    name: 'Vowel Siren',
    category: 'lead',
    tags: ['vocal', 'formant', 'talking'],
    description: '會說話的合成人聲，在 A、E、I、O、U 母音之間吟唱變形',
    params: {
      'voice.mode': 'legato', 'voice.glide': 0.07,
      'vib.depth': 14, 'vib.delay': 0.4, 'vib.rate': 5.4,
      'amp.vel': 0.35, 'amp.level': -3.5,
      'osc1.unison': 5, 'osc1.detune': 0.22, 'osc1.level': 0.75,
      'osc2.on': true, 'osc2.shape': 1, 'osc2.oct': -1, 'osc2.level': 0.3,
      'noise.on': true, 'noise.level': 0.03, 'noise.color': 0.2, 'noise.filt': 0.85,
      'filter.type': 'formant', 'filter.cutoff': 1300, 'filter.key': 0.2, 'filter.vel': 0.08,
      'aenv.a': 0.01, 'aenv.d': 0.5, 'aenv.s': 0.9,
      'lfo1.shape': 'tri', 'lfo1.rate': 0.3,
      'mod1.src': 'lfo1', 'mod1.dst': 'filter.vowel', 'mod1.amt': 0.1,
      'mod2.src': 'wheel', 'mod2.dst': 'filter.vowel', 'mod2.amt': 0.5,
      'mod3.src': 'aftertouch', 'mod3.dst': 'filter.cutoff', 'mod3.amt': 0.1,
      'chorus.on': true, 'chorus.depth': 0.35, 'chorus.mix': 0.25,
      'delay.on': true, 'delay.feedback': 0.3, 'delay.mix': 0.15, 'delay.tone': 0.4,
      'reverb.on': true, 'reverb.size': 0.65, 'reverb.decay': 2.6, 'reverb.mix': 0.2,
      'eq.mid': 2.5, 'eq.midfreq': 2600, 'comp.amount': 0.6,
    },
    macros: [
      { name: '母音 Vowel', targets: [{ id: 'filter.vowel', amount: 0.9 }, { id: 'amp.level', amount: 0.04 }] },
      { name: '嗓音 Voice', targets: [{ id: 'filter.cutoff', amount: 0.2 }] },
      { name: '說話 Talk', targets: [{ id: 'mod1.amt', amount: 0.3 }, { id: 'lfo1.rate', amount: 0.25 }] },
      { name: '空間 Space', targets: [{ id: 'reverb.mix', amount: 0.25 }, { id: 'delay.mix', amount: 0.2 }] },
    ],
    demo: 'lead',
    demoMacros: [
      { index: 0, to: 1, beat: 0, beats: 8 },
      { index: 0, to: 0.25, beat: 8, beats: 8 },
    ],
  },

  // 7 ── FM brass lead ────────────────────────────────────────────
  {
    name: 'Solar Brass',
    category: 'lead',
    tags: ['fm', 'brass', 'bright'],
    description: '明亮的 FM 銅管主奏：越用力吹越金光燦爛，觸後壓力讓音色咆哮起來',
    params: {
      'voice.mode': 'legato', 'voice.glide': 0.03,
      'vib.depth': 8, 'vib.delay': 0.5, 'vib.wheel': 35,
      'amp.vel': 0.35,
      'osc1.on': false,
      'fm.on': true, 'fm.algo': 2, 'fm.feedback': 0.6,
      'fm.op1.a': 0.02, 'fm.op1.d': 3, 'fm.op1.s': 0.85, 'fm.op1.r': 0.25,
      'fm.op2.a': 0.07, 'fm.op2.d': 1.2, 'fm.op2.s': 0.55, 'fm.op2.r': 0.25, 'fm.op2.vel': 0.7,
      'fm.op3.detune': 5, 'fm.op3.level': 0.3, 'fm.op3.a': 0.1, 'fm.op3.s': 0.7, 'fm.op3.r': 0.25, 'fm.op3.vel': 0.5,
      'fm.op4.detune': -5, 'fm.op4.level': 0.28, 'fm.op4.a': 0.06, 'fm.op4.s': 0.7, 'fm.op4.r': 0.25, 'fm.op4.vel': 0.5,
      'filter.type': 'lp', 'filter.cutoff': 14000, 'filter.res': 0, 'filter.key': 0,
      'filter2.type': 'hp', 'filter2.cutoff': 90,
      'aenv.a': 0.004, 'aenv.d': 1, 'aenv.s': 1, 'aenv.r': 0.25,
      'mod1.src': 'aftertouch', 'mod1.dst': 'fm.op2.level', 'mod1.amt': 0.2,
      'lfo1.rate': 22, 'lfo1.fade': 0.15,
      'mod2.src': 'lfo1', 'mod2.dst': 'fm.op2.level',
      'chorus.on': true, 'chorus.mode': 'ensemble', 'chorus.mix': 0.2,
      'delay.on': true, 'delay.sync': '1/4D', 'delay.feedback': 0.28, 'delay.mix': 0.12, 'delay.tone': 0.4,
      'reverb.on': true, 'reverb.size': 0.75, 'reverb.decay': 2.6, 'reverb.mix': 0.2,
    },
    macros: [
      { name: '銅亮 Brass', targets: [{ id: 'fm.op2.level', amount: 0.18 }, { id: 'fm.feedback', amount: 0.15 }] },
      { name: '咆哮 Growl', targets: [{ id: 'mod2.amt', amount: 0.12 }] },
      { name: '合奏 Ensemble', targets: [{ id: 'chorus.mix', amount: 0.35 }, { id: 'fm.op3.detune', amount: 0.1 }] },
      { name: '空間 Space', targets: [{ id: 'reverb.mix', amount: 0.25 }, { id: 'delay.mix', amount: 0.2 }] },
    ],
    demo: 'lead',
    demoMacros: [
      { index: 0, to: 0.8, beat: 6, beats: 6 },
      { index: 0, to: 0.2, beat: 13, beats: 3 },
    ],
  },

  // 8 ── Distorted screaming lead ─────────────────────────────────
  {
    name: 'Molten Scream',
    category: 'lead',
    tags: ['distorted', 'aggressive', 'rock'],
    description: '熔岩般灼熱的失真主奏：共振濾波器在高音區嘶吼，推起調變輪就尖嘯',
    params: {
      'voice.mode': 'legato', 'voice.glide': 0.05,
      'vib.depth': 12, 'vib.delay': 0.5, 'vib.rate': 5.8, 'vib.wheel': 50,
      'amp.vel': 0.2, 'amp.level': -1.2,
      'osc1.unison': 4, 'osc1.detune': 0.18, 'osc1.level': 0.7,
      'osc2.on': true, 'osc2.shape': 1, 'osc2.level': 0.35, 'osc2.fine': -8,
      'filter.cutoff': 2000, 'filter.res': 0.5, 'filter.drive': 0.55, 'filter.key': 0.4, 'filter.env': 0.25, 'filter.vel': 0.12,
      'filter2.type': 'hp', 'filter2.cutoff': 100,
      'fenv.a': 0.01, 'fenv.d': 0.6, 'fenv.s': 0.5, 'fenv.r': 0.3,
      'aenv.a': 0.003, 'aenv.d': 0.5, 'aenv.s': 0.95, 'aenv.r': 0.25,
      'mod1.src': 'aftertouch', 'mod1.dst': 'filter.cutoff', 'mod1.amt': 0.15,
      'mod2.src': 'wheel', 'mod2.dst': 'filter.res', 'mod2.amt': 0.3,
      'lfo1.rate': 1.5,
      'mod3.src': 'lfo1', 'mod3.dst': 'filter.cutoff',
      'drive.on': true, 'drive.type': 'tube', 'drive.amount': 0.55, 'drive.tone': 0.4,
      'delay.on': true, 'delay.feedback': 0.33, 'delay.mix': 0.16, 'delay.tone': 0.35,
      'reverb.on': true, 'reverb.decay': 2, 'reverb.mix': 0.14,
      'eq.low': -4, 'eq.high': -3, 'comp.amount': 0.3,
    },
    macros: [
      { name: '失真 Drive', targets: [{ id: 'drive.amount', amount: 0.35 }, { id: 'filter.drive', amount: 0.3 }] },
      { name: '尖嘯 Scream', targets: [{ id: 'filter.res', amount: 0.35 }, { id: 'filter.cutoff', amount: 0.08 }] },
      { name: '哇音 Wah', targets: [{ id: 'mod3.amt', amount: 0.14 }] },
      { name: '回聲 Echo', targets: [{ id: 'delay.mix', amount: 0.25 }, { id: 'delay.feedback', amount: 0.2 }] },
    ],
    demo: 'lead',
    demoMacros: [
      { index: 1, to: 0.8, beat: 8, beats: 4 },
      { index: 1, to: 0, beat: 14, beats: 2 },
    ],
  },

  // 9 ── Breath flute (physical model) ────────────────────────────
  {
    name: 'Bamboo Dizi',
    category: 'lead',
    tags: ['flute', 'breath', 'physical'],
    description: '物理模型吹奏的竹笛，笛膜輕顫、氣息飽滿，適合悠揚的東方旋律',
    params: {
      'voice.mode': 'legato', 'voice.glide': 0.04,
      'vib.depth': 18, 'vib.rate': 5.6, 'vib.wheel': 35,
      'amp.vel': 0.4,
      'osc1.on': false,
      'phys.on': true, 'phys.exciter': 'breath', 'phys.hardness': 0.4, 'phys.position': 0.5,
      'phys.decay': 1.4, 'phys.brightness': 0.5, 'phys.inharm': 0, 'phys.pressure': 0.55, 'phys.body': 0, 'phys.spread': 0.15, 'phys.damp': 0.8,
      'noise.on': true, 'noise.level': 0.1, 'noise.color': 0.4, 'noise.decay': 0.12, 'noise.filt': 0,
      'aenv.a': 0.02, 'aenv.d': 0.5, 'aenv.s': 1, 'aenv.r': 0.2,
      'lfo1.rate': 5.6, 'lfo1.fade': 0.4,
      'mod1.src': 'lfo1', 'mod1.dst': 'phys.pressure', 'mod1.amt': 0.04,
      'mod2.src': 'aftertouch', 'mod2.dst': 'phys.pressure', 'mod2.amt': 0.2,
      'mod3.src': 'velocity', 'mod3.dst': 'phys.brightness', 'mod3.amt': 0.2,
      'reverb.on': true, 'reverb.size': 0.72, 'reverb.mix': 0.26, 'reverb.predelay': 0.025,
      'delay.on': true, 'delay.sync': '1/4', 'delay.feedback': 0.22, 'delay.mix': 0.08, 'delay.tone': 0.35,
      'eq.low': -6,
    },
    macros: [
      { name: '氣壓 Breath', targets: [{ id: 'phys.pressure', amount: 0.3 }, { id: 'amp.level', amount: -0.025 }] },
      { name: '亮度 Bright', targets: [{ id: 'phys.hardness', amount: 0.25 }, { id: 'phys.brightness', amount: 0.3 }, { id: 'amp.level', amount: -0.04 }] },
      { name: '顫音 Vibrato', targets: [{ id: 'vib.depth', amount: 0.2 }, { id: 'mod1.amt', amount: 0.06 }] },
      { name: '空間 Space', targets: [{ id: 'reverb.mix', amount: 0.25 }, { id: 'delay.mix', amount: 0.2 }] },
    ],
    demo: 'lead',
    demoMacros: [
      { index: 2, to: 0, beat: 0, beats: 0.5 },
      { index: 2, to: 0.8, beat: 2, beats: 2 },
      { index: 2, to: 0, beat: 4, beats: 1 },
      { index: 2, to: 0.9, beat: 14, beats: 2 },
    ],
  },

  // 10 ── Cinematic delay-throw lead ──────────────────────────────
  {
    name: 'Horizon Throw',
    category: 'lead',
    tags: ['cinematic', 'wavetable', 'delay'],
    description: '電影感的波表主奏：音色緩緩變形，句尾的回聲一甩便在地平線上層層散開',
    params: {
      'voice.mode': 'legato', 'voice.glide': 0.08,
      'vib.depth': 9, 'vib.delay': 0.6,
      'amp.vel': 0.4, 'amp.level': 2,
      'osc1.mode': 'wavetable', 'osc1.table': 'strings', 'osc1.shape': 0.2, 'osc1.unison': 3, 'osc1.detune': 0.1, 'osc1.level': 0.75,
      'osc2.on': true, 'osc2.level': 0.3, 'osc2.oct': -1, 'osc2.shape': 0.5,
      'filter.type': 'ladder12', 'filter.cutoff': 2900, 'filter.res': 0.15, 'filter.key': 0.4, 'filter.vel': 0.15,
      'aenv.a': 0.03, 'aenv.d': 0.8, 'aenv.s': 0.9, 'aenv.r': 0.6, 'aenv.curve': 0.6,
      'lfo2.shape': 'tri', 'lfo2.rate': 0.15,
      'mod1.src': 'lfo2', 'mod1.dst': 'osc1.shape', 'mod1.amt': 0.12,
      'mod2.src': 'aftertouch', 'mod2.dst': 'filter.cutoff', 'mod2.amt': 0.15,
      'mod3.src': 'wheel', 'mod3.dst': 'osc1.shape', 'mod3.amt': 0.3,
      'chorus.on': true, 'chorus.mode': 'ensemble', 'chorus.mix': 0.25,
      'delay.on': true, 'delay.sync': '1/4D', 'delay.feedback': 0.42, 'delay.pingpong': 0.9, 'delay.tone': 0.4, 'delay.wobble': 0.25, 'delay.mix': 0.16,
      'reverb.on': true, 'reverb.size': 0.9, 'reverb.decay': 5, 'reverb.shimmer': 0.15, 'reverb.mix': 0.26,
    },
    macros: [
      { name: '變形 Morph', targets: [{ id: 'osc1.shape', amount: 0.55 }, { id: 'amp.level', amount: 0.05 }] },
      { name: '亮度 Bright', targets: [{ id: 'filter.cutoff', amount: 0.22 }] },
      { name: '回聲 Throw', targets: [{ id: 'delay.mix', amount: 0.35 }, { id: 'delay.feedback', amount: 0.2 }] },
      { name: '微光 Shimmer', targets: [{ id: 'reverb.shimmer', amount: 0.5 }, { id: 'reverb.mix', amount: 0.15 }] },
    ],
    demo: 'lead',
    demoMacros: [
      { index: 2, to: 0, beat: 0, beats: 0.5 },
      { index: 2, to: 1, beat: 2, beats: 1 },
      { index: 2, to: 0, beat: 4, beats: 1 },
      { index: 0, to: 0.7, beat: 6, beats: 6 },
      { index: 2, to: 1, beat: 14, beats: 1 },
      { index: 0, to: 0, beat: 14, beats: 2 },
    ],
  },
];
