// Pad 鋪底 — factory presets (docs/ARCHITECTURE.md §9).
// Calibrated offline (tools/render.mjs): demo phrase ≈ −19 LUFS, peaks ≤ −5 dBFS, no limiting, every macro
// audible and within ≈ ±3 LU over 0..1. 'Aurora Pad' stays first: it is the app's start-up sound (src/ui/main.js).
export default [
  // 1 ── flagship: the app's start-up sound
  {
    name: 'Aurora Pad',
    category: 'pad',
    tags: ['lush', 'wide', 'shimmer', 'hybrid'],
    description: '超鋸齒與流動的母音波表交織，觸鍵綻放一抹 FM 晶光，如極光在夜空舒展',
    params: {
      'voice.spread': 0.35,
      'vib.wheel': 8,
      'osc1.level': 0.62, 'osc1.unison': 7, 'osc1.detune': 0.3, 'osc1.spread': 0.9, 'osc1.drift': 0.3,
      'osc2.on': true, 'osc2.mode': 'wavetable', 'osc2.table': 'vowels', 'osc2.shape': 0.3, 'osc2.level': 0.38,
      'osc2.unison': 3, 'osc2.detune': 0.14, 'osc2.spread': 1, 'osc2.drift': 0.25,
      'fm.on': true, 'fm.level': 0.75, 'fm.filt': 0, 'fm.algo': 3, 'fm.oct': 1,
      'fm.op1.level': 0.9, 'fm.op1.a': 0.002, 'fm.op1.d': 3.2, 'fm.op1.s': 0, 'fm.op1.r': 2.5, 'fm.op1.vel': 0.6, 'fm.op1.kscale': -0.3,
      'fm.op2.ratio': 3.5, 'fm.op2.level': 0.3, 'fm.op2.a': 0.002, 'fm.op2.d': 1.6, 'fm.op2.s': 0, 'fm.op2.r': 1.5, 'fm.op2.vel': 0.7, 'fm.op2.kscale': -0.4,
      'fm.op3.ratio': 2, 'fm.op3.detune': 6, 'fm.op3.level': 0.6, 'fm.op3.a': 0.002, 'fm.op3.d': 2.4, 'fm.op3.s': 0, 'fm.op3.r': 2, 'fm.op3.vel': 0.6, 'fm.op3.kscale': -0.3,
      'fm.op4.ratio': 5, 'fm.op4.detune': -4, 'fm.op4.level': 0.22, 'fm.op4.a': 0.002, 'fm.op4.d': 1.2, 'fm.op4.s': 0, 'fm.op4.r': 1, 'fm.op4.vel': 0.7, 'fm.op4.kscale': -0.4,
      'filter.type': 'lp', 'filter.cutoff': 1150, 'filter.res': 0.12, 'filter.env': 0.18, 'filter.vel': 0.18,
      'fenv.a': 1.4, 'fenv.d': 3.5, 'fenv.s': 0.45, 'fenv.r': 3,
      'aenv.a': 0.32, 'aenv.d': 2, 'aenv.s': 0.88, 'aenv.r': 3.4, 'aenv.curve': 0.55,
      'amp.vel': 0.35, 'amp.level': -4.6,
      'lfo1.rate': 0.09, 'lfo1.mode': 'mono',
      'lfo2.shape': 'smooth', 'lfo2.rate': 0.3,
      'mod1.src': 'lfo1', 'mod1.dst': 'filter.cutoff', 'mod1.amt': 0.06,
      'mod2.src': 'lfo2', 'mod2.dst': 'osc2.shape', 'mod2.amt': 0.14,
      'mod3.src': 'lfo2', 'mod3.dst': 'osc2.pan', 'mod3.amt': 0.3,
      'mod4.src': 'wheel', 'mod4.dst': 'filter.cutoff', 'mod4.amt': 0.18,
      'mod5.src': 'note', 'mod5.dst': 'amp.level', 'mod5.amt': -0.05,
      'mod6.src': 'aftertouch', 'mod6.dst': 'fm.level', 'mod6.amt': 0.3,
      'chorus.on': true, 'chorus.mode': 'ensemble', 'chorus.rate': 0.35, 'chorus.depth': 0.55, 'chorus.mix': 0.35,
      'delay.on': true, 'delay.sync': '1/4D', 'delay.feedback': 0.32, 'delay.pingpong': 0.85, 'delay.tone': 0.4, 'delay.mix': 0.12,
      'reverb.on': true, 'reverb.size': 0.85, 'reverb.decay': 6.5, 'reverb.predelay': 0.03, 'reverb.damp': 0.4, 'reverb.mod': 0.5, 'reverb.shimmer': 0.12, 'reverb.mix': 0.36,
      'eq.high': 1.5, 'comp.amount': 0.2,
      'macro1': 0.3, 'macro2': 0.35, 'macro3': 0.3,
    },
    macros: [
      { name: '光芒 Glow', targets: [{ id: 'filter.cutoff', amount: 0.16 }, { id: 'fm.level', amount: 0.25 }, { id: 'reverb.shimmer', amount: 0.35 }, { id: 'eq.high', amount: 0.08 }] },
      { name: '流動 Motion', targets: [{ id: 'mod1.amt', amount: 0.03 }, { id: 'mod2.amt', amount: 0.2 }, { id: 'mod3.amt', amount: 0.2 }, { id: 'lfo2.rate', amount: 0.12 }, { id: 'chorus.depth', amount: 0.25 }] },
      { name: '空間 Space', targets: [{ id: 'reverb.mix', amount: 0.25 }, { id: 'reverb.decay', amount: 0.15 }, { id: 'delay.mix', amount: 0.18 }] },
      { name: '起音 Swell', targets: [{ id: 'aenv.a', amount: 0.4 }, { id: 'fenv.a', amount: 0.25 }, { id: 'aenv.r', amount: 0.15 }] },
    ],
    demo: 'pad',
    demoMacros: [
      { index: 0, to: 0.9, beat: 0, beats: 8 },
      { index: 1, to: 0.8, beat: 4, beats: 6 },
      { index: 0, to: 0.3, beat: 9, beats: 6 },
      { index: 1, to: 0.35, beat: 11, beats: 5 },
    ],
  },

  // 2 ── warm analog poly
  {
    name: 'Velvet Dusk',
    category: 'pad',
    tags: ['analog', 'warm', 'vintage'],
    description: '鋸齒與脈寬調變的經典類比雙振盪器，裹上合唱效果，如黃昏的絲絨餘暉',
    params: {
      'voice.spread': 0.3,
      'osc1.level': 0.62, 'osc1.unison': 2, 'osc1.detune': 0.12, 'osc1.drift': 0.35,
      'osc2.on': true, 'osc2.shape': 1, 'osc2.pw': 0.42, 'osc2.level': 0.45, 'osc2.drift': 0.35, 'osc2.fine': 4,
      'filter.cutoff': 1300, 'filter.res': 0.2, 'filter.key': 0.5, 'filter.env': 0.22, 'filter.vel': 0.25,
      'fenv.a': 0.45, 'fenv.d': 2.2, 'fenv.s': 0.4, 'fenv.r': 1.5,
      'aenv.a': 0.22, 'aenv.d': 1.5, 'aenv.s': 0.85, 'aenv.r': 1.6,
      'amp.vel': 0.4, 'amp.level': -4.5,
      'lfo1.shape': 'tri', 'lfo1.rate': 0.55, 'lfo1.mode': 'mono',
      'lfo2.rate': 0.3, 'lfo2.mode': 'mono',
      'mod1.src': 'lfo1', 'mod1.dst': 'osc2.pw', 'mod1.amt': 0.28,
      'mod2.src': 'lfo2', 'mod2.dst': 'filter.cutoff', 'mod2.amt': 0.03,
      'mod3.src': 'wheel', 'mod3.dst': 'filter.cutoff', 'mod3.amt': 0.2,
      'mod4.src': 'lfo2', 'mod4.dst': 'voice.pitch', 'mod4.amt': 0.0003,
      'vib.wheel': 12,
      'chorus.on': true, 'chorus.rate': 0.55, 'chorus.depth': 0.65,
      'drive.on': true, 'drive.type': 'tube', 'drive.amount': 0.22, 'drive.tone': 0.35, 'drive.mix': 0,
      'delay.on': true, 'delay.sync': '1/4', 'delay.feedback': 0.3, 'delay.wobble': 0.55, 'delay.tone': 0.3, 'delay.mix': 0,
      'reverb.on': true, 'reverb.size': 0.62, 'reverb.decay': 3.2, 'reverb.damp': 0.55, 'reverb.mix': 0.26,
      'eq.low': 1, 'comp.amount': 0.15,
    },
    macros: [
      { name: '亮度 Bright', targets: [{ id: 'filter.cutoff', amount: 0.22 }, { id: 'filter.env', amount: 0.1 }] },
      { name: '合唱 Ensemble', targets: [{ id: 'chorus.depth', amount: 0.35 }, { id: 'chorus.mix', amount: 0.3 }, { id: 'chorus.rate', amount: 0.12 }, { id: 'osc1.detune', amount: 0.15 }] },
      { name: '磁帶 Tape', targets: [{ id: 'drive.mix', amount: 0.8 }, { id: 'mod4.amt', amount: 0.0012 }, { id: 'delay.mix', amount: 0.22 }, { id: 'osc1.drift', amount: 0.45 }, { id: 'osc2.drift', amount: 0.45 }, { id: 'eq.high', amount: -0.25 }, { id: 'eq.low', amount: -0.08 }] },
      { name: '起音 Swell', targets: [{ id: 'aenv.a', amount: 0.4 }, { id: 'fenv.a', amount: 0.3 }, { id: 'aenv.r', amount: 0.15 }] },
    ],
    demo: 'pad',
    demoMacros: [
      { index: 2, to: 0.8, beat: 0, beats: 8 },
      { index: 2, to: 0, beat: 10, beats: 6 },
    ],
  },

  // 3 ── celestial choir
  {
    name: 'Seraphim Voices',
    category: 'pad',
    tags: ['choir', 'angelic', 'ethereal'],
    description: '天使般柔和的「嗚—喔」合唱在穹頂下迴旋，微光殘響把人聲托向高處',
    params: {
      'voice.spread': 0.45,
      'vib.depth': 9, 'vib.rate': 4.8, 'vib.delay': 0.9, 'vib.wheel': 0,
      'osc1.mode': 'wavetable', 'osc1.table': 'vowels', 'osc1.shape': 0.8, 'osc1.level': 0.72, 'osc1.filt': 0.35,
      'osc1.unison': 5, 'osc1.detune': 0.16, 'osc1.spread': 0.9, 'osc1.drift': 0.4,
      'osc2.on': true, 'osc2.shape': 0.2, 'osc2.level': 0.26, 'osc2.filt': 0,
      'osc2.unison': 3, 'osc2.detune': 0.1, 'osc2.drift': 0.4,
      'noise.on': true, 'noise.level': 0.08, 'noise.color': 0.2,
      'filter.type': 'formant', 'filter.cutoff': 2200, 'filter.res': 0.3, 'filter.key': 0.15, 'filter.vowel': 0.8,
      'filter2.type': 'lp', 'filter2.cutoff': 7000,
      'aenv.a': 0.7, 'aenv.d': 2, 'aenv.s': 0.9, 'aenv.r': 2.8,
      'amp.vel': 0.35, 'amp.level': -1.6,
      'lfo1.rate': 0.11, 'lfo1.mode': 'mono',
      'lfo2.shape': 'smooth', 'lfo2.rate': 0.4,
      'mod1.src': 'lfo1', 'mod1.dst': 'filter.vowel', 'mod1.amt': 0.06,
      'mod2.src': 'lfo2', 'mod2.dst': 'osc1.shape', 'mod2.amt': 0.06,
      'mod3.src': 'wheel', 'mod3.dst': 'vib.depth', 'mod3.amt': 0.2,
      'mod4.src': 'velocity', 'mod4.dst': 'osc1.shape', 'mod4.amt': -0.2,
      'mod5.src': 'velocity', 'mod5.dst': 'filter.vowel', 'mod5.amt': -0.15,
      'chorus.on': true, 'chorus.mode': 'ensemble', 'chorus.rate': 0.3, 'chorus.depth': 0.55, 'chorus.mix': 0.3,
      'reverb.on': true, 'reverb.size': 0.92, 'reverb.decay': 7, 'reverb.predelay': 0.04, 'reverb.damp': 0.45, 'reverb.shimmer': 0.18, 'reverb.mix': 0.4,
      'comp.amount': 0.15,
    },
    macros: [
      { name: '母音 Vowel', targets: [{ id: 'filter.vowel', amount: -0.75 }, { id: 'osc1.shape', amount: -0.7 }] },
      { name: '氣息 Breath', targets: [{ id: 'noise.level', amount: 0.65 }, { id: 'noise.color', amount: 0.15 }, { id: 'osc1.level', amount: -0.15 }] },
      { name: '聲部 Voices', targets: [{ id: 'filter.cutoff', amount: -0.25 }, { id: 'osc1.detune', amount: 0.3 }, { id: 'chorus.mix', amount: 0.25 }, { id: 'osc2.level', amount: 0.15 }] },
      { name: '天堂 Heaven', targets: [{ id: 'reverb.mix', amount: 0.25 }, { id: 'reverb.decay', amount: 0.2 }, { id: 'reverb.shimmer', amount: 0.35 }] },
    ],
    demo: 'pad',
    demoMacros: [
      { index: 0, to: 0.8, beat: 0, beats: 8 },
      { index: 0, to: 0, beat: 8, beats: 8 },
    ],
  },

  // 4 ── glass / crystal shimmer
  {
    name: 'Prism Halo',
    category: 'pad',
    tags: ['glass', 'shimmer', 'bright'],
    description: '玻璃波表與 FM 泛音層層折射，微光殘響把每個和弦化成懸浮的光環',
    params: {
      'voice.spread': 0.5,
      'osc1.mode': 'wavetable', 'osc1.table': 'glass', 'osc1.shape': 0.3, 'osc1.level': 0.55,
      'osc1.unison': 4, 'osc1.detune': 0.12, 'osc1.spread': 1, 'osc1.drift': 0.2,
      'osc2.on': true, 'osc2.shape': 0.1, 'osc2.level': 0.22, 'osc2.filt': 0, 'osc2.unison': 2, 'osc2.detune': 0.08,
      'fm.on': true, 'fm.level': 0.45, 'fm.filt': 0.3, 'fm.algo': 5, 'fm.feedback': 0.15,
      'fm.op1.level': 0.9, 'fm.op1.a': 0.7, 'fm.op1.d': 6, 'fm.op1.s': 0.85, 'fm.op1.r': 2.5, 'fm.op1.vel': 0.2,
      'fm.op2.ratio': 2, 'fm.op2.detune': 7, 'fm.op2.level': 0.55, 'fm.op2.a': 0.9, 'fm.op2.d': 6, 'fm.op2.s': 0.8, 'fm.op2.r': 2.8, 'fm.op2.vel': 0.2,
      'fm.op3.ratio': 3, 'fm.op3.detune': -7, 'fm.op3.level': 0.4, 'fm.op3.a': 1.2, 'fm.op3.d': 6, 'fm.op3.s': 0.8, 'fm.op3.r': 3, 'fm.op3.vel': 0.2, 'fm.op3.kscale': -0.3,
      'fm.op4.ratio': 4, 'fm.op4.level': 0.24, 'fm.op4.a': 1.6, 'fm.op4.d': 4, 'fm.op4.s': 0.6, 'fm.op4.r': 3, 'fm.op4.kscale': -0.3,
      'filter.type': 'lp', 'filter.cutoff': 4800, 'filter.res': 0.12, 'filter.key': 0.5, 'filter.vel': 0.2,
      'filter2.type': 'hp', 'filter2.cutoff': 160,
      'aenv.a': 0.7, 'aenv.d': 3, 'aenv.s': 0.85, 'aenv.r': 4,
      'amp.vel': 0.3, 'amp.level': -4.5,
      'lfo1.shape': 'smooth', 'lfo1.rate': 0.25,
      'mod1.src': 'lfo1', 'mod1.dst': 'osc1.shape', 'mod1.amt': 0.12,
      'mod2.src': 'wheel', 'mod2.dst': 'fm.op4.level', 'mod2.amt': 0.3,
      'mod3.src': 'note', 'mod3.dst': 'amp.level', 'mod3.amt': -0.06,
      'delay.on': true, 'delay.feedback': 0.45, 'delay.pingpong': 0.9, 'delay.tone': 0.65, 'delay.mix': 0.16,
      'reverb.on': true, 'reverb.size': 0.9, 'reverb.decay': 8, 'reverb.damp': 0.3, 'reverb.mod': 0.5, 'reverb.shimmer': 0.4, 'reverb.mix': 0.42,
    },
    macros: [
      { name: '微光 Shimmer', targets: [{ id: 'reverb.shimmer', amount: 0.45 }, { id: 'reverb.mix', amount: 0.1 }] },
      { name: '晶瑩 Sparkle', targets: [{ id: 'osc1.shape', amount: 0.35 }, { id: 'fm.op4.level', amount: 0.2 }, { id: 'mod1.amt', amount: 0.1 }] },
      { name: '深度 Depth', targets: [{ id: 'osc2.level', amount: 0.3 }, { id: 'filter2.cutoff', amount: -0.15 }, { id: 'filter.cutoff', amount: -0.08 }] },
      { name: '回聲 Echo', targets: [{ id: 'delay.mix', amount: 0.25 }, { id: 'delay.feedback', amount: 0.2 }] },
    ],
    demo: 'pad',
    demoMacros: [
      { index: 1, to: 0.8, beat: 0, beats: 10 },
      { index: 1, to: 0, beat: 10, beats: 6 },
    ],
  },

  // 5 ── dark cinematic drone
  {
    name: 'Event Horizon',
    category: 'pad',
    tags: ['dark', 'cinematic', 'drone'],
    description: '咆哮波表與深沉鋸齒在暗處緩緩蠕動，像被黑洞邊緣吞沒的電影配樂',
    params: {
      'voice.spread': 0.3,
      'osc1.level': 0.6, 'osc1.unison': 5, 'osc1.detune': 0.25, 'osc1.spread': 0.8, 'osc1.drift': 0.4,
      'osc2.on': true, 'osc2.mode': 'wavetable', 'osc2.table': 'growl', 'osc2.shape': 0.25, 'osc2.level': 0.35,
      'osc2.unison': 3, 'osc2.detune': 0.25,
      'noise.on': true, 'noise.level': 0.04, 'noise.color': -0.5,
      'filter.cutoff': 700, 'filter.res': 0.35, 'filter.drive': 0.3, 'filter.key': 0.75, 'filter.vel': 0.2,
      'filter2.type': 'hp', 'filter2.cutoff': 70,
      'aenv.a': 1.4, 'aenv.d': 3, 'aenv.s': 1, 'aenv.r': 4.5,
      'lfo1.rate': 0.05, 'lfo1.mode': 'mono',
      'lfo2.shape': 'smooth', 'lfo2.rate': 0.15,
      'mod1.src': 'lfo1', 'mod1.dst': 'filter.cutoff', 'mod1.amt': 0.08,
      'mod2.src': 'lfo2', 'mod2.dst': 'osc2.shape', 'mod2.amt': 0.2,
      'mod3.src': 'wheel', 'mod3.dst': 'filter.res', 'mod3.amt': 0.3,
      'vib.wheel': 0,
      'drive.on': true, 'drive.type': 'tube', 'drive.mix': 0.5, 'drive.tone': 0.4,
      'phaser.on': true, 'phaser.rate': 0.06, 'phaser.depth': 0.6, 'phaser.feedback': 0.5, 'phaser.mix': 0.3,
      'reverb.on': true, 'reverb.size': 1, 'reverb.decay': 8, 'reverb.predelay': 0.07, 'reverb.damp': 0.72, 'reverb.mix': 0.42,
      'amp.level': 1, 'comp.amount': 0.25,
    },
    macros: [
      { name: '張力 Tension', targets: [{ id: 'filter.res', amount: 0.35 }, { id: 'filter.drive', amount: 0.4 }, { id: 'filter.cutoff', amount: 0.08 }] },
      { name: '黑暗 Darkness', targets: [{ id: 'filter.cutoff', amount: -0.15 }, { id: 'reverb.damp', amount: 0.2 }, { id: 'eq.high', amount: -0.2 }] },
      { name: '蠕動 Crawl', targets: [{ id: 'mod1.amt', amount: 0.12 }, { id: 'mod2.amt', amount: 0.25 }, { id: 'lfo1.rate', amount: 0.25 }, { id: 'phaser.mix', amount: 0.3 }] },
      { name: '深淵 Abyss', targets: [{ id: 'reverb.mix', amount: 0.25 }, { id: 'reverb.decay', amount: 0.15 }, { id: 'noise.level', amount: 0.15 }] },
    ],
    demo: 'pad',
    demoMacros: [
      { index: 0, to: 0.8, beat: 2, beats: 10 },
      { index: 0, to: 0, beat: 12, beats: 4 },
    ],
  },

  // 6 ── rhythmic motion
  {
    name: 'Kaleidoscope',
    category: 'pad',
    tags: ['motion', 'rhythmic', 'evolving'],
    description: '隨節拍呼吸起伏的律動鋪底，數位波表不斷變換色彩，如萬花筒般旋轉',
    params: {
      'voice.spread': 0.4,
      'osc1.mode': 'wavetable', 'osc1.table': 'digital', 'osc1.shape': 0.2, 'osc1.level': 0.6,
      'osc1.unison': 5, 'osc1.spread': 0.9,
      'osc2.on': true, 'osc2.mode': 'wavetable', 'osc2.table': 'harmonic', 'osc2.shape': 0.35, 'osc2.oct': 1, 'osc2.level': 0.3,
      'osc2.unison': 3, 'osc2.detune': 0.15,
      'filter.type': 'lp', 'filter.cutoff': 2200, 'filter.res': 0.3, 'filter.key': 0.4, 'filter.vel': 0.2,
      'aenv.a': 0.12, 'aenv.d': 1.5, 'aenv.s': 0.9, 'aenv.r': 1.4,
      'amp.level': -3,
      'lfo1.shape': 'tri', 'lfo1.sync': '2/1', 'lfo1.mode': 'mono',
      'lfo2.sync': '1/4', 'lfo2.mode': 'mono', 'lfo2.phase': 0.75,
      'mod1.src': 'lfo1', 'mod1.dst': 'osc1.shape', 'mod1.amt': 0.2,
      'mod2.src': 'lfo2', 'mod2.dst': 'amp.level', 'mod2.amt': 0.06,
      'mod3.src': 'lfo2', 'mod3.dst': 'filter.cutoff', 'mod3.amt': 0.06,
      'mod4.src': 'wheel', 'mod4.dst': 'filter.res', 'mod4.amt': 0.35,
      'phaser.on': true, 'phaser.rate': 0.15, 'phaser.depth': 0.6, 'phaser.mix': 0.3,
      'delay.on': true, 'delay.feedback': 0.4, 'delay.pingpong': 1, 'delay.tone': 0.55, 'delay.mix': 0.18,
      'reverb.on': true, 'reverb.size': 0.7, 'reverb.decay': 3.5, 'reverb.mix': 0.28,
      'comp.amount': 0.25,
    },
    macros: [
      { name: '律動 Pump', targets: [{ id: 'mod2.amt', amount: 0.07 }, { id: 'mod3.amt', amount: 0.03 }] },
      { name: '變幻 Morph', targets: [{ id: 'osc1.shape', amount: 0.5 }, { id: 'mod1.amt', amount: 0.12 }] },
      { name: '共振 Resonance', targets: [{ id: 'filter.res', amount: 0.32 }, { id: 'filter.cutoff', amount: 0.03 }, { id: 'mod3.amt', amount: 0.02 }] },
      { name: '回聲 Echo', targets: [{ id: 'delay.mix', amount: 0.22 }, { id: 'delay.feedback', amount: 0.2 }] },
    ],
    demo: 'pad',
    demoMacros: [
      { index: 0, to: 1, beat: 0, beats: 8 },
      { index: 1, to: 0.7, beat: 4, beats: 8 },
      { index: 0, to: 0, beat: 12, beats: 4 },
      { index: 1, to: 0, beat: 12, beats: 4 },
    ],
  },

  // 7 ── breathy airy
  {
    name: 'Zephyr',
    category: 'pad',
    tags: ['airy', 'breathy', 'soft'],
    description: '柔和的正弦齊奏裹著吹管氣息與掠過的風聲，輕盈得像春日西風',
    params: {
      'voice.spread': 0.45,
      'osc1.shape': 0.15, 'osc1.level': 0.5, 'osc1.unison': 3, 'osc1.detune': 0.12, 'osc1.drift': 0.3, 'osc1.filt': 0,
      'osc2.on': true, 'osc2.mode': 'wavetable', 'osc2.table': 'harmonic', 'osc2.shape': 0.1, 'osc2.oct': 1, 'osc2.level': 0.2, 'osc2.filt': 0,
      'phys.on': true, 'phys.level': 0.35, 'phys.exciter': 'breath', 'phys.hardness': 0.45, 'phys.position': 0.5, 'phys.decay': 1.4,
      'phys.brightness': 0.35, 'phys.inharm': 0, 'phys.body': 0, 'phys.spread': 0.4, 'phys.damp': 0.8,
      'noise.on': true, 'noise.level': 0.25, 'noise.color': -0.3,
      'filter.type': 'bp', 'filter.cutoff': 1600, 'filter.res': 0.45, 'filter.key': 0.6,
      'filter2.type': 'lp', 'filter2.cutoff': 6500,
      'aenv.a': 0.6, 'aenv.d': 2, 'aenv.s': 0.9, 'aenv.r': 2.5,
      'amp.vel': 0.4, 'amp.level': -4,
      'lfo1.shape': 'smooth', 'lfo1.rate': 0.18,
      'mod1.src': 'lfo1', 'mod1.dst': 'filter.cutoff', 'mod1.amt': 0.1,
      'mod2.src': 'wheel', 'mod2.dst': 'phys.pressure', 'mod2.amt': 0.3,
      'mod3.src': 'note', 'mod3.dst': 'amp.level', 'mod3.amt': -0.07,
      'mod4.src': 'wheel', 'mod4.dst': 'noise.level', 'mod4.amt': 0.25,
      'chorus.on': true, 'chorus.rate': 0.25, 'chorus.mix': 0.3,
      'reverb.on': true, 'reverb.size': 0.9, 'reverb.decay': 6, 'reverb.mix': 0.42,
      'eq.high': -2,
    },
    macros: [
      { name: '氣息 Breath', targets: [{ id: 'noise.level', amount: 0.3 }, { id: 'phys.pressure', amount: 0.25 }] },
      { name: '風速 Wind', targets: [{ id: 'mod1.amt', amount: 0.15 }, { id: 'lfo1.rate', amount: 0.2 }] },
      { name: '音色 Tone', targets: [{ id: 'osc1.shape', amount: 0.25 }, { id: 'osc2.shape', amount: 0.35 }, { id: 'osc1.level', amount: -0.1 }, { id: 'phys.brightness', amount: 0.25 }] },
      { name: '空間 Space', targets: [{ id: 'reverb.mix', amount: 0.25 }, { id: 'reverb.decay', amount: 0.2 }] },
    ],
    demo: 'pad',
    demoMacros: [
      { index: 1, to: 0.85, beat: 0, beats: 8 },
      { index: 1, to: 0, beat: 9, beats: 7 },
    ],
  },

  // 8 ── bowed vibraphone texture
  {
    name: 'Bowed Nocturne',
    category: 'pad',
    tags: ['physical', 'bowed', 'mallet'],
    description: '琴弓拉奏鐵琴音條的物理模型，金屬長音在夜色中吟唱，開啟馬達便泛起顫音',
    params: {
      'voice.spread': 0.8,
      'phys.on': true, 'phys.level': 0.75, 'phys.model': 'bar', 'phys.exciter': 'bow',
      'phys.position': 0.85, 'phys.decay': 10, 'phys.inharm': 0.04, 'phys.brightness': 0.7, 'phys.body': 0.4,
      'phys.spread': 1, 'phys.damp': 0.5,
      'osc1.shape': 0, 'osc1.oct': 1, 'osc1.level': 0.06, 'osc1.unison': 2, 'osc1.detune': 0.1, 'osc1.spread': 1,
      'filter.type': 'lp', 'filter.cutoff': 3000, 'filter.key': 0.5,
      'aenv.a': 0.45, 'aenv.d': 3, 'aenv.s': 1, 'aenv.r': 2.4,
      'amp.level': -5,
      'lfo1.rate': 5.2, 'lfo1.mode': 'mono',
      'lfo2.shape': 'smooth', 'lfo2.rate': 0.2,
      'mod1.src': 'lfo1', 'mod1.dst': 'amp.level', 'mod1.amt': 0.004,
      'mod2.src': 'lfo2', 'mod2.dst': 'phys.pressure', 'mod2.amt': 0.08,
      'mod3.src': 'wheel', 'mod3.dst': 'phys.pressure', 'mod3.amt': 0.25,
      'mod4.src': 'note', 'mod4.dst': 'amp.level', 'mod4.amt': -0.09,
      'vib.wheel': 0,
      // no chorus and a drier reverb: on this near-sine bar their slow comb notches made the same key come out
      // up to 5.5 LU louder or softer from press to press (8 LU across C3–C5)
      'delay.on': true, 'delay.sync': '1/2', 'delay.feedback': 0.3, 'delay.pingpong': 0.8, 'delay.mix': 0.1,
      'reverb.on': true, 'reverb.size': 0.88, 'reverb.decay': 7.5, 'reverb.damp': 0.4, 'reverb.shimmer': 0.12, 'reverb.mix': 0.25,
    },
    macros: [
      { name: '弓壓 Bow', targets: [{ id: 'phys.pressure', amount: 0.35 }, { id: 'phys.brightness', amount: 0.15 }] },
      { name: '馬達 Motor', targets: [{ id: 'mod1.amt', amount: 0.07 }, { id: 'lfo1.rate', amount: 0.04 }, { id: 'amp.level', amount: -0.05 }] },
      { name: '光暈 Halo', targets: [{ id: 'osc1.level', amount: 0.25 }, { id: 'reverb.shimmer', amount: 0.35 }] },
      { name: '空間 Space', targets: [{ id: 'reverb.mix', amount: 0.25 }, { id: 'reverb.decay', amount: 0.2 }, { id: 'delay.mix', amount: 0.2 }] },
    ],
    demo: 'pad',
    demoMacros: [
      { index: 1, to: 0.8, beat: 4, beats: 4 },
      { index: 1, to: 0, beat: 12, beats: 4 },
    ],
  },

  // 9 ── 80s brass pad
  {
    name: 'Starfall Brass',
    category: 'pad',
    tags: ['brass', '80s', 'bold'],
    description: '八〇年代電影感銅管鋪底，濾波包絡吹出飽滿起音，觸後壓力讓它更明亮',
    params: {
      'voice.spread': 0.5,
      'vib.depth': 6, 'vib.rate': 5.2, 'vib.delay': 0.7,
      'osc1.level': 0.6, 'osc1.unison': 3, 'osc1.detune': 0.14, 'osc1.drift': 0.25,
      'osc2.on': true, 'osc2.level': 0.55, 'osc2.fine': 7, 'osc2.drift': 0.25,
      'filter.cutoff': 650, 'filter.res': 0.12, 'filter.key': 0.6, 'filter.env': 0.42, 'filter.vel': 0.3,
      'fenv.a': 0.09, 'fenv.d': 1.1, 'fenv.s': 0.45, 'fenv.r': 0.8, 'fenv.curve': 0.4,
      'aenv.a': 0.07, 'aenv.d': 1.2, 'aenv.s': 0.88, 'aenv.r': 0.9,
      'amp.vel': 0.45, 'amp.level': -3,
      'mod1.src': 'aftertouch', 'mod1.dst': 'filter.cutoff', 'mod1.amt': 0.15,
      'chorus.on': true, 'chorus.rate': 0.4, 'chorus.depth': 0.45, 'chorus.mix': 0.36,
      'delay.on': true, 'delay.sync': '1/4', 'delay.feedback': 0.25, 'delay.mix': 0.1, 'delay.tone': 0.4,
      'reverb.on': true, 'reverb.size': 0.55, 'reverb.decay': 2.6, 'reverb.damp': 0.45, 'reverb.mix': 0.22,
      'comp.amount': 0.3,
    },
    macros: [
      { name: '咆哮 Blare', targets: [{ id: 'filter.env', amount: 0.2 }, { id: 'filter.drive', amount: 0.35 }, { id: 'fenv.d', amount: -0.1 }] },
      { name: '亮度 Bright', targets: [{ id: 'filter.cutoff', amount: 0.2 }] },
      { name: '厚度 Stack', targets: [{ id: 'osc1.detune', amount: 0.25 }, { id: 'chorus.mix', amount: 0.25 }, { id: 'voice.spread', amount: 0.3 }] },
      { name: '空間 Space', targets: [{ id: 'reverb.mix', amount: 0.25 }, { id: 'reverb.decay', amount: 0.2 }, { id: 'delay.mix', amount: 0.15 }] },
    ],
    demo: 'pad',
    demoMacros: [
      { index: 1, to: 0.8, beat: 0, beats: 6 },
      { index: 0, to: 0.7, beat: 4, beats: 4 },
      { index: 1, to: 0, beat: 10, beats: 6 },
      { index: 0, to: 0, beat: 12, beats: 4 },
    ],
  },

  // 10 ── ambient sunrise swell
  {
    name: 'First Light',
    category: 'pad',
    tags: ['ambient', 'swell', 'evolving'],
    description: '從幽暗緩緩升起的泛音掃描，每個和弦都像地平線上逐漸亮起的第一道晨光',
    params: {
      'voice.spread': 0.4,
      'osc1.mode': 'wavetable', 'osc1.table': 'harmonic', 'osc1.shape': 0.1, 'osc1.level': 0.65,
      'osc1.unison': 5, 'osc1.spread': 0.9, 'osc1.drift': 0.3,
      'osc2.on': true, 'osc2.mode': 'wavetable', 'osc2.table': 'strings', 'osc2.shape': 0.3, 'osc2.oct': 1, 'osc2.level': 0.22,
      'filter.type': 'ladder12', 'filter.cutoff': 650, 'filter.res': 0.15, 'filter.key': 0.45, 'filter.env': 0.35, 'filter.vel': 0.15,
      'fenv.a': 4, 'fenv.d': 5, 'fenv.s': 0.7, 'fenv.r': 4, 'fenv.curve': 0.7,
      'menv.a': 5, 'menv.d': 6, 'menv.s': 0.8, 'menv.r': 4,
      'aenv.a': 1.8, 'aenv.d': 4, 'aenv.s': 1, 'aenv.r': 4.5, 'aenv.curve': 0.65, 'amp.level': -1,
      'mod1.src': 'menv', 'mod1.dst': 'osc1.shape', 'mod1.amt': 0.35,
      'lfo1.rate': 0.07, 'lfo1.mode': 'mono',
      'mod2.src': 'lfo1', 'mod2.dst': 'filter.cutoff', 'mod2.amt': 0.04,
      'mod3.src': 'wheel', 'mod3.dst': 'filter.cutoff', 'mod3.amt': 0.2,
      'chorus.on': true, 'chorus.mode': 'ensemble', 'chorus.rate': 0.25, 'chorus.mix': 0.3,
      'delay.on': true, 'delay.sync': '1/2', 'delay.feedback': 0.4, 'delay.pingpong': 0.8, 'delay.tone': 0.45, 'delay.mix': 0.12,
      'reverb.on': true, 'reverb.size': 0.9, 'reverb.decay': 9, 'reverb.damp': 0.4, 'reverb.shimmer': 0.3, 'reverb.mix': 0.45,
    },
    macros: [
      { name: '日出 Sunrise', targets: [{ id: 'filter.cutoff', amount: 0.25 }, { id: 'osc1.shape', amount: 0.35 }, { id: 'reverb.shimmer', amount: 0.3 }] },
      { name: '起音 Attack', targets: [{ id: 'aenv.a', amount: -0.3 }, { id: 'fenv.a', amount: -0.25 }, { id: 'menv.a', amount: -0.2 }] },
      { name: '溫度 Warmth', targets: [{ id: 'osc2.level', amount: 0.3 }, { id: 'eq.low', amount: 0.15 }, { id: 'chorus.mix', amount: 0.25 }] },
      { name: '空間 Space', targets: [{ id: 'reverb.mix', amount: 0.2 }, { id: 'reverb.decay', amount: 0.15 }, { id: 'delay.mix', amount: 0.2 }] },
    ],
    demo: 'pad',
    demoMacros: [
      { index: 0, to: 0.9, beat: 0, beats: 12 },
      { index: 0, to: 0, beat: 12, beats: 4 },
    ],
  },
];
