// Pluck 撥弦 — factory presets (sound design: presets-pluck).
export default [
  {
    name: 'Starlight Harp',
    category: 'pluck',
    tags: ['harp', 'shimmer', 'ethereal'],
    description: '星光灑落的豎琴，高八度玻璃泛音在微光殘響中緩緩升起',
    params: {
      'voice.poly': 16, 'voice.spread': 0.3,
      'osc1.mode': 'wavetable', 'osc1.table': 'glass', 'osc1.shape': 0.25, 'osc1.oct': 1, 'osc1.level': 0,
      'osc1.unison': 2, 'osc1.detune': 0.12,
      'phys.on': true, 'phys.filt': 1,
      'phys.hardness': 0.3, 'phys.position': 0.85, 'phys.decay': 6, 'phys.brightness': 0.5, 'phys.inharm': 0.04,
      'phys.body': 0.25, 'phys.spread': 0.6, 'phys.damp': 0.25,
      'filter.type': 'hp', 'filter.cutoff': 120, 'filter.key': 1, 'filter.res': 0.05,
      'filter2.type': 'lp', 'filter2.cutoff': 8000,
      'aenv.a': 0, 'aenv.d': 10, 'aenv.s': 1, 'aenv.r': 3,
      'menv.a': 0.002, 'menv.d': 1.2, 'menv.r': 1,
      'mod1.src': 'menv', 'mod1.dst': 'osc1.level', 'mod1.amt': 0.22,
      'mod2.src': 'wheel', 'mod2.dst': 'osc1.level', 'mod2.amt': 0.25,
      'mod3.src': 'note', 'mod3.dst': 'phys.decay', 'mod3.amt': -0.12, 'vib.wheel': 0,
      'delay.on': true, 'delay.sync': '1/4D', 'delay.feedback': 0.3, 'delay.tone': 0.45, 'delay.mix': 0.14,
      'reverb.on': true, 'reverb.decay': 5, 'reverb.size': 0.8, 'reverb.shimmer': 0.25, 'reverb.damp': 0.4,
      'amp.level': -4,
    },
    macros: [
      { name: '亮度 Bright', targets: [{ id: 'phys.brightness', amount: 0.35 }, { id: 'phys.hardness', amount: 0.3 }] },
      { name: '星塵 Stardust', targets: [{ id: 'mod1.amt', amount: 0.2 }, { id: 'reverb.shimmer', amount: 0.65 }, { id: 'reverb.mix', amount: 0.1 }] },
      { name: '回聲 Echo', targets: [{ id: 'delay.mix', amount: 0.3 }, { id: 'delay.feedback', amount: 0.3 }] },
      { name: '餘韻 Ring', targets: [{ id: 'phys.decay', amount: 0.15 }, { id: 'reverb.decay', amount: 0.2 }, { id: 'reverb.mix', amount: 0.15 }] },
    ],
    demo: 'pluck',
    demoMacros: [{ index: 1, to: 0.9, beat: 4, beats: 6 }, { index: 1, to: 0, beat: 12, beats: 4 }],
  },
  {
    name: 'Nylon Serenade',
    category: 'pluck',
    tags: ['guitar', 'acoustic', 'warm'],
    description: '月光下的尼龍弦古典吉他，指尖撥奏溫暖圓潤，琴箱共鳴自然',
    params: {
      'osc1.on': false,
      'phys.on': true, 'phys.filt': 1,
      'phys.hardness': 0.35, 'phys.position': 0.22, 'phys.decay': 3.5, 'phys.brightness': 0.45, 'phys.inharm': 0.05,
      'phys.body': 0.55, 'phys.spread': 0.4, 'phys.damp': 0.35,
      'filter.type': 'hp', 'filter.cutoff': 110, 'filter.key': 1, 'filter.res': 0.05,
      'aenv.a': 0, 'aenv.d': 10, 'aenv.s': 1, 'aenv.r': 1.6,
      'amp.vel': 0.65, 'mod1.src': 'note', 'mod1.dst': 'phys.decay', 'mod1.amt': -0.1, 'vib.wheel': 22, 'vib.rate': 5.2,
      'reverb.on': true, 'reverb.decay': 1.8, 'reverb.size': 0.45, 'reverb.mix': 0.2, 'reverb.damp': 0.55,
      'amp.level': 2.6, 'voice.spread': 0.25,
      // peak soft clip (amount 0 = unity-gain tanh, clean at playing level): chords' summed strikes no longer
      // push the output limiter (5-note chord at velocity 0.9)
      'drive.on': true, 'drive.amount': 0, 'drive.mix': 0.4,
    },
    macros: [
      { name: '音色 Tone', targets: [{ id: 'phys.brightness', amount: 0.3 }, { id: 'phys.position', amount: -0.14 }] },
      { name: '悶音 Mute', targets: [{ id: 'phys.damp', amount: 0.5 }, { id: 'phys.decay', amount: -0.16 }, { id: 'phys.brightness', amount: -0.12 }, { id: 'aenv.r', amount: -0.1 }, { id: 'amp.level', amount: 0.06 }] },
      { name: '揉弦 Vibrato', targets: [{ id: 'vib.depth', amount: 0.2 }, { id: 'vib.delay', amount: -0.15 }, { id: 'phys.decay', amount: 0.06 }] },
      { name: '空間 Room', targets: [{ id: 'reverb.mix', amount: 0.25 }, { id: 'reverb.decay', amount: 0.15 }] },
    ],
    demo: 'pluck',
    demoMacros: [{ index: 0, to: 0.85, beat: 4, beats: 6 }, { index: 0, to: 0, beat: 12, beats: 4 }],
  },
  {
    name: 'Jade Guzheng',
    category: 'pluck',
    tags: ['guzheng', 'asian', 'bend'],
    description: '玉石般清亮的古箏，指甲撥弦帶出金屬光澤，揉弦與上滑音婉轉生情',
    params: {
      'osc1.on': false,
      'phys.on': true, 'phys.filt': 1,
      'phys.hardness': 0.6, 'phys.position': 0.12, 'phys.decay': 4.5, 'phys.brightness': 0.68, 'phys.inharm': 0.14,
      'phys.body': 0.35, 'phys.spread': 0.35, 'voice.spread': 0.2, 'phys.damp': 0.45,
      'filter.type': 'hp', 'filter.cutoff': 120, 'filter.key': 1, 'filter.res': 0.05, 'filter2.type': 'lp', 'filter2.cutoff': 10000,
      'aenv.a': 0, 'aenv.d': 10, 'aenv.s': 1, 'aenv.r': 2,
      'vib.depth': 10, 'vib.rate': 5, 'vib.delay': 0.4, 'vib.wheel': 40,
      'menv.a': 0, 'menv.d': 0.18, 'menv.r': 0.1,
      'mod1.src': 'menv', 'mod1.dst': 'voice.pitch', 'mod1.amt': -0.006,
      'mod2.src': 'note', 'mod2.dst': 'phys.decay', 'mod2.amt': -0.1,
      'delay.on': true, 'delay.feedback': 0.28, 'delay.tone': 0.4, 'delay.mix': 0.12,
      'reverb.on': true, 'reverb.decay': 2.6, 'reverb.mix': 0.22,
      'amp.level': 1.3, 'phys.level': 1,
      // peak soft clip (amount 0 = unity-gain tanh, clean at playing level): chords' summed strikes no longer
      // push the output limiter (5-note chord at velocity 0.9)
      'drive.on': true, 'drive.amount': 0, 'drive.mix': 0.5,
    },
    macros: [
      { name: '亮度 Bright', targets: [{ id: 'phys.brightness', amount: 0.25 }, { id: 'phys.hardness', amount: 0.2 }] },
      { name: '滑音 Slide', targets: [{ id: 'mod1.amt', amount: -0.012 }, { id: 'menv.d', amount: 0.12 }] },
      { name: '揉弦 Vibrato', targets: [{ id: 'vib.depth', amount: 0.25 }, { id: 'vib.delay', amount: -0.2 }] },
      { name: '空間 Space', targets: [{ id: 'delay.mix', amount: 0.25 }, { id: 'reverb.mix', amount: 0.2 }] },
    ],
    demo: 'pluck',
    demoMacros: [{ index: 1, to: 0.8, beat: 4, beats: 6 }, { index: 1, to: 0, beat: 12, beats: 4 }],
  },
  {
    name: 'Dewdrop Kalimba',
    category: 'pluck',
    tags: ['kalimba', 'mallet', 'playful'],
    description: '晨露般晶瑩的拇指琴，金屬簧片輕彈，木箱共鳴與乒乓回聲輕盈跳躍',
    params: {
      'osc1.on': false,
      'phys.on': true, 'phys.model': 'bar',
      'phys.hardness': 0.62, 'phys.position': 0.15, 'phys.decay': 2.4, 'phys.brightness': 0.42, 'phys.inharm': 0.55,
      'phys.body': 0.5, 'phys.spread': 0.35, 'voice.spread': 0.25, 'phys.damp': 0.5,
      'fm.on': true, 'fm.level': 0.75, 'fm.algo': 3, 'fm.filt': 0,
      'fm.op1.level': 0.5, 'fm.op1.d': 1.2, 'fm.op1.s': 0, 'fm.op1.r': 0.4, 'fm.op1.vel': 0.4,
      'fm.op2.level': 0.25, 'fm.op2.d': 0.12, 'fm.op2.s': 0, 'fm.op2.r': 0.1, 'fm.op2.vel': 0.8,
      'fm.op3.ratio': 6.27, 'fm.op3.level': 0.8, 'fm.op3.d': 0.5, 'fm.op3.s': 0, 'fm.op3.r': 0.1, 'fm.op3.vel': 0.7,
      'fm.op4.level': 0.05, 'fm.op4.d': 0.1, 'fm.op4.s': 0, 'fm.op4.r': 0.1,
      'aenv.a': 0, 'aenv.d': 10, 'aenv.s': 1, 'aenv.r': 1.5,
      'delay.on': true, 'delay.sync': '1/8', 'delay.pingpong': 0.9, 'delay.tone': 0.55, 'delay.mix': 0.2,
      'reverb.on': true, 'reverb.decay': 2.2, 'reverb.mix': 0.2,
      'amp.level': -3, 'mod1.src': 'note', 'mod1.dst': 'amp.level', 'mod1.amt': -0.22,
    },
    macros: [
      { name: '金屬 Tine', targets: [{ id: 'fm.op3.level', amount: 0.2 }, { id: 'phys.brightness', amount: 0.25 }, { id: 'phys.hardness', amount: 0.15 }] },
      { name: '木箱 Box', targets: [{ id: 'phys.body', amount: 0.5 }, { id: 'eq.low', amount: 0.2 }, { id: 'fm.op1.level', amount: 0.25 }] },
      { name: '回聲 Echo', targets: [{ id: 'delay.mix', amount: 0.3 }, { id: 'delay.feedback', amount: 0.25 }] },
      { name: '長度 Length', targets: [{ id: 'phys.decay', amount: 0.12 }, { id: 'fm.op1.d', amount: 0.12 }, { id: 'aenv.r', amount: 0.1 }] },
    ],
    demo: 'pluck',
    demoMacros: [{ index: 2, to: 0.9, beat: 4, beats: 6 }, { index: 2, to: 0, beat: 12, beats: 4 }],
  },
  {
    name: 'Sunrise Anthem',
    category: 'pluck',
    tags: ['trance', 'supersaw', 'edm'],
    description: '日出時分的電音撥奏，超鋸齒齊奏配上快速濾波包絡與附點乒乓延遲',
    params: {
      'osc1.level': 1, 'osc1.unison': 7, 'osc1.detune': 0.3, 'osc1.spread': 0.9, 'osc1.phase': 'random',
      'osc2.on': true, 'osc2.oct': 1, 'osc2.unison': 3, 'osc2.detune': 0.18, 'osc2.level': 0.3, 'osc2.phase': 'random',
      'filter.cutoff': 550, 'filter.res': 0.3, 'filter.env': 0.6, 'filter.key': 0.6, 'filter.vel': 0.15,
      'fenv.a': 0, 'fenv.d': 0.22, 'fenv.s': 0, 'fenv.r': 0.2,
      'aenv.a': 0, 'aenv.d': 0.7, 'aenv.s': 0.05, 'aenv.r': 0.25,
      'mod1.src': 'wheel', 'mod1.dst': 'filter.cutoff', 'mod1.amt': 0.2,
      'mod2.src': 'note', 'mod2.dst': 'amp.level', 'mod2.amt': -0.1,
      'delay.on': true, 'delay.feedback': 0.4, 'delay.pingpong': 0.8, 'delay.tone': 0.45, 'delay.mix': 0.2,
      'reverb.on': true, 'reverb.decay': 3.5, 'reverb.size': 0.8, 'reverb.mix': 0.22,
      'amp.level': 5.5,
    },
    macros: [
      { name: '截止 Cutoff', targets: [{ id: 'filter.cutoff', amount: 0.25 }] },
      { name: '長度 Decay', targets: [{ id: 'fenv.d', amount: 0.2 }, { id: 'aenv.d', amount: 0.1 }, { id: 'amp.level', amount: -0.04 }] },
      { name: '共振 Reso', targets: [{ id: 'filter.res', amount: 0.5 }] },
      { name: '空間 Space', targets: [{ id: 'delay.mix', amount: 0.25 }, { id: 'reverb.mix', amount: 0.25 }] },
    ],
    demo: 'pluck',
    demoMacros: [{ index: 0, to: 0.9, beat: 4, beats: 6 }, { index: 0, to: 0, beat: 12, beats: 4 }],
  },
  {
    name: 'Pizzicato Hall',
    category: 'pluck',
    tags: ['pizzicato', 'orchestral', 'strings'],
    description: '音樂廳裡的弦樂撥奏群，短促圓潤的指撥在寬廣殘響中此起彼落',
    params: {
      'osc1.on': false,
      'phys.on': true, 'phys.filt': 1,
      'phys.hardness': 0.32, 'phys.position': 0.3, 'phys.decay': 1.0, 'phys.brightness': 0.46, 'phys.inharm': 0.02,
      'phys.body': 0.8, 'phys.spread': 0.5, 'phys.damp': 0.8,
      'filter.type': 'hp', 'filter.cutoff': 110, 'filter.key': 1, 'filter.res': 0.05,
      'aenv.a': 0, 'aenv.d': 10, 'aenv.s': 1, 'aenv.r': 0.8,
      'voice.spread': 0.4, 'mod1.src': 'note', 'mod1.dst': 'phys.decay', 'mod1.amt': -0.15,
      'mod2.src': 'wheel', 'mod2.dst': 'phys.hardness', 'mod2.amt': 0.3,
      'chorus.on': true, 'chorus.mode': 'ensemble', 'chorus.mix': 0.3, 'chorus.rate': 0.4,
      'reverb.on': true, 'reverb.decay': 2.8, 'reverb.size': 0.85, 'reverb.predelay': 0.03, 'reverb.mix': 0.28,
      'amp.level': 5, 'phys.level': 1,
      // peak soft clip (amount 0 = unity-gain tanh, clean at playing level): chords' summed strikes no longer
      // push the output limiter (5-note chord at velocity 0.9)
      'drive.on': true, 'drive.amount': 0, 'drive.mix': 0.8,
    },
    macros: [
      { name: '力度 Snap', targets: [{ id: 'phys.hardness', amount: 0.35 }, { id: 'phys.brightness', amount: 0.2 }] },
      { name: '群奏 Section', targets: [{ id: 'chorus.mix', amount: 0.4 }, { id: 'voice.spread', amount: 0.4 }] },
      { name: '長度 Length', targets: [{ id: 'phys.decay', amount: 0.15 }, { id: 'phys.damp', amount: -0.4 }] },
      { name: '音樂廳 Hall', targets: [{ id: 'reverb.mix', amount: 0.25 }, { id: 'reverb.decay', amount: 0.12 }] },
    ],
    demo: 'pluck',
    demoMacros: [{ index: 1, to: 0.9, beat: 4, beats: 6 }, { index: 1, to: 0, beat: 12, beats: 4 }],
  },
  {
    name: 'Prism Shards',
    category: 'pluck',
    tags: ['wavetable', 'digital', 'glassy'],
    description: '光線穿過稜鏡的數位碎片，波表位置隨每次撥奏迅速掃過',
    params: {
      'osc1.mode': 'wavetable', 'osc1.table': 'digital', 'osc1.shape': 0.8, 'osc1.unison': 3, 'osc1.detune': 0.12, 'osc1.spread': 0.8,
      'osc1.level': 1, 'osc2.on': true, 'osc2.shape': 0.2, 'osc2.level': 0.4,
      'filter.cutoff': 2500, 'filter.res': 0.15, 'filter.env': 0.35, 'filter.key': 0.5, 'filter.vel': 0.25,
      'fenv.a': 0, 'fenv.d': 0.45, 'fenv.s': 0, 'fenv.r': 0.3,
      'aenv.a': 0, 'aenv.d': 0.8, 'aenv.s': 0.08, 'aenv.r': 0.35,
      'menv.a': 0, 'menv.d': 0.35, 'menv.r': 0.2,
      'mod1.src': 'menv', 'mod1.dst': 'osc1.shape', 'mod1.amt': 0.2,
      'mod2.src': 'wheel', 'mod2.dst': 'osc1.shape', 'mod2.amt': -0.3,
      'delay.on': true, 'delay.sync': '3/16', 'delay.feedback': 0.4, 'delay.pingpong': 0.8, 'delay.mix': 0.22,
      'reverb.on': true, 'reverb.decay': 2.2, 'reverb.mix': 0.2,
      'drive.on': true, 'drive.type': 'crush', 'drive.amount': 0.2, 'drive.mix': 0,
      'amp.level': 4.5,
    },
    macros: [
      { name: '掃描 Scan', targets: [{ id: 'osc1.shape', amount: -0.5 }, { id: 'mod1.amt', amount: 0.25 }] },
      { name: '衰減 Decay', targets: [{ id: 'menv.d', amount: 0.2 }, { id: 'aenv.d', amount: 0.1 }, { id: 'fenv.d', amount: 0.15 }] },
      { name: '晶格 Crush', targets: [{ id: 'drive.mix', amount: 0.45 }, { id: 'drive.amount', amount: 0.3 }] },
      { name: '回聲 Echo', targets: [{ id: 'delay.mix', amount: 0.3 }, { id: 'delay.feedback', amount: 0.25 }] },
    ],
    demo: 'pluck',
    demoMacros: [{ index: 0, to: 1, beat: 4, beats: 6 }, { index: 0, to: 0, beat: 12, beats: 4 }],
  },
  {
    name: 'Golden Twelve',
    category: 'pluck',
    tags: ['guitar', '12-string', 'chorus'],
    description: '金色陽光般閃耀的十二弦鋼弦吉他，八度複弦與合唱交織出豐盈光澤',
    params: {
      'osc1.on': false, 'voice.poly': 16, 'chord.type': 'oct',
      'phys.on': true, 'phys.filt': 1,
      'phys.hardness': 0.55, 'phys.position': 0.18, 'phys.decay': 5, 'phys.brightness': 0.65, 'phys.inharm': 0.08,
      'phys.body': 0.45, 'phys.spread': 0.6, 'phys.damp': 0.4,
      'filter.type': 'hp', 'filter.cutoff': 110, 'filter.key': 1, 'filter.res': 0.05, 'filter2.type': 'lp', 'filter2.cutoff': 9000,
      'mod1.src': 'note', 'mod1.dst': 'phys.brightness', 'mod1.amt': -0.3,
      'mod2.src': 'note', 'mod2.dst': 'phys.decay', 'mod2.amt': -0.12,
      'aenv.a': 0, 'aenv.d': 10, 'aenv.s': 1, 'aenv.r': 2,
      'chorus.on': true, 'chorus.mix': 0.3, 'chorus.rate': 0.5, 'chorus.depth': 0.4,
      'reverb.on': true, 'reverb.decay': 2.2, 'reverb.mix': 0.2,
      'amp.level': -1,
      // peak soft clip (amount 0 = unity-gain tanh, clean at playing level): chords' summed strikes no longer
      // push the output limiter (5-note chord at velocity 0.9)
      'drive.on': true, 'drive.amount': 0, 'drive.mix': 0.6,
    },
    macros: [
      { name: '亮度 Bright', targets: [{ id: 'phys.brightness', amount: 0.25 }, { id: 'phys.hardness', amount: 0.2 }] },
      { name: '閃爍 Shimmer', targets: [{ id: 'chorus.mix', amount: 0.35 }, { id: 'chorus.depth', amount: 0.3 }] },
      { name: '撥片 Pick', targets: [{ id: 'phys.position', amount: -0.07 }, { id: 'phys.hardness', amount: 0.4 }, { id: 'amp.level', amount: 0.025 }] },
      { name: '空間 Space', targets: [{ id: 'reverb.mix', amount: 0.25 }, { id: 'reverb.decay', amount: 0.12 }] },
    ],
    demo: 'pluck',
    demoMacros: [{ index: 1, to: 0.9, beat: 4, beats: 6 }, { index: 1, to: 0, beat: 12, beats: 4 }],
  },
  {
    name: 'Cassette Bloom',
    category: 'pluck',
    tags: ['lofi', 'fm', 'tape'],
    description: '舊卡帶裡綻放的 Lo-fi 撥音，FM 柔和鐘感帶著磁帶抖動與溫暖顆粒',
    params: {
      'osc1.on': false,
      'fm.on': true, 'fm.algo': 3, 'fm.feedback': 0.1,
      'fm.op1.d': 1.6, 'fm.op1.s': 0, 'fm.op1.r': 0.5, 'fm.op1.vel': 0.35,
      'fm.op2.level': 0.32, 'fm.op2.d': 0.35, 'fm.op2.s': 0, 'fm.op2.vel': 0.8,
      'fm.op3.ratio': 2, 'fm.op3.level': 0.45, 'fm.op3.d': 0.9, 'fm.op3.s': 0, 'fm.op3.vel': 0.5,
      'fm.op4.ratio': 3, 'fm.op4.level': 0.2, 'fm.op4.d': 0.2, 'fm.op4.s': 0, 'fm.op4.r': 0.2, 'fm.op4.vel': 0.7,
      'filter.type': 'ladder12', 'filter.cutoff': 3500, 'filter.key': 0.2,
      'aenv.a': 0, 'aenv.d': 10, 'aenv.s': 1, 'aenv.r': 0.5,
      'lfo1.mode': 'mono', 'lfo1.rate': 0.7,
      'mod1.src': 'lfo1', 'mod1.dst': 'voice.pitch', 'mod1.amt': 0.0015,
      'mod2.src': 'note', 'mod2.dst': 'amp.level', 'mod2.amt': -0.1,
      'chorus.on': true, 'chorus.rate': 0.3, 'chorus.depth': 0.4, 'chorus.mix': 0.25,
      'delay.on': true, 'delay.sync': '1/4', 'delay.wobble': 0.5, 'delay.tone': 0.3, 'delay.mix': 0.18,
      'reverb.on': true, 'reverb.decay': 1.8, 'reverb.mix': 0.18, 'reverb.damp': 0.7,
      'drive.on': true, 'drive.type': 'tube', 'drive.amount': 0.25, 'drive.tone': 0.4,
      'amp.level': 3.9, 'fm.level': 1,
    },
    macros: [
      { name: '磁帶 Wow', targets: [{ id: 'mod1.amt', amount: 0.0025 }, { id: 'delay.wobble', amount: 0.4 }, { id: 'chorus.depth', amount: 0.3 }] },
      { name: '溫暖 Warmth', targets: [{ id: 'filter.cutoff', amount: -0.2 }, { id: 'eq.low', amount: 0.12 }, { id: 'eq.high', amount: -0.15 }] },
      { name: '顆粒 Grit', targets: [{ id: 'drive.amount', amount: 0.4 }, { id: 'drive.tone', amount: 0.15 }] },
      { name: '回聲 Echo', targets: [{ id: 'delay.mix', amount: 0.3 }, { id: 'delay.feedback', amount: 0.25 }] },
    ],
    demo: 'keys',
    demoMacros: [{ index: 0, to: 0.9, beat: 4, beats: 6 }, { index: 0, to: 0, beat: 15, beats: 5 }],
  },
  {
    name: 'Bamboo Bloop',
    category: 'pluck',
    tags: ['mallet', 'playful', 'water'],
    description: '雨滴落在竹筒上的俏皮木質撥音，每一下都帶著「啵」的水滴音高滑升',
    params: {
      'osc1.shape': 0, 'osc1.level': 0.5,
      'phys.on': true, 'phys.model': 'bar', 'phys.exciter': 'mallet', 'phys.oct': 1,
      'phys.hardness': 0.55, 'phys.position': 0.9, 'phys.decay': 0.7, 'phys.brightness': 0.45, 'phys.inharm': 0,
      'phys.body': 0.7, 'phys.spread': 0.4, 'phys.damp': 0.5, 'phys.level': 0.65,
      'filter.type': 'lp', 'filter.cutoff': 2000, 'filter.env': 0.3, 'filter.key': 0.5,
      'fenv.a': 0, 'fenv.d': 0.15, 'fenv.s': 0, 'fenv.r': 0.1,
      'aenv.a': 0, 'aenv.d': 0.5, 'aenv.s': 0, 'aenv.r': 0.4,
      'menv.a': 0, 'menv.d': 0.09, 'menv.r': 0.05,
      'mod1.src': 'menv', 'mod1.dst': 'voice.pitch', 'mod1.amt': -0.1,
      'delay.on': true, 'delay.sync': '1/16', 'delay.feedback': 0.3, 'delay.pingpong': 1, 'delay.mix': 0.18,
      'reverb.on': true, 'reverb.decay': 1.5, 'reverb.mix': 0.18,
      'amp.level': 3.9, 'voice.spread': 0.35,
      // peak soft clip (amount 0 = unity-gain tanh, clean at playing level): chords' summed strikes no longer
      // push the output limiter (5-note chord at velocity 0.9)
      'drive.on': true, 'drive.amount': 0,
    },
    macros: [
      { name: '水滴 Drop', targets: [{ id: 'mod1.amt', amount: -0.1 }, { id: 'menv.d', amount: 0.1 }, { id: 'amp.level', amount: 0.03 }] },
      { name: '竹管 Bamboo', targets: [{ id: 'phys.level', amount: 0.2 }, { id: 'phys.hardness', amount: 0.3 }, { id: 'osc1.level', amount: -0.2 }] },
      { name: '回聲 Echo', targets: [{ id: 'delay.mix', amount: 0.3 }, { id: 'delay.feedback', amount: 0.25 }] },
      { name: '長度 Length', targets: [{ id: 'aenv.d', amount: 0.08 }, { id: 'phys.decay', amount: 0.12 }] },
    ],
    demo: 'pluck',
    demoMacros: [{ index: 0, to: 1, beat: 4, beats: 6 }, { index: 0, to: 0, beat: 12, beats: 4 }],
  },
];
