// Strings & Winds 弦樂/管樂 — factory presets (docs/ARCHITECTURE.md §9).
// Calibrated offline (tools/render.mjs): each preset ≈ −19 LUFS on its demo phrase, peaks ≤ −6 dBFS, no limiting;
// every macro stays within ≈ ±4 LU over 0..1. `demoMacros` = macro rides for the ▶ Demo ({index, to, beat, beats} →
// sequencer 'ramp-macro' events); each ride returns to its start so the looping demo stays consistent.
// Expression: velocity → level + brightness everywhere; mod wheel → vibrato (bowed/winds), cutoff (brass/ensembles)
// or vowel (choir); aftertouch → vibrato, bow/breath pressure or brightness.
export default [
  // 1 ── flagship: hybrid orchestral string section
  {
    name: 'Aurora Symphony',
    category: 'strings',
    tags: ['orchestral', 'ensemble', 'lush', 'cinematic'],
    description: '波表弦群、物理擦弦與低音提琴層層交織，從極弱推到極強；轉動「極光」，整座音樂廳泛起微光',
    params: {
      'osc1.mode': 'wavetable', 'osc1.table': 'strings', 'osc1.shape': 0.38, 'osc1.unison': 5, 'osc1.detune': 0.16,
      'osc1.spread': 1, 'osc1.drift': 0.3, 'osc1.level': 0.6,
      'osc2.on': true, 'osc2.mode': 'wavetable', 'osc2.table': 'strings', 'osc2.shape': 0.3, 'osc2.oct': -1, 'osc2.unison': 2, 'osc2.detune': 0.08, 'osc2.level': 0.22,
      'phys.on': true, 'phys.exciter': 'bow', 'phys.hardness': 0.45, 'phys.decay': 2.5, 'phys.brightness': 0.5, 'phys.inharm': 0.03,
      'phys.pressure': 0.6, 'phys.body': 0.55, 'phys.spread': 0, 'phys.level': 0.3, 'phys.filt': 1,
      'filter.type': 'lp', 'filter.cutoff': 2100, 'filter.res': 0.12, 'filter.env': 0.12, 'filter.vel': 0.3,
      'fenv.a': 0.45, 'fenv.d': 1.8, 'fenv.s': 0.6, 'fenv.r': 1.2,
      'aenv.a': 0.3, 'aenv.d': 1.2, 'aenv.s': 1, 'aenv.r': 1.1, 'amp.vel': 0.55,
      'vib.depth': 11, 'vib.rate': 5.2, 'vib.delay': 0.7, 'vib.wheel': 22,
      'lfo2.rate': 0.13, 'lfo2.shape': 'smooth',
      'mod1.src': 'wheel', 'mod1.dst': 'filter.cutoff', 'mod1.amt': 0.14,
      'mod2.src': 'lfo2', 'mod2.dst': 'osc1.shape', 'mod2.amt': 0.06,
      'mod3.src': 'aftertouch', 'mod3.dst': 'vib.depth', 'mod3.amt': 0.25,
      'mod4.src': 'note', 'mod4.dst': 'osc2.level', 'mod4.amt': -0.45,
      'mod5.src': 'wheel', 'mod5.dst': 'amp.level', 'mod5.amt': 0.04,
      'voice.spread': 0.45,
      'chorus.on': true, 'chorus.mode': 'ensemble', 'chorus.rate': 0.45, 'chorus.depth': 0.55, 'chorus.mix': 0.32,
      'reverb.on': true, 'reverb.size': 0.85, 'reverb.decay': 4.2, 'reverb.predelay': 0.035, 'reverb.damp': 0.45, 'reverb.mix': 0.32,
      'eq.low': -1.5, 'eq.high': 1, 'comp.amount': 0.2,
      'amp.level': -4.5,
      'macro1': 0.3,
    },
    macros: [
      { name: '力度 Dynamics', targets: [{ id: 'filter.cutoff', amount: 0.16 }, { id: 'osc1.shape', amount: 0.3 }, { id: 'amp.level', amount: 0.07 }, { id: 'phys.pressure', amount: 0.3 }] },
      { name: '運弓 Bowing', targets: [{ id: 'aenv.a', amount: -0.3 }, { id: 'fenv.a', amount: -0.3 }, { id: 'phys.hardness', amount: 0.4 }, { id: 'filter.env', amount: 0.15 }, { id: 'aenv.r', amount: -0.12 }] },
      { name: '合奏 Ensemble', targets: [{ id: 'chorus.mix', amount: 0.35 }, { id: 'osc1.detune', amount: 0.18 }, { id: 'voice.spread', amount: 0.4 }] },
      { name: '極光 Aurora', targets: [{ id: 'reverb.mix', amount: 0.25 }, { id: 'reverb.decay', amount: 0.12 }, { id: 'reverb.shimmer', amount: 0.35 }, { id: 'reverb.predelay', amount: 0.1 }] },
    ],
    demo: 'strings',
    demoMacros: [{ index: 3, to: 0, beat: 0, beats: 2 }, { index: 0, to: 0.95, beat: 0, beats: 9 }, { index: 0, to: 0.35, beat: 11, beats: 5 }, { index: 3, to: 0.75, beat: 11, beats: 5 }],
  },

  // 2 ── bowed solo cello (Section macro fades in a wavetable cello section)
  {
    name: 'Rosewood Cello',
    category: 'strings',
    tags: ['cello', 'bowed', 'warm'],
    description: '物理擦弦大提琴，琴身溫暖、揉弦緩緩浮現；推「聲部」巨集，獨奏瞬間化為整排大提琴',
    params: {
      'osc1.mode': 'wavetable', 'osc1.table': 'strings', 'osc1.shape': 0.3, 'osc1.unison': 5, 'osc1.detune': 0.15, 'osc1.spread': 0.9, 'osc1.drift': 0.3, 'osc1.level': 0,
      'phys.on': true, 'phys.exciter': 'bow', 'phys.hardness': 0.42, 'phys.position': 0.5, 'phys.decay': 2.5, 'phys.brightness': 0.55,
      'phys.inharm': 0.03, 'phys.pressure': 0.6, 'phys.body': 0.62, 'phys.spread': 0.25, 'phys.damp': 0.6, 'phys.level': 0.85, 'phys.filt': 1,
      'filter.type': 'lp', 'filter.cutoff': 2600, 'filter.res': 0.15, 'filter.key': 0.25, 'filter.vel': 0.25,
      'filter2.type': 'hp', 'filter2.cutoff': 45,
      'aenv.a': 0.02, 'aenv.s': 1, 'aenv.r': 0.8,
      'vib.depth': 16, 'vib.rate': 5.3, 'vib.delay': 0.45, 'vib.wheel': 25,
      'mod1.src': 'aftertouch', 'mod1.dst': 'phys.pressure', 'mod1.amt': 0.35,
      'mod2.src': 'velocity', 'mod2.dst': 'phys.brightness', 'mod2.amt': 0.2,
      'voice.spread': 0.3,
      'chorus.on': true, 'chorus.mode': 'ensemble', 'chorus.rate': 0.4, 'chorus.mix': 0,
      'reverb.on': true, 'reverb.size': 0.62, 'reverb.decay': 2.6, 'reverb.predelay': 0.025, 'reverb.damp': 0.55, 'reverb.mix': 0.24,
      'eq.low': 1, 'eq.mid': -1.5, 'eq.midfreq': 700,
      'amp.level': -6.5,
    },
    macros: [
      { name: '弓壓 Pressure', targets: [{ id: 'phys.pressure', amount: 0.35 }, { id: 'phys.brightness', amount: 0.25 }, { id: 'filter.cutoff', amount: 0.1 }] },
      { name: '揉弦 Vibrato', targets: [{ id: 'vib.depth', amount: 0.25 }, { id: 'vib.delay', amount: -0.3 }] },
      { name: '聲部 Section', targets: [{ id: 'osc1.level', amount: 0.45 }, { id: 'chorus.mix', amount: 0.45 }, { id: 'voice.spread', amount: 0.4 }, { id: 'phys.spread', amount: 0.4 }] },
      { name: '空間 Room', targets: [{ id: 'reverb.mix', amount: 0.3 }, { id: 'reverb.size', amount: 0.3 }, { id: 'reverb.decay', amount: 0.12 }] },
    ],
    demo: 'strings',
    demoMacros: [{ index: 1, to: 0.7, beat: 0, beats: 4 }, { index: 2, to: 0.85, beat: 4, beats: 6 }, { index: 2, to: 0, beat: 13, beats: 3 }, { index: 1, to: 0.2, beat: 14, beats: 2 }],
  },

  // 3 ── erhu: nasal bowed lead with slides
  {
    name: 'Autumn Moon Erhu',
    category: 'strings',
    tags: ['erhu', 'bowed', 'expressive', 'lead'],
    description: '平湖秋月般的二胡，鼻音般的擦弦、深情揉弦與滑音，推調變輪揉得更深',
    params: {
      'osc1.on': false,
      'phys.on': true, 'phys.exciter': 'bow', 'phys.hardness': 0.55, 'phys.position': 0.3, 'phys.brightness': 0.7,
      'phys.inharm': 0.05, 'phys.pressure': 0.55, 'phys.body': 0.15, 'phys.spread': 0.1, 'phys.damp': 0.5, 'phys.filt': 1,
      'filter.type': 'lp', 'filter.cutoff': 3800, 'filter.res': 0.3, 'filter.key': 0.2, 'filter.vel': 0.22,
      'filter2.type': 'hp', 'filter2.cutoff': 120,
      'voice.mode': 'legato', 'voice.glide': 0.12,
      'aenv.a': 0.02, 'aenv.s': 1, 'aenv.r': 0.35,
      'vib.depth': 26, 'vib.rate': 5.8, 'vib.delay': 0.25, 'vib.wheel': 40,
      'mod1.src': 'aftertouch', 'mod1.dst': 'vib.depth', 'mod1.amt': 0.3,
      'mod2.src': 'velocity', 'mod2.dst': 'phys.pressure', 'mod2.amt': 0.25,
      'mod3.src': 'note', 'mod3.dst': 'amp.level', 'mod3.amt': -0.08,
      'delay.on': true, 'delay.feedback': 0.3, 'delay.tone': 0.4, 'delay.mix': 0.12, 'delay.pingpong': 0.7,
      'reverb.on': true, 'reverb.size': 0.7, 'reverb.decay': 3.2, 'reverb.predelay': 0.03, 'reverb.mix': 0.28,
      'eq.low': -3, 'eq.mid': 5, 'eq.midfreq': 1400,
      'amp.level': -3.2,
      'macro1': 0.3,
    },
    macros: [
      { name: '揉弦 Vibrato', targets: [{ id: 'vib.depth', amount: 0.3 }, { id: 'vib.rate', amount: 0.08 }] },
      { name: '滑音 Glide', targets: [{ id: 'voice.glide', amount: 0.22 }] },
      { name: '鼻音 Nasal', targets: [{ id: 'eq.mid', amount: 0.2 }, { id: 'filter.res', amount: 0.25 }, { id: 'amp.level', amount: -0.045 }] },
      { name: '月色 Moonlight', targets: [{ id: 'reverb.mix', amount: 0.3 }, { id: 'delay.mix', amount: 0.2 }, { id: 'reverb.decay', amount: 0.1 }] },
    ],
    demo: 'lead',
    demoMacros: [{ index: 1, to: 0.7, beat: 7, beats: 1 }, { index: 0, to: 0.9, beat: 9.5, beats: 2 }, { index: 1, to: 0, beat: 13, beats: 2 }, { index: 0, to: 0.3, beat: 13, beats: 2 }],
  },

  // 4 ── brass section: FM brass + saw with filter blat
  {
    name: 'Gilded Fanfare',
    category: 'strings',
    tags: ['brass', 'section', 'punchy'],
    description: '金光閃閃的銅管聲部，FM 銅管疊上鋸齒波，下鍵越重越嘹亮，推調變輪就發出咆哮',
    params: {
      'fm.on': true, 'fm.level': 0.62, 'fm.algo': 2, 'fm.feedback': 0.45,
      'fm.op1.a': 0.03, 'fm.op1.d': 3, 'fm.op1.s': 0.85, 'fm.op1.r': 0.25,
      'fm.op2.level': 0.41, 'fm.op2.a': 0.09, 'fm.op2.d': 1.2, 'fm.op2.s': 0.55, 'fm.op2.r': 0.25, 'fm.op2.vel': 0.6, 'fm.op2.kscale': -0.25,
      'fm.op3.detune': 5, 'fm.op3.level': 0.2, 'fm.op3.a': 0.12, 'fm.op3.s': 0.7, 'fm.op3.r': 0.25,
      'fm.op4.detune': -5, 'fm.op4.level': 0.18, 'fm.op4.a': 0.07, 'fm.op4.s': 0.7, 'fm.op4.r': 0.25,
      'osc1.unison': 3, 'osc1.detune': 0.08, 'osc1.level': 0.45,
      'filter.cutoff': 750, 'filter.res': 0.15, 'filter.key': 0.6, 'filter.env': 0.42, 'filter.vel': 0.35, 'filter.drive': 0.2,
      'fenv.a': 0.06, 'fenv.d': 0.6, 'fenv.s': 0.45, 'fenv.r': 0.3,
      'aenv.a': 0.035, 'aenv.d': 0.5, 'aenv.s': 0.9, 'aenv.r': 0.25, 'amp.vel': 0.6,
      'menv.a': 0, 'menv.d': 0.09, 'menv.r': 0.05,
      'mod1.src': 'menv', 'mod1.dst': 'voice.pitch', 'mod1.amt': -0.008,
      'mod2.src': 'wheel', 'mod2.dst': 'filter.cutoff', 'mod2.amt': 0.15,
      'mod3.src': 'aftertouch', 'mod3.dst': 'filter.cutoff', 'mod3.amt': 0.1,
      'vib.delay': 0.4, 'vib.wheel': 12,
      'voice.spread': 0.5,
      'chorus.on': true, 'chorus.mix': 0.2, 'chorus.depth': 0.3,
      'reverb.on': true, 'reverb.size': 0.75, 'reverb.decay': 2.8, 'reverb.predelay': 0.03, 'reverb.mix': 0.25,
      'comp.amount': 0.3,
      'amp.level': -4,
    },
    macros: [
      { name: '咆哮 Bite', targets: [{ id: 'filter.env', amount: 0.25 }, { id: 'filter.drive', amount: 0.35 }, { id: 'fm.op2.level', amount: 0.1 }] },
      { name: '漸強 Swell', targets: [{ id: 'aenv.a', amount: 0.3 }, { id: 'fenv.a', amount: 0.35 }] },
      { name: '聲部 Section', targets: [{ id: 'chorus.mix', amount: 0.35 }, { id: 'osc1.detune', amount: 0.2 }, { id: 'voice.spread', amount: 0.4 }] },
      { name: '空間 Hall', targets: [{ id: 'reverb.mix', amount: 0.3 }, { id: 'reverb.decay', amount: 0.12 }] },
    ],
    demo: 'keys',
    demoMacros: [{ index: 0, to: 0.8, beat: 4, beats: 8 }, { index: 0, to: 0.1, beat: 16, beats: 4 }],
  },

  // 5 ── french horn: mellow, round, distant hall
  {
    name: 'Twilight Horn',
    category: 'strings',
    tags: ['horn', 'mellow', 'orchestral'],
    description: '暮色中的法國號，圓潤溫暖、慢慢綻放，彷彿從遠方的音樂廳傳來',
    params: {
      'osc1.level': 0.75, 'osc1.drift': 0.25,
      'filter.cutoff': 520, 'filter.res': 0.12, 'filter.key': 0.7, 'filter.env': 0.3, 'filter.vel': 0.4,
      'fenv.a': 0.12, 'fenv.d': 0.9, 'fenv.s': 0.55, 'fenv.r': 0.5,
      'aenv.a': 0.07, 'aenv.d': 0.8, 'aenv.s': 0.95, 'aenv.r': 0.45, 'amp.vel': 0.6,
      'menv.a': 0, 'menv.d': 0.12, 'menv.r': 0.05,
      'mod1.src': 'menv', 'mod1.dst': 'voice.pitch', 'mod1.amt': -0.006,
      'mod2.src': 'wheel', 'mod2.dst': 'filter.cutoff', 'mod2.amt': 0.12,
      'mod3.src': 'aftertouch', 'mod3.dst': 'filter.cutoff', 'mod3.amt': 0.08,
      'vib.delay': 0.6, 'vib.wheel': 15,
      'voice.spread': 0.4,
      'chorus.on': true, 'chorus.mix': 0, 'chorus.depth': 0.35, 'chorus.rate': 0.35,
      'reverb.on': true, 'reverb.size': 0.8, 'reverb.decay': 3.8, 'reverb.predelay': 0.045, 'reverb.damp': 0.6, 'reverb.mix': 0.32,
      'eq.mid': 2, 'eq.midfreq': 420,
      'amp.level': -4.5,
    },
    macros: [
      { name: '力度 Dynamics', targets: [{ id: 'filter.cutoff', amount: 0.15 }, { id: 'filter.env', amount: 0.15 }, { id: 'amp.level', amount: 0.05 }] },
      { name: '漸強 Swell', targets: [{ id: 'aenv.a', amount: 0.4 }, { id: 'fenv.a', amount: 0.4 }] },
      { name: '聲部 Section', targets: [{ id: 'chorus.mix', amount: 0.45 }, { id: 'chorus.depth', amount: 0.3 }, { id: 'voice.spread', amount: 0.45 }] },
      { name: '空間 Hall', targets: [{ id: 'reverb.mix', amount: 0.3 }, { id: 'reverb.predelay', amount: 0.2 }, { id: 'reverb.decay', amount: 0.12 }] },
    ],
    demo: 'pad',
    demoMacros: [{ index: 0, to: 0.8, beat: 4, beats: 8 }, { index: 0, to: 0.25, beat: 12, beats: 4 }],
  },

  // 6 ── pan flute: breath physical model + chiff
  {
    name: 'Andes Pan Flute',
    category: 'strings',
    tags: ['flute', 'breathy', 'world'],
    description: '安地斯山的排笛，物理吹氣模型帶著氣音、顫音與山谷回聲',
    params: {
      'osc1.on': false,
      'phys.on': true, 'phys.exciter': 'breath', 'phys.hardness': 0.45, 'phys.position': 0.5, 'phys.decay': 1.4, 'phys.brightness': 0.35,
      'phys.inharm': 0, 'phys.pressure': 0.55, 'phys.body': 0, 'phys.spread': 0.15, 'phys.damp': 0.8, 'phys.filt': 1,
      'noise.on': true, 'noise.level': 0.2, 'noise.decay': 0.12,
      'filter.type': 'lp', 'filter.cutoff': 4500, 'filter.res': 0, 'filter.key': 0.5,
      'filter2.type': 'hp', 'filter2.cutoff': 150,
      'voice.mode': 'legato', 'voice.glide': 0.04,
      'aenv.a': 0.03, 'aenv.d': 1, 'aenv.s': 1,
      'vib.depth': 14, 'vib.rate': 5, 'vib.delay': 0.35,
      'lfo1.rate': 5, 'lfo1.fade': 0.6,
      'mod1.src': 'lfo1', 'mod1.dst': 'amp.level', 'mod1.amt': 0.02,
      'mod2.src': 'aftertouch', 'mod2.dst': 'phys.pressure', 'mod2.amt': 0.3,
      'delay.on': true, 'delay.tone': 0.45, 'delay.mix': 0.18, 'delay.pingpong': 0.8,
      'reverb.on': true, 'reverb.size': 0.8, 'reverb.decay': 3.5, 'reverb.predelay': 0.03,
    },
    macros: [
      { name: '氣息 Breath', targets: [{ id: 'phys.pressure', amount: 0.3 }, { id: 'noise.level', amount: 0.3 }, { id: 'phys.hardness', amount: 0.2 }, { id: 'amp.level', amount: -0.04 }] },
      { name: '顫音 Vibrato', targets: [{ id: 'vib.depth', amount: 0.3 }] },
      { name: '回聲 Echo', targets: [{ id: 'delay.mix', amount: 0.3 }, { id: 'delay.feedback', amount: 0.25 }] },
      { name: '山谷 Canyon', targets: [{ id: 'reverb.mix', amount: 0.3 }, { id: 'reverb.decay', amount: 0.12 }] },
    ],
    demo: 'lead',
    demoMacros: [{ index: 2, to: 0.7, beat: 8, beats: 4 }, { index: 2, to: 0, beat: 14, beats: 2 }],
  },

  // 7 ── clarinet: square/odd harmonics, reed breath
  {
    name: 'Ebony Clarinet',
    category: 'strings',
    tags: ['clarinet', 'woodwind', 'jazz'],
    description: '烏木單簧管，奇次泛音的木質音色與簧片氣息，低音溫潤、高音明亮',
    params: {
      'osc1.shape': 1, 'osc1.pw': 0.47, 'osc1.level': 0.7, 'osc1.drift': 0.05,
      'noise.on': true, 'noise.level': 0.06, 'noise.color': -0.2, 'noise.filt': 0.9,
      'filter.cutoff': 900, 'filter.res': 0.15, 'filter.key': 0.8, 'filter.env': 0.1, 'filter.vel': 0.25,
      'filter2.type': 'hp', 'filter2.cutoff': 120,
      'fenv.a': 0.02, 'fenv.s': 0.7, 'fenv.r': 0.2,
      'voice.mode': 'legato', 'voice.glide': 0.03,
      'aenv.a': 0.035, 'aenv.d': 0.5, 'aenv.s': 1, 'aenv.r': 0.18,
      'vib.depth': 4, 'vib.rate': 5, 'vib.delay': 0.6, 'vib.wheel': 20,
      'mod1.src': 'aftertouch', 'mod1.dst': 'filter.cutoff', 'mod1.amt': 0.1,
      'reverb.on': true, 'reverb.size': 0.45, 'reverb.decay': 1.8, 'reverb.mix': 0.2,
      'amp.level': -3,
    },
    macros: [
      { name: '亮度 Bright', targets: [{ id: 'filter.cutoff', amount: 0.13 }, { id: 'filter.res', amount: 0.12 }] },
      { name: '氣息 Breath', targets: [{ id: 'noise.level', amount: 0.35 }] },
      { name: '顫音 Vibrato', targets: [{ id: 'vib.depth', amount: 0.2 }] },
      { name: '空間 Room', targets: [{ id: 'reverb.mix', amount: 0.3 }, { id: 'reverb.size', amount: 0.3 }] },
    ],
    demo: 'lead',
    demoMacros: [{ index: 0, to: 0.6, beat: 8, beats: 4 }, { index: 2, to: 0.7, beat: 9, beats: 3 }, { index: 0, to: 0.1, beat: 13, beats: 3 }, { index: 2, to: 0, beat: 14, beats: 2 }],
  },

  // 8 ── choir "ah": saws through the formant filter + vowel wavetable
  {
    name: 'Vesper Choir',
    category: 'strings',
    tags: ['choir', 'vocal', 'ethereal'],
    description: '晚禱合唱團，母音從「啊」慢慢轉成「喔」，在教堂殘響裡迴盪',
    params: {
      'osc1.unison': 6, 'osc1.detune': 0.14, 'osc1.spread': 0.9, 'osc1.drift': 0.4, 'osc1.level': 0.6,
      'osc2.on': true, 'osc2.mode': 'wavetable', 'osc2.table': 'vowels', 'osc2.shape': 0, 'osc2.unison': 3, 'osc2.level': 0.3, 'osc2.filt': 0.5,
      'noise.on': true, 'noise.level': 0.04, 'noise.color': 0.3,
      'filter.type': 'formant', 'filter.cutoff': 1000, 'filter.res': 0, 'filter.key': 1,
      'aenv.a': 0.45, 'aenv.d': 1, 'aenv.s': 1, 'aenv.r': 1.5,
      'vib.depth': 9, 'vib.rate': 5, 'vib.delay': 0.5, 'vib.wheel': 20,
      'lfo2.rate': 0.2, 'lfo2.shape': 'smooth',
      'mod1.src': 'lfo2', 'mod1.dst': 'filter.vowel', 'mod1.amt': 0.03,
      'mod2.src': 'wheel', 'mod2.dst': 'filter.vowel', 'mod2.amt': 0.5,
      'mod3.src': 'aftertouch', 'mod3.dst': 'vib.depth', 'mod3.amt': 0.2,
      'mod4.src': 'note', 'mod4.dst': 'amp.level', 'mod4.amt': -0.12,
      'chorus.on': true, 'chorus.mode': 'ensemble', 'chorus.mix': 0.4,
      'reverb.on': true, 'reverb.size': 0.9, 'reverb.decay': 5.5, 'reverb.predelay': 0.04, 'reverb.mix': 0.38, 'reverb.shimmer': 0.1,
      'amp.level': -3.5,
    },
    macros: [
      { name: '母音 Vowel', targets: [{ id: 'filter.vowel', amount: 0.75 }, { id: 'osc2.shape', amount: 0.75 }, { id: 'amp.level', amount: -0.04 }] },
      { name: '氣聲 Breath', targets: [{ id: 'noise.level', amount: 0.25 }, { id: 'osc1.level', amount: -0.15 }] },
      { name: '人數 Voices', targets: [{ id: 'osc1.detune', amount: 0.2 }, { id: 'chorus.mix', amount: 0.3 }, { id: 'voice.spread', amount: 0.5 }] },
      { name: '天堂 Heaven', targets: [{ id: 'reverb.mix', amount: 0.3 }, { id: 'reverb.shimmer', amount: 0.35 }, { id: 'reverb.decay', amount: 0.08 }] },
    ],
    demo: 'strings',
    demoMacros: [{ index: 0, to: 0, beat: 0, beats: 3 }, { index: 3, to: 0, beat: 0, beats: 3 }, { index: 0, to: 0.75, beat: 4, beats: 8 }, { index: 3, to: 0.6, beat: 8, beats: 8 }],
  },

  // 9 ── vintage string machine
  {
    name: "String Machine '79",
    category: 'strings',
    tags: ['vintage', 'string-machine', 'analog', 'ensemble'],
    description: '七〇年代弦樂機，鋸齒波加上 BBD 合奏與緩慢相位器，復古又夢幻',
    params: {
      'osc1.unison': 2, 'osc1.detune': 0.05, 'osc1.level': 0.6,
      'osc2.on': true, 'osc2.oct': 1, 'osc2.level': 0.3,
      'filter.type': 'lp', 'filter.cutoff': 3500, 'filter.res': 0.05,
      'filter2.type': 'hp', 'filter2.cutoff': 110,
      'aenv.a': 0.12, 'aenv.d': 1, 'aenv.s': 1, 'aenv.r': 0.9, 'amp.vel': 0.2,
      'mod1.src': 'wheel', 'mod1.dst': 'filter.cutoff', 'mod1.amt': 0.12,
      'chorus.on': true, 'chorus.mode': 'ensemble', 'chorus.depth': 0.75, 'chorus.mix': 0.7,
      'phaser.on': true, 'phaser.rate': 0.12, 'phaser.depth': 0.8, 'phaser.feedback': 0.5, 'phaser.mix': 0.3,
      'reverb.on': true, 'reverb.size': 0.55, 'reverb.decay': 2.4, 'reverb.mix': 0.25,
      'eq.low': -4, 'eq.high': -2,
      'amp.level': -2,
    },
    macros: [
      { name: '亮度 Bright', targets: [{ id: 'filter.cutoff', amount: 0.2 }] },
      { name: '相位 Phaser', targets: [{ id: 'phaser.mix', amount: 0.4 }, { id: 'phaser.feedback', amount: 0.3 }, { id: 'amp.level', amount: -0.05 }] },
      { name: '八度 Octave', targets: [{ id: 'osc2.level', amount: 0.5 }, { id: 'amp.level', amount: -0.06 }] },
      { name: '空間 Space', targets: [{ id: 'reverb.mix', amount: 0.3 }, { id: 'reverb.decay', amount: 0.15 }] },
    ],
    demo: 'pad',
    demoMacros: [{ index: 1, to: 0.8, beat: 0, beats: 8 }, { index: 1, to: 0.1, beat: 10, beats: 6 }],
  },

  // 10 ── spiccato ostinato via the arpeggiator
  {
    name: 'Storm Ostinato',
    category: 'strings',
    tags: ['ostinato', 'rhythmic', 'cinematic'],
    description: '按住和弦，琶音器就奏出風暴般的十六分音符跳弓，電影配樂的緊張感一觸即發',
    params: {
      'osc1.mode': 'wavetable', 'osc1.table': 'strings', 'osc1.shape': 0.6, 'osc1.unison': 4, 'osc1.detune': 0.12, 'osc1.level': 0.9,
      'osc2.on': true, 'osc2.mode': 'wavetable', 'osc2.table': 'strings', 'osc2.shape': 0.45, 'osc2.oct': -1, 'osc2.unison': 2, 'osc2.detune': 0.1, 'osc2.level': 0.6,
      'noise.on': true, 'noise.level': 0.1, 'noise.color': -0.3, 'noise.decay': 0.05,
      'filter.cutoff': 2400, 'filter.res': 0.15, 'filter.env': 0.13, 'filter.vel': 0.2,
      'fenv.a': 0.001, 'fenv.d': 0.12, 'fenv.s': 0.2, 'fenv.r': 0.1,
      'aenv.a': 0.004, 'aenv.d': 0.16, 'aenv.s': 0.5, 'aenv.r': 0.12,
      'arp.on': true, 'arp.oct': 2, 'arp.gate': 0.55,
      'mod1.src': 'wheel', 'mod1.dst': 'filter.cutoff', 'mod1.amt': 0.12,
      'mod2.src': 'aftertouch', 'mod2.dst': 'filter.cutoff', 'mod2.amt': 0.1,
      'delay.on': true, 'delay.sync': '3/16', 'delay.feedback': 0.25, 'delay.mix': 0.12, 'delay.pingpong': 0.8, 'delay.tone': 0.4,
      'reverb.on': true, 'reverb.size': 0.7, 'reverb.decay': 2.5, 'reverb.mix': 0.22,
      'comp.amount': 0.35,
      'amp.level': 5,
    },
    macros: [
      { name: '音長 Length', targets: [{ id: 'arp.gate', amount: 0.3 }, { id: 'aenv.d', amount: 0.2 }, { id: 'aenv.s', amount: 0.2 }] },
      { name: '咬勁 Bite', targets: [{ id: 'filter.cutoff', amount: 0.05 }, { id: 'filter.env', amount: 0.08 }, { id: 'noise.level', amount: 0.12 }, { id: 'filter.res', amount: 0.2 }, { id: 'filter.drive', amount: 0.35 }] },
      { name: '音域 Range', targets: [{ id: 'arp.oct', amount: 0.34 }] },
      { name: '殿堂 Hall', targets: [{ id: 'reverb.mix', amount: 0.3 }, { id: 'reverb.decay', amount: 0.12 }] },
    ],
    demo: 'arp',
    demoMacros: [{ index: 2, to: 0, beat: 0, beats: 0.25 }, { index: 1, to: 0.9, beat: 0, beats: 8 }, { index: 1, to: 0.15, beat: 12, beats: 4 }, { index: 2, to: 1, beat: 12, beats: 0.5 }],
  },
];
